### ISSUE TITLE
Link to language docs

### ISSUE THREAD

**Issue by jcscottiii** [18F/cg-dashboard#1045]
In order to help new developers and designers on this repo, it would be helpful for them to have a set of links for them if they are going to be using a new library (React) or language (Go or Javascript)

**Comment by jonathanconway** [comment]
Not sure if this will help, but here goes!

Links for GoLang:

* [Do the tour (and the exercises)](https://tour.golang.org)
* [How to write idiomatic Go (large)](https://golang.org/doc/effective_go.html)
* [Code review basics](https://github.com/golang/go/wiki/CodeReviewComments)
* [How Go code is organised](https://talks.golang.org/2014/organizeio.slide)
* [Naming things](https://talks.golang.org/2014/names.slide)
* [Go best practices](https://peter.bourgon.org/go-best-practices-2016)
* [Advice for Go newbies](https://blog.rubylearning.com/best-practices-for-a-new-go-developer)

Links for React:

* [React docs](https://facebook.github.io/react/docs/hello-world.html)
* [Learn Pure React](https://daveceddia.com/learn-pure-react/) (Unfortunately it's a paid resource)
* [React Router docs](https://reacttraining.com/react-router/)
* [React Fundamentals course (free)](https://reacttraining.com/online/react-fundamentals)
* [Code Academy course (free)](https://www.codecademy.com/learn/react-101)
