### ISSUE TITLE
index.html template is not interpolated in testing-server

### ISSUE THREAD

**Issue by adborden** [18F/cg-dashboard#1065]
I see newrelic calls when using the testing server. This is because the NR settings are set to template variables:
```
NEW_RELIC_ID: "{{.NEW_RELIC_ID}}" || false,
```

So `window.settings.NEW_RELIC_ID` is truthy which enables New Relic when it shouldn't.

**Comment by msecret** [comment]
Thanks for looking into that, I noticed this as well but hadn't investigated the cause yet.
