### ISSUE TITLE
Remove session backend dependency and other session management tidy-up

### ISSUE THREAD

**Issue by aeijdenberg** [18F/cg-dashboard#1234]
We'd like to submit a PR to remove the dependency on Redis for a session backend. In addition to making the dashboard more complex to deploy, a database of refresh tokens is a juicy target and we'd like to avoid storing them if possible.

As background, the session currently contains basically just a serialized OAuth2 token.

In theory, we could use the gorilla session library (which is already a dependency) to simply sign and encrypt this value and rely on the browser to store it for us, however from a practical standpoint this currently fails to work because the serialized token is too large (greater than 4096 bytes) and thus won't work reliably between browsers (the gorilla library won't even try).

Newer versions of UAA (since May 2016) support [opaque tokens](https://www.cloudfoundry.org/opaque-access-tokens-cloud-foundry/) for both access and refresh tokens which are much smaller and if used make this small enough to store within the user session.

However, after experimenting with this, we found that while UAA (who issues the opaque tokens) can accept them, the CF API (`cloud_controller_ng`) currently cannot accept an opaque access token as it is built to decode and verify a JWT only and expects the access token to be in this form.

We can however use a hybrid approach. Request from UAA opaque tokens and receive an opaque refresh token and access token. We then discard the access token, and use the opaque refresh token to request a JWT access token (and discard the new JWT refresh token returned), and then store in the session the JWT access token along with the opaque refresh token, which together are small enough to remain below the session size limit giving us the best of both worlds.

Creating issue to track discussion around this - expect to see some PRs forth coming.

In addition the PRs will address a few other issues encountered along the way:

- Separation of the CSRF token key, a session authentication key, and a session encryption key.
- Actually update the access key in the session after a refresh token is fetched - currently once an access token is expired, every request will trigger a new access token be fetched, when it should be saved back into the session.
- Allow for all environment variables to be set via a user-provided-service - currently some are, some aren't, and allowing all makes deployment easier. Possibly it's distracting to put this in the same PR, but it sure made it easier for us to test so I'll likely start that way and we can split out if needed.

**Comment by jcscottiii** [comment]
@aeijdenberg this is very exciting. Looking forward to the PRs!

**Comment by aeijdenberg** [comment]
@jcscottiii - the first part if I've done it right should be entirely unexciting and can be found here in pull request #1235.

It's probably the largest change but will make the other bits easier. We found that using CUPS made it easier for us to deploy to multiple environments, so this PR allows all environment variables to be set in a common method.

**Comment by aeijdenberg** [comment]
I forgot to link to this issue before from the PR, part 2 is: https://github.com/18F/cg-dashboard/pull/1238

**Comment by jonathaningram** [comment]
@aeijdenberg with your recent change, looks like we need to improve the handling around existence of `VCAP_APPLICATION` and `VCAP_SERVICES` env vars a bit:

```
Warning: No Cloud Foundry Environment found ### @jonathaningram added: (error was because of unexpected end of JSON input)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13aa886]

goroutine 1 [running]:
github.com/18F/cg-dashboard/helpers.NewEnvLookupFromCFAppNamedService(0x0, 0x14da59f, 0xd, 0x2c)
	/Users/Jonathan/go/src/github.com/18F/cg-dashboard/helpers/env_vars.go:141 +0x26
main.startApp(0xc42001407c, 0x4, 0x0)
	/Users/Jonathan/go/src/github.com/18F/cg-dashboard/server.go:56 +0x58
main.main()
	/Users/Jonathan/go/src/github.com/18F/cg-dashboard/server.go:38 +0x195
```

Happy to fix myself if need be, just wanted to note this here - you may be cleaning this up in your next pass.

Note: this is on my local and it's straight after pulling in this change, so I've not actually tried to fix the issue, I'm really just reporting that we should be able to fix the nil pointer and possibly give a more helpful error message (e.g. "Could not find Cloud Foundry environment variables. Are VCAP_APPLICATION and VCAP_SERVICES set?") and/or `os.Exit`.

**Comment by aeijdenberg** [comment]
Thank @jonathaningram - sorry about that. Should be fixed in https://github.com/18F/cg-dashboard/pull/1242.

I don't even think it needs an error - but it does now print a warning.
