### ISSUE TITLE
Is dashboard-uaa-icon.jpg used externally or can it be removed?

### ISSUE THREAD

**Issue by jonathaningram** [18F/cg-dashboard#1266]
See https://github.com/18F/cg-dashboard/blob/master/static_src/main.js#L5:

```js
// Icon used in cg-uaa.
import './img/dashboard-uaa-icon.jpg';
```

However, searching the codebase for this image reveals no results. What does "Icon used in cg-uaa." mean?

Would be great to be able to remove this rogue asset, or at least move it to the `cg` skin if it's necessary for something in cloud.gov.

**Comment by jcscottiii** [comment]
@jonathaningram i think we can delete it. let me verify tomorrow when i get on my laptop. 
this issue describes why we needed it but i think we changed it https://github.com/18F/cg-uaa/issues/25

**Comment by pburkholder** [comment]
I don't see that it's being used anywhere in this project, and it's not been requested according to our logs. So, yeah, it can be removed.
