### ISSUE TITLE
Migrate from glide to dep

### ISSUE THREAD

**Issue by jonathaningram** [18F/cg-dashboard#1283]
@jcscottiii if I do a PR to migrate from glide to dep will you accept it? 

We've just run into a glide issue when deploying through our CI. In summary, if you kill glide part way through and end up with a corrupt vendor folder, then you try and run it again, it will not work. Since `dep` is impending, I don't think glide will be accepting contributions.

Anyway, thoughts?

**Comment by jcscottiii** [comment]
@jonathaningram YES!!! please do. I know that exact problem. it has been on my TODO since the go buildpack has dep in it now.
