### ISSUE TITLE
Error when running the quick start

### ISSUE THREAD

**Issue by hamzahamidi** [18F/cg-dashboard#1284]
I have these errors in chrome console when I run the command **docker-compose up frontend_testing_server**

Loading failed for the <script> with source “http://localhost:8001/assets/bundle.js”.  localhost:8001:58
Loading failed for the <script> with source “http://js-agent.newrelic.com/nr-spa-963.min.js”.  localhost:8001:1
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  localhost:8001

**Comment by pburkholder** [comment]
Thanks for reaching out, but I'm afraid that's not enough information for us to provide useful guidance. 

Is this still an issue for you? Do the other resources load ok?

**Comment by pburkholder** [comment]
actually, this may be related to an out-of-date webpack, which is being fixed in today's release. If you're still having trouble, try this later today.

**Comment by pburkholder** [comment]
@hamzahamidi I see what's happening. We've been running the `frontend_testing_server` after we'd already compiled our assets. So for you with a fresh checkout, indeed there's nothing there. Try this:

    docker-compose up frontend_testing_server watch

and then be patient. Once you see something like:

```
watch_1                    |       [99] ./~/css-loader!./~/cloudgov-style/css/base.css 122 kB {0} [built]
watch_1                    |         + 85 hidden modules
watch_1                    | Child extract-text-webpack-plugin:
watch_1                    |        [0] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
watch_1                    |        [1] ./~/css-loader!./static_src/css/route_form.css 1.67 kB {0} [built]
```

then you should be able to use the site at http://localhost:8001.

Please let us know if that works, and we'll update the README.

Thanks, Peter

**Comment by hamzahamidi** [comment]
It works thank you :D
