### ISSUE TITLE
How to deploy this UI in PWS

### ISSUE THREAD

**Issue by hamzahamidi** [18F/cg-dashboard#1293]
So how to deploy this UI in PWS? I read many times the documentation & I don't know where to begin. Is it even possible to deploy this UI in PWS?

**Comment by pburkholder** [comment]
In order to deploy the standard version of this you would need the UAA to grant your application permissions to manage users. In PWS you probably couldn't do that.

Since PWS already has a web dashboard, can you fill me in on what functionality you'd like cg-dashboard to provide?

Thanks, Peter

**Comment by hamzahamidi** [comment]
Thank you for your answer. I would like to deploy a demo that contains all of cg-board functionalities (market place, log streams ,ssh ...)  so that my team & I can study it & maybe consider it for our PaaS.

**Comment by pburkholder** [comment]
@jonathaningram Would you have any tips for Hamza? I'm still coming up to speed on cg-dashboard.

**Comment by mogul** [comment]
> I would like to deploy a demo that contains all of cg-board functionalities (market place, log streams ,ssh ...) so that my team & I can study it & maybe consider it for our PaaS.

Note that `cg-dashboard` doesn't have a web-based ssh capability today.

**Comment by hamzahamidi** [comment]
What about the other functionalities like the market place & Log stream?

**Comment by jonathaningram** [comment]
I'm going to defer to @aeijdenberg as my own experience with PWS is limited. Any ideas @aeijdenberg ?

**Comment by aeijdenberg** [comment]
The app is a pretty standard CloudFoundry app, and as such should run where ever a CF app can normally be deployed.  It does however need two UAA clients* - one to allow SSO for normal users (a "3-legged flow") and one to act on it's on behalf ("2-legged" - or "client_credentials" in UAA-speak)

I've not used PWS, so I'm not sure what ability it gives to create your own UAA clients. I think if you can get past that, you'll be able to run the app fine.

\* I think of these as distinct clients, although I think one is currently used for both purposes. Even if you can't get `client_credentials` grant, if you can configure the client for just an `authorization_code,refresh_token` flow, then you'll be able to use most part of the application (those that act on behalf of the logged in user).

Hope that helps a bit.

**Comment by pburkholder** [comment]
I should point out that doing the Full Deploy as described in devtools/docker-setup.md will let you exercise all the current functionality of cg-dashboard with cloudfoundry/uaa bundled into _cfdev_.

It takes up to an hour for all the code to download and set itself up, but it may provide a better demonstration of the dashboard functionality than trying to run it with PWS where you may be limited in setting up your UAA clients. More importantly, you'll be spared the pain of figuring out how to work with PWS UAA -- which you should save until you're working with the CF/UAA at Orange.

You should also look at the Stratos UI released by Suse recently. The demo seems to include  functionality that this project doesn't currently have.

**Comment by hamzahamidi** [comment]
Thank you all for your detailed answers. I 'll follow the instruction. If anything comes up, I'll be back here. In the mean time I'll close the issue.
