### ISSUE TITLE
Password reset workflow improvements

### ISSUE THREAD

**Issue by hollyallen** [18F/cg-dashboard#136]
As a user, the reset password workflow is frustrating. 
1. The requirements for a new password are not in the email, nor on the page where you are entering a new password. Instead, they are doled out to you piecemeal based on which constraints you have violated.
2. Apparently once you have "used" a password reset link once you cannot use it again. That fact that is not immediately apparent if you click on the link again and put in a conforming password; the new password has not actually been accepted but no error is given.

**Comment by jcscottiii** [comment]
Part 1 has been solved by this: https://trello.com/c/tc2CAVkh/439-ui-changing-setting-password-should-show-requirements-beforehand

**Comment by hollyallen** [comment]
Thanks! The one note I have is that the term "special letters" is a bit strange.

**Comment by suprenant** [comment]
@mogul we're closing this up – please reopen if you think it hasn't been sufficiently covered.
