### ISSUE TITLE
Eliminate deck tech debt

### ISSUE THREAD

**Issue by mogul** [18F/cg-dashboard#178]
In order for the cloud.gov development team to write consistent, clean, tested code the cloud.gov front end codebase should not have tech debt older then a year.

Acceptance criteria
- [ ] Any major front end libraries should not be using versions more then a year old
- [ ] Developers should be able to run a suite of linting, unit tests and functional tests across the codebase.
- [ ] There should be documentation on coding workflow and standards.

**Comment by jcscottiii** [comment]
have these specified in favro
