### ISSUE TITLE
Searchable docs

### ISSUE THREAD

**Issue by mogul** [18F/cg-dashboard#236]
Visitors can search cloud.gov content from the global navigation

Benefits

- Help users find existing documentation when it's not obvious to them how to navigate toward what they're looking for

See [the task list for implementing search.usa.gov](http://search.digitalgov.gov/blog/go-live.html), which we've already provisioned.

**Comment by suprenant** [comment]
This is redundant with https://github.com/18F/cg-product/issues/194. Moving the information from this issue there and closing this up
