### ISSUE TITLE
Functional tests should run with cleaned data

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#262]
In order for developers to run and write functional tests in a repeatable environment, any data associated with the tests should be reset for each test.

There are probably different ways to do this, and I'm not sure what's best, but essentially the result of one test shouldn't change the result of another. Please put ideas in this issue for how to do this.

**Comment by msecret** [comment]
An idea:
Write functions that ensure each tests brings back the state of the data to the original.

I don't see how this could be done in a safe way, because even if the funcitons don't use the UI to do this, network requests could fail.

**Comment by jeremiak** [comment]
@jcscottiii I wanted to get your opinion on an approach for this. I was thinking of creating a bunch of fixtures `.json` files and put them at appropriate file paths to be served up by something like [`http-server`](//npm.im/http-server).

I was imaging that it would then set `CONSOLE_API_URL` to equal something like `http//127.0.0.1:8080/` so that all of the Go endpoints would still work but would return predictable data.

Thoughts/concerns?

**Comment by jcscottiii** [comment]
@jeremiak i like where you're going with this. you'll need some logic in there to represent state as to which fixture to server for example if we do `GET /v2/services` than create a service and do `GET /v2/services`. I would do that.

There are some other options i've been eying such as https://github.com/tchughesiv/cf-mini/ (needs to be updated) and https://github.com/pivotal-cf/pcfdev (takes foreverrrrrrrrr to download and start)

**Comment by msecret** [comment]
An additional thing to explore here: Can we make these functional tests runnable by somebody outside of 18F, as in they don't need any secrets sent to them?

**Comment by jeremiak** [comment]
I'm going to do a two hour experiment with [smocks](https://www.npmjs.com/package/smocks) to get a better estimate of the right way to go about this and the likely time investment.

**Comment by jeremiak** [comment]
I've got a basic sketch of an idea at 5415e1561914d866ded6e338d79855e5878a1914

**Comment by jeremiak** [comment]
Continuing off that sketch, and as of now I think the only view left to mock endpoints for is the Marketplace. Seems to be working pretty well, and I think we could now have future front end designers/devs contribute to the app without having to get any authentication variables set up nor deal with Go!
Obviously, if they're doing sustained work on the app it would be best to set them up properly but maybe this can help with getting other folks in and helping with smaller features/bugs/issuse.

**Comment by msecret** [comment]
Relies on #633

**Comment by suprenant** [comment]
We're feeling this is larger – will break it up more.

**Comment by adborden** [comment]
I think the remainder of this work is really covered by https://github.com/18F/cg-dashboard/issues/680

**Comment by suprenant** [comment]
@adborden ok, sounds good. Will close this up. @msecret can you please confirm?
