### ISSUE TITLE
Investigate permissions needed for UAA client

### ISSUE THREAD

**Issue by afeld** [18F/cg-dashboard#340]
Looking at [the setup instructions](https://github.com/18F/cg-deck#create-a-client-with-uaac), I was a bit surprised to see the level of permissions the client credentials receive. We should look into whether all of those are necessary.

/cc @18F/cloud-gov-ops

**Comment by suprenant** [comment]
@mogul we're pulling Navigator from this one. Do you want to triage from here?

**Comment by mogul** [comment]
I think @jcscottiii fixed it in the PR referenced above.
