### ISSUE TITLE
Add summary and caption attributes to tables

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#364]
In order for users to understand the tables better, there should be summary tags and caption elements for each of them.

> If this table is a data table, consider using the summary attribute of the table element to give an overview of this table.
> 
> If this table is a data table, consider using a caption element to the table element to identify this table.

**Comment by msecret** [comment]
@brittag if you're interested and have time, you could help come up with the content for these.

**Comment by jeremiak** [comment]
Acceptance criteria:
- [ ] Every `<table>` should have either a summary or a caption attribute
