### ISSUE TITLE
directory structure for clone

### ISSUE THREAD

**Issue by prabhuinbarajan** [18F/cg-dashboard#386]
i am a new user trying to follow instructions to setup cg-deck on my local mac.

seems like the below directory structure seems to be a critical factor to make this work
mkdir -p src/github.com/18F/
git clone https://github.com/18F/cg-deck.git src/github.com/18F/
export GOPATH=$GOPATH:.

am i doing anything wrong?

**Comment by msecret** [comment]
@prabhuinbarajan that's definitely how I've set the repo up, and is part of the `golang` system to set up projects. That being said, we're using a new go dependency manager called [glide](https://github.com/Masterminds/glide), which I **thing** means you don't need that structure anymore. Glide does require you use go > 1.5 and set `GO15VENDOREXPERIMENT=1` in your environment. You can read more on the [Glide install section](https://github.com/Masterminds/glide#install).

We're working on providing a method of working with the deck that doesn't require go or UAA, will update when that is ready.

**Comment by jeremiak** [comment]
Hey @prabhuinbarajan, I'm not super good with Go (yet, hopefully) but I think you'll want your GOPATH to point to the parent directory of `src`.

Please post back here if it still doesn't work, we'd like to make sure the instructions and documentation are sufficient for anybody to get started.

To that end, we've got an idea for a much easier (Node based) way to get started and make quick changes. Check out [this new section of `README.md`](https://github.com/18F/cg-deck/tree/staging-alpha#run-locally-without-needing-go) and let us know what you think.

**Comment by prabhuinbarajan** [comment]
@jeremiak - i did that experiment. i think the gopath is trying to find the controllers , helper and other cg-deck components under src/github.com/18F/cg-deck. i ended up cloning the directory structure under github.com/18F/cg-deck. its not a big deal, but might be helpful if the documentation pointed that out.
the new README based on node seems promising , I will give this a spin and post the results.
Thanks
Prabhu

**Comment by adborden** [comment]
@prabhuinbarajan did you end up getting back to this? How did it go?

**Comment by jcscottiii** [comment]
try https://github.com/18F/cg-dashboard/blob/master/devtools/docker-setup.md @prabhuinbarajan
