### ISSUE TITLE
Build prototype of next dashboard iteration

### ISSUE THREAD

**Issue by vz3** [18F/cg-dashboard#416]
Initial prototype will focus on activity log.

Acceptance criteria:
- Clickable InVision prototype
- Show full user path from dashboard to seeing an error in their app.
- Should be at a state in which it can be tested by users, with a representation of some basic additional functionality so that usability testing won't be overly hand holdy.
- Prototype should have clickable items that do not lead to a success state for testing.

**Comment by thisisdano** [comment]
Sketch files from ideation session + variations on that theme.
[00-cg-dash-prototype.zip](https://github.com/18F/cg-deck/files/344046/00-cg-dash-prototype.zip)


- - -

![cg-dash-sketch-exercise 2x](https://cloud.githubusercontent.com/assets/11464021/16532441/dbb31bf2-3f86-11e6-99fe-4b2b3b894385.png)
<img width="488" alt="screen shot 2016-07-01 at 12 25 33 pm" src="https://cloud.githubusercontent.com/assets/11464021/16532473/01083d42-3f87-11e6-8e49-34a5b5389215.png">
<img width="559" alt="screen shot 2016-07-01 at 12 25 49 pm" src="https://cloud.githubusercontent.com/assets/11464021/16532476/055240aa-3f87-11e6-8d4f-2be218d1aaa6.png">

- - -

Invision here: https://invis.io/MA7U5XOZJ
Custom typeface for Sketch files here: https://github.com/18F/cg-design/blob/master/18Franklin-v0.06.zip

**Comment by thisisdano** [comment]
Newest Sketch file here:
[001-cg-dash-prototype.zip](https://github.com/18F/cg-deck/files/348354/001-cg-dash-prototype.zip)

Invision constantly in flux! (Same link as before.)
I'm working on an app page and an app/logs view today.

**Comment by msecret** [comment]
Last update on this was 7 days ago, is this done?

**Comment by mogul** [comment]
> - Should be at a state in which it can be tested by users, with a representation of some basic additional functionality so that usability testing won't be overly hand holdy.

Presumably now that we're actively testing the mocks in Invision this issue should be closed and we should be opening a new one to deal with findings, right @thisisdano and @vz3?

**Comment by vz3** [comment]
sorry catching up on Git, this is complete yes.
