### ISSUE TITLE
App pages should link to documentation explaining cloud.gov logging

### ISSUE THREAD

**Issue by brittag** [18F/cg-dashboard#417]
When I look at https://console.cloud.gov for my tiny testing "hello world" app, I see one item in the event log, which makes sense:

![screen shot 2016-07-01 at 1 13 01 pm](https://cloud.githubusercontent.com/assets/391313/16533467/bc620694-3f8d-11e6-931f-4d009d02127d.png)

When I look at https://dashboard.cloud.gov, go to the app, and click the "Event are currently available at logs.cloud.gov" link, I see no events for my tiny app:

![screen shot 2016-07-01 at 1 13 12 pm](https://cloud.githubusercontent.com/assets/391313/16533507/f689e486-3f8d-11e6-9bd2-6235d5bb4ae8.png)

As a user, I would expect to see the same results in both systems.

**Comment by brittag** [comment]
Status - we should verify whether this is a bug, including by finding out whether this mismatch happens for other people's apps too.

**Comment by mogul** [comment]
What was the time between looking in console.cloud.gov and looking at logs.cloud.gov? There can be some delay between logs appearing in the CF logs buffer (which is small, accessible via `cf logs`, and also supplies that portion of `console.cloud.gov`) and appearing in logs.cloud.gov (which is effectively infinite, and is only accessed via the web). If you looked in `logs.cloud.gov` immediately after seeing the log entry appear in `console.cloud.gov`, it might not have made it there yet. Also, can you search `logs.cloud.gov` (when it's back up... :( ) to see if the entry is there, eg it appeared later?

**Comment by brittag** [comment]
@mogul The event is from June 9, and I looked at both console.cloud.gov and logs.cloud.gov on July 1, so I suspect the problem isn't an ordinary logs delay.

But what's the average range of delay (when everything is working as expected)? That might be helpful for me to add to https://docs.cloud.gov/apps/logs/ as a note.

**Comment by mogul** [comment]
I have no explanation for the difference, and no insight into the actual delay (although I believe evidence-free that it's on the order of a minute or so). Might have to wait for @LinuxBozo to return from vacay for more info on both counts.

**Comment by brittag** [comment]
Talked to Adam and learned a few things!

This problem (events/logs not matching) is not an issue with the Dashboard's links to logs.cloud.gov. These links seem fine. Instead, the underlying logging system seems to have some issues.

To resolve this confusion for future users, I'm going to document this a little bit:

- [ ] Add a link on this Dashboard page to https://docs.cloud.gov/apps/logs/ for more information about cloud.gov's logging system.
- [ ] On that docs page, set expectations in some appropriate spot: Events/logs (as displayed by `cf logs`) should show up on logs.cloud.gov in less than a minute. If users find that this isn't happening, there may be an issue on our end causing a delay. They should check our cloud.gov status page, and if nothing is reported there about logging issues, ask our support (email or Slack).

**Comment by brittag** [comment]
Also that docs page should probably talk about `cf events` somehow.

**Comment by suprenant** [comment]
We're thinking this is done except for the link to recent activity. Leaving this open for now
