### ISSUE TITLE
There's no clear visual distinction between the dashboard pages and docs pages

### ISSUE THREAD

**Issue by wslack** [18F/cg-dashboard#447]
See title. The sites are really close in look, but not function, so its a little confusing.

**Comment by brittag** [comment]
I suspect we should solve this generally for both the dashboard and the docs -- when you’re on any page on both, you should have a clear visual indication about where you are. This might be as simple as fitting in a top header saying "Documentation" or "Dashboard".

**Comment by thisisdano** [comment]
This issue is a little ambiguous, but we're working through what I think are its implications here: https://github.com/18F/cg-dashboard/issues/712
