### ISSUE TITLE
Placeholder text before content is loaded is confusing (and sometimes content doesn't load)

### ISSUE THREAD

**Issue by brittag** [18F/cg-dashboard#448]
I think we're working on state problems in a different issue, but I'm not sure if this specific behavior is getting tracked:

When I load a space page, there's sometimes a flash of "No apps" before my app list loads. That text is incorrect since I do have apps - they're just not loaded yet. I suspect we can't solve this just by updating that text though, since that probably also needs to display if you actually have no apps.

It looks like this:

![screen shot 2016-07-07 at 4 20 50 pm](https://cloud.githubusercontent.com/assets/391313/16673040/7a9fd50c-445f-11e6-8bef-c1a1ac56507d.png)

And I'm seeing that right now on this space page despite having an app. My app list just didn't end up loading. If I try again, it loads ok - this is intermittent.

**Comment by brittag** [comment]
As we work on this, we should test this with a superuser cloud.gov account that has access to all spaces (or a simulated equivalent of that account), since any lag/loading/state problems will especially show up for them.

**Comment by msecret** [comment]
We did work on loading states, I think there may be a problem with this specific apps table. I'm looking into it in the sidenav PR

**Comment by msecret** [comment]
@jeremiak mentioned he is looking at this.

**Comment by jeremiak** [comment]
I actually think that @msecret might have fixed this in c4e96f73e867432f6066a6fb8f9bc764c207b098

@brittag can you verify that you are still seeing this problem?

**Comment by brittag** [comment]
When I look at a local copy of the latest master, I see a flash of "Loading apps" before my app list loads, but that's less confusing than "No apps".

I'm not sure whether the rest of this is fixed (such as whether this will behave reasonably quickly if you have access to tons of orgs/spaces/apps) since my local test copy just has a few of each.

**Comment by brittag** [comment]
I found a reproducible "sometimes content doesn't load" problem! 🎉 🎉 🎉 🎉 🎉 Here are my steps, running the [lightweight demo version](https://github.com/18F/cg-deck#run-locally-without-needing-go):

1. Open a fresh browser tab with http://localhost:8000/
2. Click the first "Spaces" on the left
3. Click the first space ("space-space-guid-one")
4. Under Apps, it says "No apps". This is incorrect.
5. Verify that it's incorrect - go to "space-space-guid-two" and then click back to "space-space-guid-one", and it shows a list of apps.

**Comment by msecret** [comment]
Yea I saw this too even though I thought I fixed it :(. I'm not sure what's wrong with it this time.

**Comment by jeremiak** [comment]
@brittag I'm investigating this but I don't see the same end result. With the current `master` (ad5a94abee88c54c837c1bcdcdbd553f10d430cb) I see the apps load when I'm using the lightweight server and the Go server :/

I do see the flash of content, unreliably, on the production version of the dashboard so I think I know what you're talking about. I'm not sure if 8a290f4 is the solution but it is another potential suspect.

If you can still reproduce the test case maybe you can try and see if the `jk-no-apps` fixes the problem?

**Comment by brittag** [comment]
OK, I tried these steps again with the current `master` (ad5a94abee88c54c837c1bcdcdbd553f10d430cb), and I no longer see that "No apps" problem!

I'm getting other mild weirdness (brief but slightly distracting flash of "Loading apps" before my apps load + all of my orgs are just called "org-name" instead of their proper fake test names), but I think this issue is ok to close for now.

**Comment by brittag** [comment]
(...although I'd be inclined to leave it open until we test this behavior with a cloud.gov account that has access to tons of orgs/spaces/apps, since I suspect any lingering intermittent loading problems will show up with that kind of account.)

**Comment by brittag** [comment]
I recruited Bret to test this with the current version of https://dashboard.cloud.gov/ since he has access to tons of orgs/spaces/apps. I watched him click around, and we noticed a few lingering latency/state/loading problems:

- [ ] When viewing a space, I sometimes see a brief flash of "Space not found" -> then the space loads.
- [ ] When viewing a space, I sometimes see a brief flash of "Loading apps" -> then a brief flash of "No apps" -> then the list of apps loads.
- [ ] When viewing a space's list of users, I sometimes see a brief flash of "No users" -> then the list of users appears.
- [ ] When viewing a space, I occasionally get "No apps", even though that space has apps. (Only saw this once.)

In general, we should make sure that copy isn't contradicting reality (it shouldn't say "no x" or "x not found" if the status is "loading x").

**Comment by dlapiduz** [comment]
👍 Here are some screenshots... 
<img width="1232" alt="screen shot 2016-07-15 at 9 36 05 am" src="https://cloud.githubusercontent.com/assets/4604/16877929/0f4041ae-4a70-11e6-89c2-02591961b101.png">
<img width="1232" alt="screen shot 2016-07-15 at 9 35 54 am" src="https://cloud.githubusercontent.com/assets/4604/16877930/0f407110-4a70-11e6-8dd3-4b7caefbac74.png">

**Comment by jeremiak** [comment]
@dlapiduz Could you try with the `jk-loading-bugs` branch?

I'll be in the SF office tomorrow afternoon so maybe I can recruit @mogul to try it on that branch and see if the problem persists.

**Comment by brittag** [comment]
If I look at the latest master (https://github.com/18F/cg-deck/commit/1bd876ad79dbf5dbccac5fa0e4bdcf1466a90ea0) locally (using the demo server) or on dashboard-master.cloud.gov, and I throttle my network connection to “GPRS” in Chrome, I can still reproduce this behavior:

* Loading a space: "Space not found" -> then space info loads.
* Loading users: "Loading users" -> "No users" -> then users load.

**Comment by brittag** [comment]
Here's a specific set of steps to reproduce (with network throttling), in case this is helpful:

"Space not found":
1. Open a fresh browser tab with https://dashboard-master.cloud.gov/
2. Click "sandbox" org in sidebar, click "britta.gustafson" space. I see "Space not found" and then my space loads.

"No users":
1. Open a fresh browser tab with https://dashboard-master.cloud.gov/
2. Click "sandbox" org in sidebar.
3. Then, without waiting for anything to fully load, click "britta.gustafson" space, then "User management", then "All organization users". I see "Loading users", then "No users", and then my org users load.
