### ISSUE TITLE
Add component for page info snippets rather then `<em>` tags

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#450]
There should be a separate React component and style for the content snippets we're putting on the pages.

**Comment by el-mapache** [comment]
[@Andrew Suprenant] I searched through the codebase and found one instance of `<em>` tags being used, I think its safe to close and delete this ticket

**Comment by suprenant** [comment]
[@el-mapache — Adam Biagianti] noted and closed, thank you.
