### ISSUE TITLE
Set up ways to test dashboard with realistic fake data

### ISSUE THREAD

**Issue by brittag** [18F/cg-dashboard#454]
As a developer, I want to be able to use an environment with test data so I can test states (e.g. broken services) instances without impacting our other environments.

Acceptance criteria:

- [ ] URL that uses fake data to create such an environment

__

Let's have options for designers/developers to try the Dashboard with lots of fake data, to help us find latency + state problems (along with UI problems) before users run into them, especially problems for superusers who have access to lots of orgs/spaces/apps (since those are key users who need to be able to use the Dashboard effectively).

This should include test data for all the features - service instances, routes, space users with a variety of permissions, org users with a variety of permissions, etc.

This should be real-looking data (such as non-sensitive real data copied over from real accounts).

For example, the frontend test setup at https://github.com/18F/cg-deck#run-locally-without-needing-go has a little bit of fake data in it, but let's add more!

**Comment by thisisdano** [comment]
I love this idea. A way to modify data/roles to model how the system works for different kinds of users and situations would be an amazing tool.

**Comment by line47** [comment]
I'd like to see cloud.gov test data for the following:

- [ ] recent activities
- [ ] bound service instances
- [ ] bound routes
