### ISSUE TITLE
Show indication that a service instance delete request is in progress

### ISSUE THREAD

**Issue by brittag** [18F/cg-dashboard#459]
When I go to a list of service instances for a space, and I click "Delete Instance" and then "Confirm Delete", I don't get visual feedback the the service is being deleted

I would expect to see a loading indicator letting me know a request is in progress.

**Comment by vrajmohan** [comment]
My experience with this issue was slightly worse:
1. The "Confirm delete" dialog did not go away after clicking it.
2. The service instance was **not deleted**.

**Comment by brittag** [comment]
Checking in on this, this is a bit better now - when I click "Delete Instance" and "Confirm delete", after a moment the dialog disappears. After a refresh, they remain deleted.

**Comment by suprenant** [comment]
Thinking of waiting on this until this page is further developed.

**Comment by brittag** [comment]
This still happens for me - when I click "Delete Instance" and "Confirm delete", after a moment the dialog disappears, and after a refresh, the service instance is back.

**Comment by brittag** [comment]
This still happens for me - when I click "Delete Instance" and "Confirm delete", after a moment the dialog disappears, and after a refresh, the service instance is back.

**Comment by suprenant** [comment]
Github issue for reference: https://github.com/18F/cg-dashboard/issues/459

**Comment by suprenant** [comment]
test

**Comment by el-mapache** [comment]
[@suprenant - Andrew Suprenant] Not sure if the semantics matter to you, but I would actually call this a feature, not a bug. Deleting service instances works fine,  but no feedback is provided to the user  (i.e. a loading icon) while the request is in flight. 

The description of the ticket is out-of-date, the service being deleted is removed and the user sees this reflected on the front end without requiring a page refresh.

**Comment by suprenant** [comment]
[@el-mapache — Adam Biagianti] semantics matter – I removed the bug label, thanks. Can you please update the description of the ticket if it's out of date?

If you have further questions or want to pair on this, let me know.

**Comment by el-mapache** [comment]
Heads up! This ticket has been altered. Previously the UI didn't report that service instances were being deleted.

**Comment by el-mapache** [comment]
IP PR here: https://github.com/18F/cg-dashboard/pull/1159

**Comment by suprenant** [comment]
Accepted – looks good!
