### ISSUE TITLE
Add anything currently only available on console.cloud.gov that the Director of Infrastructure needs

### ISSUE THREAD

**Issue by brittag** [18F/cg-dashboard#460]
In order for 18F's director of infrastructure to work efficiently, he needs to be able to use an effective web UI for key cloud.gov-related tasks. Currently console.cloud.gov is serving those needs adequately, but dashboard.cloud.gov is not quite serving them.

We can probably keep up console.cloud.gov for as long as we need to, but fixing these things should be part of the plan for dashboard.cloud.gov. So, we need to:
- [ ] Gather a list of the problems and/or missing features that are blocking him, and gather a list of the "nice to have" things that aren't blockers but are preferred.
- [ ] Address those issues.
- [ ] Check with him to make sure there are no more blockers, then turn off console.cloud.gov.

@NoahKunin, as the next step, can you provide a brief list? My current understanding is:

- [x] Make sure route information is displayed accurately/comprehensively (matching the old Deck). Related: https://github.com/18F/cg-deck/issues/468
- [ ] Fix up the loading state problems tracked at https://github.com/18F/cg-deck/issues/448 - so that even when using an account with access to lots of orgs/spaces/apps, it's not frustrating to use the Dashboard.

(Slack discussion for Liberator team reference - https://18f.slack.com/archives/cloud-gov-liberator/p1467933286001814 )

**Comment by msecret** [comment]
I think I'd like to move this to the https://github.com/18F/cg-product/issues/193 as the only known thing to fix on this issue now is loading state. This would allow us to close out the launch of the refactor. @brittag does that make sense?

**Comment by brittag** [comment]
That makes sense to me! Let's close this one and open a new issue under "Improve deck utility" with a fresh summary of the task - it's probably shifted since this issue. Something like "Review Dashboard with Infrastructure team to identify improvements they need".

**Comment by brittag** [comment]
(Or just moving this one seems fine to me too!)

**Comment by msecret** [comment]
Moved to #531
