### ISSUE TITLE
Share analytics on use, performance and errors with the team

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#472]
In order for cloud.gov team members to have visibility into how users are using the dashboard, there should be a way for these analytics to be shared across the team.

From 07/13/2016 sprint retro.

**Comment by brittag** [comment]
I made a quick guide for how team members can view analytics for both the old Deck and the new Dashboard: https://docs.google.com/document/d/1gSbP2ak2a3QLpCZIF_KlbQ2QHE6RjDI-7ZnnrJZvMDE/edit

**Comment by msecret** [comment]
I created a document https://docs.google.com/document/d/1jUHbpaiGlLA9B04yqFos06Ij2nIQAcjoRr7X3_o9ayQ/edit (GSA only sorry) to track data people are interested in learning. This could help me determine dashboards to make.

**Comment by msecret** [comment]
I have some different ideas in how to ensure this data is accessible to the team:

- Create dashboards in New Relic and Google Analytics that are easily shareable with the team
- Write a concise newsletter, bi-weekly or monthly that does some analysis of the data and displays some quick tidbits about what was found. Then link to the data. This newsletter would likely go out to the whole cloud.gov internal team.
- Have a bi-weekly meeting, with the cloud.gov internal team where recent analytics tidbits are presented, and then discussed.
