### ISSUE TITLE
Get general feedback from 18F developers on the dashboard

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#474]
In order for the cloud.gov liberator team to understand bugs people are having OR missing/incompletely functionality OR general problems with the dashboard, there should be a feedback/whine/AMA session with 18F developers about the dashboard.

**Comment by jeremiak** [comment]
Acceptance criteria:
- [ ] A short meeting (15-20 minutes) or a small series of meetings set up with developers who use the dashboard to solicit their bugs and feedback

**Comment by jeremiak** [comment]
Per @brittag's suggestion, one of the first things we can do is get a #cloud-gov-feedback channel set up so that we have a place to ask questions of users

**Comment by jeremiak** [comment]
I created the #cloud-gov-feedback Slack channel and will start inviting folks there.

**Comment by suprenant** [comment]
We did some of these. Closing this up.
