### ISSUE TITLE
In the sidebar, I should be able to collapse an org

### ISSUE THREAD

**Issue by brittag** [18F/cg-dashboard#481]
If you have access to lots of orgs and spaces (such as org admins who can see everyone's sandbox spaces), it's harder to navigate the sidebar to find what you want, since there's no way to collapse an org's list of spaces in the sidebar.

This may be a design problem that needs to just wait for the next iteration of Dashboard navigation.

**Comment by msecret** [comment]
Yea I'm responsible for this one, we had originally planned to have you collapse an org if you clicked on it while it was expanded.

The technical problem here is that I'm calling the menu toggle on the inital load of every page in the router, so now there's not distinction of when you're toggling the menu vs just setting the org on load. I think a fix is to use a different action (which we actually already have `changeCurrentOrg`, which is unused) which we can call to set the initial state of the org on routes. Another option would be to ensure each main page UI can take the current Org and potential space as params and set them there (including the sidebar).

So it's not a super simple solution, but definitely doable.
