### ISSUE TITLE
Finish Deck -> Dashboard switchover

### ISSUE THREAD

**Issue by brittag** [18F/cg-dashboard#485]
In order for cloud.gov users to consistently find and use an actively-maintained cloud.gov web UI, we need to clean up places where we link to the old Deck (or call it the Deck), and then we need to close down the old Deck after we make the current Dashboard match required missing functionality. This is a followup to https://github.com/18F/cg-deck/issues/333.

To do:

- [x] Update 18f/cg-uaa to redirect to dashboard.cloud.gov rather then console.cloud.gov (https://github.com/18F/cg-uaa/issues/25).
- [x] Redirect https://github.com/18F/cg-deck to https://github.com/18F/cg-dashboard for consistent branding, and update the readme to reflect the name (https://github.com/18F/cg-deck/issues/412).
- [x] Update docs page at https://docs.cloud.gov/ops/repos/ to reflect "Dashboard" name and new repo link.

To do after we decide that console.cloud.gov can be closed (which depends on resolving https://github.com/18F/cg-deck/issues/460):

- [ ] Redirect console.cloud.gov to dashboard.cloud.gov.
- [ ] Remove update note from the top of dashboard.cloud.gov.

**Comment by brittag** [comment]
Tiny additional thing:

- [ ] The <title> of the page is currently "Cloud.gov Deck" - let's switch it to "cloud.gov Dashboard".

**Comment by msecret** [comment]
Moved to #531
