### ISSUE TITLE
Slightly confusing "Date Created" column on users list

### ISSUE THREAD

**Issue by brittag** [18F/cg-dashboard#507]
When I gave a teammate a role on my space today, I was mildly confused by the "Date Created" line on my space users list:

![screen shot 2016-07-21 at 3 42 48 pm](https://cloud.githubusercontent.com/assets/391313/17041308/272d5d08-4f5a-11e6-8c4d-9bb6e43dd6ee.png)

It displays the date his cloud.gov account was created (last year), but in context I expected this to show the date that I added him to my space (today). I'm not sure what the right information to display here would be. For context: console.cloud.gov has this same "Date Created" behavior. The CLI doesn't show a date when ask for a list of space users (`cf space-users sandbox britta.gustafson`).

A few options:
- Change this to "Date Account Created" and leave the info there
- Remove this column
- Change this to "Date Modified" and change the info to be the date that the user's role as modified

I don't think this is a high priority - just noting it in case other people have ideas.

**Comment by msecret** [comment]
Thanks for filling @brittag . I looked into the API responses from the API, and there is an `updated` at for every user and user role, but it's always missing the actual data. So looks like option 1 or 2 are only possible right now.

Additionally, it might be good to learn why updated at is always empty, it could be potentially useful debugging info for our team and our users.

**Comment by jcscottiii** [comment]
It was addressed a while ago. just going to archive it
