### ISSUE TITLE
Add link to routes section

### ISSUE THREAD

**Issue by dlapiduz** [18F/cg-dashboard#514]
Would it make sense to add links for each route? It'd be great to test them

**Comment by jeremiak** [comment]
Acceptance criteria:

- [ ] A dashboard user should be able to open a route in a new tab

**Comment by suprenant** [comment]
@msecret is this issue still relevant given our current work with routes?

**Comment by suprenant** [comment]
@vz3 @thisisdano will do a design review to consider how edit button will work, carat size/link type, etc.

**Comment by thisisdano** [comment]
I might suggest simply adding an underline to active routes.

**Comment by suprenant** [comment]
@msecret just talked to @vz3, he's good with the above approach, so you should be good to go here. Please let us know if you need anything else to move on this.

**Comment by suprenant** [comment]
in PR
