### ISSUE TITLE
Activity log for cloud foundry events per application

### ISSUE THREAD

**Issue by jeremiak** [18F/cg-dashboard#515]
In order for developers to troubleshoot their applications, they need to understand what recent system events occurred.

Acceptance criteria:
- [ ] An activity list of [platform events](https://apidocs.cloudfoundry.org/226/events/list_all_events.html) with timestamps
- [ ] Timestamps should be in the format of "Mar 09 2017   05:17:24"
- [ ] Crash events should be prominent
- [ ] Any changes due to user activity (quota changes, services bound, ssh logins, etc) should be prominent but different from crash events

**Comment by jeremiak** [comment]
@vz3 Can you add the design comps you showed me earlier to this issue so I can continue to build against them?

**Comment by vz3** [comment]
## Pattern
![activity log](https://cloud.githubusercontent.com/assets/582918/17533889/c7a35b80-5e54-11e6-8a15-2ba037e5aefc.png)

## Example
![activity log - example](https://cloud.githubusercontent.com/assets/582918/17533888/c796136c-5e54-11e6-84c2-9624a754f73d.png)

**Comment by vz3** [comment]
Quick iteration on this:
-Removes background color band.
-Removed glyph for more subtle visual element.
-Bolded text for priority events.
-Removes redundant dates: date should only be showed in first instance. (Need to validate usability on this)

![activity log](https://cloud.githubusercontent.com/assets/582918/17566451/6a05a450-5f09-11e6-8ccf-5bf8f8e764a2.png)
