### ISSUE TITLE
Panel components for app view

### ISSUE THREAD

**Issue by jeremiak** [18F/cg-dashboard#516]
In order for developers to manage their applications, they need to be able to view and adjust:
* Routes
* Scale
* Services

Acceptance criteria: 
- [ ] A panel organism should be created in cloudgov-style
- [ ] The panel should expand to occupy the full width or share width with a second panel
- [ ] The panel should be visually grouped together, such as with a black border
- [ ] The panel should have subsections that are clearly labeled

**Comment by msecret** [comment]
Plan on doing a sketch session for this.

**Comment by vz3** [comment]
@jeremiak Is there anything else devs needs to be able to view/edit in this view? Just routes/services (I assume we're getting rid of scale)? Should we create content to point people to the manifest+documentation?

Also what's a typical number of routes? Is there one?

**Comment by mogul** [comment]
Typically you'll only see about one route per app in the space. And most spaces we've seen only have an app or two in them.

**Comment by msecret** [comment]
@vz3 I think this story is more focused on the shared "panel" organism that has to be designed for things like routes, services, and scale. Those things are separate stories.
