### ISSUE TITLE
View services in a panel

### ISSUE THREAD

**Issue by jeremiak** [18F/cg-dashboard#518]
In order for developers to keep their apps running, they need to know which services are currently bound, which are available to be bound, and the size of each service.

Acceptance criteria:
- [ ] The panel should show the service limit per the org/space quota
- [ ] The panel should clearly show the number of currently bound services
- [ ] The panel should clearly show bound service instances with an icon of that service for ease of recognition
- [ ] The panel should show currently unbound service instances that can be added to the application

**Comment by msecret** [comment]
Based on mockups here: https://github.com/18F/cg-design/issues/5#issuecomment-241795547 both view and edit functionality is a little too much work for 2-3 days of work, so I'm making this story about the view aspect.

**Comment by msecret** [comment]
How to get the data:

Get all bound services to an app:
`GET /v2/apps/$app_guid/service_bindings`

Which gives `service_instance_guid`.

Get the full service instance from the service bindings
`GET /v2/service_instances/$service_instance_guid`

Get all unbound services for the space
`GET /v2/spaces/$space_guid/service_instances`

For each bound and unbound service:

Get the service plan with the service instance guid
` GET /v2/service_plans/$service_instance_guid`

From the service plan, get the `name`, and the cost with `extra: costs:[{"amount":{"usd":0},"unit":"MONTHLY"}]`.

With the service instance, use the `last_operation.type|state` to know what's going on with the instance.

**Comment by msecret** [comment]
### Store design


```js
// main.js
function app(spaceGuid, appGuid) {
  cfApi.fetchServiceBindings(appGuid);
  cfApi.fetchServiceInstances(spaceGuid);
}
```

```js
// service_instance_store
on serviceActionTypes.SERVICE_BINDINGS_RESV:
  each action.bindings
    serviceReqs.push(cfApi.fetchService(binding.service_instance_guid));
  if (serviceReqs.length) this.waitingOnRequests = true;
  Promise.all(serviceReqs).then((res) => {
    this.waitingOnRequests = false;
    fetching = false;
    fetched = true;
    emitChange();
  });

  on serviceActions.SERVICE_INSTANCE_RESV:
     if (!this.waitingOnRequests) {
       this.fetching = false;
       this.fetched = true;
     }
     this.merge('guid', instance, () => { });
     ...
```

**Comment by msecret** [comment]
### Component design

```js
// service_instance_list_panel.jsx
propTypes = {
  instances: array,
  bound: boolean
}

render() {
  <Panel>
  if (this.props.bound) {
    heading = <h1>Bound services</h1>
  } else { <h1>Unbound services</h1> }

  this.props.services.map((service) => {
    return (<PanelRow><ServiceInstance service bound /></PanelRow>
  });
  </Panel>
}
```

```js
// service_instance.jsx
propTypes = {
  serviceInstance,
  serviceBinding // is not required
}

render() {
  <td>{ instance.name }</td>
  <td>{ instance.plan.name }<br>{ instance.plan.cost }</td> // share with other code
  <td>{ getState(instance.last_operation) }</td>
}
```

**Comment by msecret** [comment]
How to include the service plan with the service?

1. The service instance store adds it on

2. The service_instance_list_panel adds it on
```
function stateSetter() {
  const services = ServiceStore.getAllServicesForWhatever();
  fullServices = services.map((service) => {
    const plan = ServicePlanStore.get(service.service_plan_guid);
    return Object.assign({}, service, {plan});
  });
}
```

**Comment by msecret** [comment]
### Service panel design

How will the service list get bound vs unbound services?

Keep the bound app guid on the service entity and filter by that to get bound ones

```
services = [
  {
    guid,
    plan,
    boundAppGuid
  }
]

const boundServices = services.getAll(currentSpaceGuid).filter((service) => {
  return service.boundAppGuid === currentAppGuid
});
```

Have a separate service binding store and use some sort of matching

```js
class ServiceBindingStore {
  data: [
    {
      guid,
      serviceInstanceGuid,
      appGuid,
      credentials
    }
  ]
}

// services_panel.jsx
const allServices = ServiceStore.getAll(currentSpaceGuid);
const bindings = ServiceBindingStore.getAll(currentAppGuid);
const boundServices = allServices.filter((service) => {
  return bindings.find((binding) => {
    return service.guid === binding.service_instance_guid;
  });
});
```

Whats the component hierarchy?

```
--ServicesPanel
----ServicesList (un)bound
------Service currentlyBound
```

**Comment by msecret** [comment]
### Component design

Another try at it now that I see panel code

```
services_panel
-- panel, title="services"
---- panel_group
------ service_instance_list
-------- panel_header, "bound"
-------- panel_row
---------- column
---------- column
---------- panel_actions
------------ button, "unbind"
---------- instance_(un)bind_form
```
