### ISSUE TITLE
Improve diagnostics available to dashboard users

### ISSUE THREAD

**Issue by jeremiak** [18F/cg-dashboard#519]
In order for dashboard users to be able to troubleshoot their applications, we need to provide more information to them about the current state of their application. This includes things such as:
* Making current state very clear
* Highlighting crash events
* Highlighting user events such as SSH logins, quota changes, etc
* Enabling control over the current "scale" of the application
* Seeing services and environment variables

[Design here](https://gsa.invisionapp.com/share/MA7U5XOZJ#/screens/171977070)

**Comment by msecret** [comment]
Moving to https://github.com/18F/cg-product/issues/189
