### ISSUE TITLE
Review Dashboard with Infrastructure team to identify improvements they need

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#531]

**Comment by brittag** [comment]
Adding a note to this task - console.cloud.gov still has a couple key users who prefer it over dashboard.cloud.gov. See https://gsa-tts.slack.com/archives/cloud-gov-highbar/p1476896625004422 and https://gsa-tts.slack.com/archives/cloud-gov-highbar/p1476898375004429 for info.

**Comment by suprenant** [comment]
Got it, thanks for flagging @brittag. 

cc @thisisdano @vz3

**Comment by suprenant** [comment]
Noting that we're shutting down console.cloud.gov but still would be interested in talking to Infrastructure folks in the future.
