### ISSUE TITLE
Build pattern library

### ISSUE THREAD

**Issue by vz3** [18F/cg-dashboard#532]
We will be following Atomic Design for this:
http://bradfrost.com/blog/post/atomic-web-design/

The pattern library should be delivered via PDF+Sketch for implementation by front end devs.

**Comment by vz3** [comment]
First swing at this is here:
18f/cg-design#3

**Comment by msecret** [comment]
Separate things to do:
- Create issues for separate parts in cg-design

**Comment by suprenant** [comment]
Closing this. Moved elements to https://github.com/18F/cg-design/issues/3
