### ISSUE TITLE
Mapped routes in recent events are missing a period

### ISSUE THREAD

**Issue by stvnrlly** [18F/cg-dashboard#550]
It looks like the host and the domain are concatenated without adding the period in between, so `cool-website.18f.gov` is shown as `cool-website18f.gov`.

**Comment by jmcarp** [comment]
I noticed a potentially related issue--patch submitted at https://github.com/18F/cg-dashboard/pull/777. With those changes, I didn't replicate this issue.

**Comment by suprenant** [comment]
Thanks folks. @msecret past the patch, is there more to investigate here?

**Comment by jmcarp** [comment]
Has this rolled out to production? Once it has, I can verify that it's working as expected before closing.

**Comment by msecret** [comment]
It didn't make it into the last release but is available on dashboard-master.cloud.gov.

https://github.com/18F/cg-dashboard/releases

**Comment by jmcarp** [comment]
Does anything live at that url? It's not working now.

**Comment by msecret** [comment]
Ah sorry, I keep forgetting it was changed: https://dashboard-master.apps.cloud.gov.

**Comment by jmcarp** [comment]
Looks good! I don't see the issue I ran into earlier. @stvnrlly: can you take a look at https://dashboard-master.apps.cloud.gov and verify that the original issue is resolved?

**Comment by stvnrlly** [comment]
Yep, looks like the original issue is resolved:

<img width="863" alt="screen shot 2016-12-03 at 7 53 12 pm" src="https://cloud.githubusercontent.com/assets/4156602/20863236/3c23149e-b992-11e6-845e-828f745cd7fe.png">

I'll go ahead and close this.
