### ISSUE TITLE
Assumption: Application limits should be exclusive and disallow 'overlap' with other limits in the space/org

### ISSUE THREAD

**Issue by thisisdano** [18F/cg-dashboard#556]
I'm not sure if this is already the case.

For instance, if you have a space with a quota of 1GB disk, can you have five apps in that space that each have 'overlapping' 1GB application disk limits? Or should an application limit be exclusive and _reserve_ the space instead? That is: must all the application limits in a space/org add up to no more than the space/org quota?

If limits reserve, it would prevent 'encroachment'  — where a second app's usage would cut into a first app's limit.

**Comment by thisisdano** [comment]
OK, this seems to be addressed here: https://github.com/18F/cg-design/issues/5

Limits and quotas are exclusive. 💯

**Comment by suprenant** [comment]
Excellent.

Outside of this issue specifically, have we discussed what we want to do with assumptions that are resolved? I would assume that we'd move them to closed and also put any important information (outside of what directly informs our WIP, perhaps) in our documentation.

**Comment by mogul** [comment]
I'd just close 'em at the least... :)
