### ISSUE TITLE
A user should be able to see all of their bound routes in a panel interface

### ISSUE THREAD

**Issue by jeremiak** [18F/cg-dashboard#559]
Refs #517

**Comment by suprenant** [comment]
In order for developers to view which public URLs where their apps are available, they need a list of routes that are currently bound to the application.

Acceptance criteria:
- [ ] The user can see the number of routes bound
- [ ] The user can see the individual public URLs that are currently bound
- [ ] The user can see how many routes that are available given the user's quota

Refs 18f/cg-design#5
