### ISSUE TITLE
A user should be able to edit any existing routes and add a new one

### ISSUE THREAD

**Issue by jeremiak** [18F/cg-dashboard#560]
Refs #517

**Comment by suprenant** [comment]
In order for developers to managing the public URLs where their apps are available, they need features such as the ability to:

- Create new routes
- Update existing routes
- Delete existing routes
- Have their delete action confirmed using https://github.com/18F/cg-style/blob/master/src/css/components/actions.scss#L7
- Prevent updating or creating routes such that they collide with an existing route

Acceptance criteria:
- [ ] The user can click a button that Add Route granting the ability to add a new route
- [ ] The user can click an Edit Route link to update a route
- [ ] The user can click a Delete Route link to delete a route
- [ ] The user can see a Delete Action confirmation when deleting a route
- [ ] The user can see a notification if they attempt to update or create routes that collide with an exiting route
- [ ] The user can see buttons to Cancel or Apply their changes 
- [ ] The user can only create a route that has a domain that has been assigned within the organization

Refs 18f/cg-design#5
