### ISSUE TITLE
App settings panel

### ISSUE THREAD

**Issue by jeremiak** [18F/cg-dashboard#561]
In order for developers to adjust their applications, they need a panel that clearly shows application settings such as:
* Buildpacks
* Scale
* Memory, disk, and service usage
* Environment variables

Acceptance criteria:
- [ ] The user should be able see a buildpacks associated with their application
- [ ] The user should be able to see the scale of their application
- [ ] The user should be able to see memory, disk, and service usage compared to their quota limit for each
- [ ] The user should be able to see all of their environment variables

Refs #517

**Comment by suprenant** [comment]
We already have designs for memory, disk, and service. Writing new stories for design/features for the rest of these items.
