### ISSUE TITLE
Discovery research: PMs and dashboard

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#567]
In order for the cloud.gov liberator team to understand missing/incompletely functionality or general problems with the dashboard, we will conduct research sessions with 18F Product Managers about the dashboard.

Acceptance criteria:

- [ ] A small series of meetings set up with product leads who use the dashboard to solicit their feedback 
- [ ] Document with notes/shared learnings

**Comment by suprenant** [comment]
We conducted one research session yesterday. Notes are here: 

https://drive.google.com/drive/u/0/folders/0B_a71ksF1BfnVEQtVEc1OEktY3M


Another session is scheduled for today.

**Comment by vz3** [comment]
@suprenant There is not an assumption here that PMs are using the current dashboard. I would frame this as discovery research, not feedback.

**Comment by suprenant** [comment]
Interview two notes: https://docs.google.com/document/d/1BX4dR10e6AkezR2rMPPVvwJeYcqCNjmBDM9IE75w8UI/edit

**Comment by suprenant** [comment]
Noting that @abisker suggested we talk to RTI

**Comment by suprenant** [comment]
@vz3 after four rounds, are we done here, or are we continuing to plan additional sessions?

**Comment by suprenant** [comment]
...and do we have a norm for batching/synthesizing our research learnings so we can share and act on them? If not, I'd be happy to work with you on it @vz3

**Comment by suprenant** [comment]
Discussed during standup – the four interviews we have conducted, when summarized, will complete this story. Any additional research stories will be outlined in separate issues. 

Interview notes with brief synopses are here: https://drive.google.com/drive/folders/0B_a71ksF1BfnVEQtVEc1OEktY3M 

cc @mogul

**Comment by suprenant** [comment]
@vz3 as a reminder, let's make sure we're also thinking about how we want to include this on Wednesday's demo during Sprint Review

**Comment by suprenant** [comment]
Talked to @vz3 – thinking we'll include this in the WIP section for now for the demo

**Comment by suprenant** [comment]
@vz3 since we have our notes from this session and have already internalized the learnings, should we mark this done and move on?
