### ISSUE TITLE
Error handling for route edit/creation

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#569]
In order for a developer to know when something goes wrong with creating or editing a route (such as trying to create a route that already exists) there should be error messages in the route form.

Design:
https://cloud.githubusercontent.com/assets/11464021/17978809/9e34dc1a-6aac-11e6-8983-074665214436.png

Acceptance criteria:
- [ ] Show a clear description of an error if such an error exists
- [ ] Errors are written in such a manner that users will know how to address the error

**Comment by suprenant** [comment]
@thisisdano you are assigned to this. Is there work here that you expect to do?
