### ISSUE TITLE
App services panel stuck in loading state in strange condition

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#572]
On some apps, there are no service instances but one service binding. In this condition the services panel is stuck in loading state.

**Comment by adborden** [comment]
@msecret can you provide some repro steps to get an app in the right state? Not sure how to add a binding with no service.

**Comment by suprenant** [comment]
@msecret @adborden can you please advise/help accept this one?

**Comment by adborden** [comment]
I am not seeing this behavior.
