### ISSUE TITLE
Route displays incorrectly for "apps.cloud.gov" route

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#573]
On apps that use the "apps.cloud.gov" route, the route is displaying with just the path and the domain seems to be missing

**Comment by msecret** [comment]
Could be related to: `GET http://localhost:9999/v2/private_domains/97435c2f-d5bb-4c10-8393-55d7d7169932 404 (Not Found)`

**Comment by msecret** [comment]
Also found in that route, it says the domain url is `/v2/shared_domains/97435c2f-d5bb-4c10-8393-55d7d7169932`.

Maybe because we're searching in `private_domains` when it could be a shared domain we're not getting the correct one?

**Comment by adborden** [comment]
Looks good on dashboard-master
