### ISSUE TITLE
Review/update Definition(s) of Done

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#576]
As a UX squad member, I can access Definition(s) of Done to provide clear direction in how the squad will work across repos. 

Note that these are our current documents: 
 - cg-product/DeliveryProcess.md
 - cg-dashboard/CONTRIBUTING.md
 - cg-landing/CONTRIBUTING.md
 - cg-docs/CONTRIBUTING.md

Acceptance criteria: 
- [ ] Various Definitions of Done reference each other correctly and do not repeat information unnecessarily

**Comment by suprenant** [comment]
@msecret as discussed

**Comment by suprenant** [comment]
@msecret looking back through notes, we also discussed that for a story to be done, a developer would need to add a PR for documenting it. Do you want to include this with this issue or address it separately?

**Comment by suprenant** [comment]
@msecret is this done? Or are there still changes you're making or planning to make?

**Comment by msecret** [comment]
I think we can move this to done
