### ISSUE TITLE
(Un)bind service instances on app page

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#578]
In order for a developer to easily activate a service such as a database on their app, there should be UI to bind service instances on the app page.

Acceptance criteria: 
 - [ ] Display cautionary dialogue when trying to unbind an app
 - [ ] Button to bind an unbound app
 - [ ] Button to unbind a bound app

**Comment by suprenant** [comment]
Discussed not needing a visual design for now. Would be helpful to know what happens when binding/unbinding fails

**Comment by vz3** [comment]
@msecret Immediate thoughts on this:
Only services that are not bound to any app at all show up as "unbound". What might cause a service to not bind? If it fails, we should show an error.

**Comment by thisisdano** [comment]
This panel should show a) services bound to the app; and b) services in the
space available to the app.

Are services in the space limited to a single app? If so, perhaps the
current view makes some sense. (But this doesn't make sense to me as a
limitation.) If this is NOT the case, the current view lets services
unbound to the current app but bound to another app in the space fall
through the cracks -- which would be misleading.

Either way, this panel prob needs further consideration. It def feels
confusing and potentially incomplete as is.

Additional consideration: are there app limits for services?

**Comment by msecret** [comment]
I'm pretty sure services in the space are not limited to a single app.

**Comment by msecret** [comment]
A thing to keep in mind: this is just the view on the app page. There's currently another view on the spaces page where we could show all services available to your space and which apps they are bound to.

**Comment by suprenant** [comment]
@thisisdano we're almost ready to pick this up. Can @marco move forward with this as-is (using the [current UI](https://cloud.githubusercontent.com/assets/582918/17873758/7779e408-6895-11e6-9062-533dd691bfe3.png) or did you want to create a visual design for it.

Please let us know ASAP as we're almost ready to pick up this issue.

cc @vz3

**Comment by thisisdano** [comment]
My concerns are less about the UI (I guess) and more about the logic of what appears in the panel. So — to confirm — this panel should show:
a) Services available in the org bound to the current app
and
b) Services available in the org not bound to the current app

There seemed to be confusion at the program sprint review (and above) about whether this panel was displaying (b), or if it was displaying **Services available in the org not bound to ANY app**. Perhaps I'm misunderstanding that confusion, tho.

If all that is ok: 
- `Unbound service instances` could be `Unbound service instances available in [org name]` to 
- Plan "size" is kinda unhelpful cos it doesn't tell you what you get
- `Are you sure you want to do this?` could be `Are you sure you want to unbind [service name]?` or something in the text that re-affirms the instance you're unbinding.

Do services have preferences or setup variables that would be affected by an unbinding? If the service were bound again, would it work properly?

Is there anyway to indicate a Application Limit to services if any exists? A space limit? (Perhaps these are elements for a further iteration.)

**Comment by suprenant** [comment]
Thanks @thisisdano 

@msecret let us know your thoughts? And if we need to find time to talk through this one together, let's do that.

**Comment by msecret** [comment]
One difference from your assumption is that the services are available to the space, not the org. So:
a) Services available in the *space* bound to the current app
and
b) Services available in the *space* not bound to the current app

I think the cloud.gov team is hoping to expand plan size to make it more understandable and consistent between services, so I kinda want to keep that data in there.

Services do have "credentials" which are pretty much user names and passwords a dev needs to use the service. This wasn't in @vz3 's UI, I'm not sure it's needed right now. Services also have permissions and keys but I havne't seen us use this functionality on cloud.gov yet.

There is a space limit to the amount of services you can have but no limit to the amount of services you can bind to an app. This means I don't think theres any limit to show here, because this isn't where you're "creating" the services, that's done in the marketplace. The only thing I'm not 100% certain on is if you can bind an instance to multiple apps, but I think you can.

**Comment by msecret** [comment]
### Code design

Add the service binding object to all bound services to make unbinding them easier:

```js
// service_instance_panel.jsx
  const boundServiceInstances = serviceInstances.map((serviceInstance) =>
    const binding = serviceBindings.find((serviceBinding) =>
      serviceInstance.guid === serviceBinding.service_instance_guid
    )
    if (!binding) return null; // Filter these dead ones out later
    return Object.assign({}, serviceInstance, { serviceBinding: binding });
  ).filter((instance) => !null);
```

Actions
```js
// service_actions.js
bindService(appGuid, instanceGuid)
unbindService(binding)
boundService(binding)
unboundService(appGuid, instanceGuid)
```

API
```js
// cf_api.js
createServiceBinding(appGuid, serviceInstanceGuid)
deleteServiceBinding(serviceBinding)
```

Store
```js
// service_binding_store.js
case serviceActionTypes.SERVICE_BINDING_{CREATE|BIND}: {
  // add to store and emit change?
}

case serviceActionTypes.SERVICE_BINDING_{DELETE|UNBIND}: {
  // remove from store and emit change?
}
```

**Comment by thisisdano** [comment]
@msecret 

`Unbind` action confirmation section is changing the width of the row:

<img width="940" alt="screen shot 2016-09-19 at 10 36 19 am" src="https://cloud.githubusercontent.com/assets/11464021/18642313/0bd5bd00-7e55-11e6-922b-5e44643c9dea.png">

`Bind` action isn't doing anything for me...

**Comment by thisisdano** [comment]
Also, what kind of a service is this instance? I see its name, `basic`, and `free`. Is there a field that might tell me what service it's an instance of?

**Comment by thisisdano** [comment]
Also (and from above):

- The `unbound` hed could be `Service instances available in [space name]`
- Do we need to see the status of available/unbound instances?
- Is it worth knowing if any of the available instances are bound to any other apps?
- Plan "size" is kinda unhelpful cos it doesn't tell you what you get
- `Are you sure you want to do this?` could be `Are you sure you want to unbind [instance name]`? or something in the text that re-affirms the instance you're unbinding.
- Are monthly costs listed per MB or GB? Or has that calculation already happened? — The costs seem very low.

**Comment by msecret** [comment]
@dano answer to things you brought up^

- Renamed `unbound` to `Service instances available in [space name]`
- There's a separate discussion that is happening around the status. It also would help code consistency to have them as is.
- I think we're going to put that information on the space page. We could also limit the list to only services that aren't bound at all.
- While there currently isn't very much information in plan "size", we can add more to it as the cloud.gov team in the future.
- Changed to `Are you sure you want to unbind [instance name]`
- I'm pretty sure it's not per MB and I think it actually is really low. But we should just talk to Diego about this when we have the meting.

**Comment by msecret** [comment]
OK I also changed the code so we only show isntances that are not bound to any app: 8b7c597d2552df8b3cdb3ae8792dbe04a356f6f6
