### ISSUE TITLE
Design limits and quotas

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#581]
Display resources app is using
Display limits and how they can be adjusted while remaining within the quotas of space and org

InVision: https://gsa.invisionapp.com/share/9T8GMJ8B8#/185319403_App-Settings-6c

Ref #561

**Comment by suprenant** [comment]
@thisisdano can you please link the Invision doc?

**Comment by thisisdano** [comment]
![image](https://cloud.githubusercontent.com/assets/11464021/18366213/a9634bac-75ca-11e6-9850-b559f813a6db.png)
