### ISSUE TITLE
Bring billing data into dashboard

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#589]
In order for the team to bring billing information to the dashboard, we should bring billing data into the dashboard.

Research w/Diego:
https://docs.google.com/document/d/1rOmK-7Fb8nWKpQjwxCM6NIcT1Fue7YABzrq1Tm_sLjs/edit\

Research w/Bret:
https://docs.google.com/document/d/1CD8wGERKulleuXXVwngAfUYAAF6dyDwtYoEkVbFlZM8/edit

Would be about getting Abacus set up
Do we want to go straight for live billing? Or is there an MVP around way to provide information?

**Comment by suprenant** [comment]
Per: https://github.com/18F/cg-dashboard/issues/596
