### ISSUE TITLE
Conduct research session with Bret/Diego to learn more about how billing works

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#596]
Research notes w/Bret:
https://docs.google.com/document/d/1CD8wGERKulleuXXVwngAfUYAAF6dyDwtYoEkVbFlZM8/edit

Research notes w/Diego:
https://docs.google.com/document/d/1rOmK-7Fb8nWKpQjwxCM6NIcT1Fue7YABzrq1Tm_sLjs/edit

Would be about getting Abacus set up
If/when it would happen, timing
30-40 mins
Could be a smaller group
Do we want to go straight for live billing? Or is there an MVP around way to provide information?

**Comment by suprenant** [comment]
Per https://github.com/18F/cg-product/issues/287

I can pick this up soon to schedule time for us

**Comment by nikzei** [comment]
Colleagues from our 18F FEC team have asked questions about cloud.gov billing (FEC just purchased a prototyping account). They might have some valuable insights to share coming from the customer perspective. If you are interested in holding a research session with them, I'd be happy to make the connection. 
@vz3

**Comment by suprenant** [comment]
As discussed, I will work to find time with @dlapiduz on this next week

**Comment by suprenant** [comment]
Session with Diego booked for this Thursday. Invite is on cloud.gov calendar. @vz3 I'm OOO FYI
