### ISSUE TITLE
Refine service states

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#601]
As a user, I want a clear description of the current state of my services. 

Notes: 
 - Cloud Foundry API doesn't give us official state of stopped
 - API gives us the last operation (create, update, or delete) and whether or not the operation was successful and we determine a state from this
 - From this, we are currently displaying these states: Failed, deleting, processing, running, and stopped
 - Ref: https://apidocs.cloudfoundry.org/242/service_instances/retrieve_a_particular_service_instance.html
last_operation

**Comment by suprenant** [comment]
@msecret @mogul – do you have anything to add/clarify here at the moment? This came up during our last sprint review, and Marco and I talked this over some.

**Comment by mogul** [comment]
I'm having a hard time mentally mapping the combination of `last_operation.type` and `last_operation.state` to `failed`,`deleting`,`processing`,`running`,and `stopped`. Can you put in a table showing how those values are being mapped?

**Comment by suprenant** [comment]
@msecret can you please add the table per Bret's request?

**Comment by msecret** [comment]
|             | create  | update  | delete   | None    |
|-------------|---------|---------|----------|---------|
| **in progress** | Running | Running | Deleting | Stopped |
| **succeeded**   | Running | Running | Deleting | Stopped |
| **failed**      | Failed  | Failed  | Failed   | Stopped |

**Comment by mogul** [comment]
Thanks! That's just what I was after. 

One confusing thing is `create+in-progress`... It says "Running" but the service not actually available to the app until it is `create+succeeded`! This _could_ be *very slow*... The API is asynchronous in case a service even actually has to be hand-provisioned! The same goes for `update`. `Running` can be misleading while things are in a waiting state.

Can I suggest:

|             | create  | update  | delete   | None    |
|-------------|---------|---------|----------|---------|
| **in progress** | Starting | Reconfiguring | Deleting | Stopped |
| **succeeded**   | Available | Available | - | Stopped |
| **failed**      | Failed  | Failed  | Failed   | Stopped |

**Comment by msecret** [comment]
That sounds good Bret! Thanks for taking a look

**Comment by msecret** [comment]
In the new UI, we're no longer showing all the states, we're only showing when something fails. Is that correct @thisisdano

**Comment by thisisdano** [comment]
It probably makes sense to include the status for all of them except available.

Here are a couple options — a simple change to the status text, and a state with an activity animation:

![service states 2x](https://cloud.githubusercontent.com/assets/11464021/18876451/a0c76010-847e-11e6-81e0-ef14f987f1be.png)

@msecret @vz3

**Comment by thisisdano** [comment]
![service states-error 2x](https://cloud.githubusercontent.com/assets/11464021/18876747/b2cc8366-847f-11e6-9308-0a675a34cde3.png)

**Comment by msecret** [comment]
That looks good @thisisdano . So in terms of putting the error message there: is that a pattern we want to use for route binding too? It would help a lot of they used the same pattern.

**Comment by thisisdano** [comment]
Yes, I'd want to use the same pattern for both.

**Comment by suprenant** [comment]
Pulling needs-design label as this no longer seems to need design.

**Comment by adborden** [comment]
Looks good on dashboard-master
