### ISSUE TITLE
Outline needs for preliminary error handling

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#616]
Services page needs error handling
A little different than route error handling
Easy to show routes errors because it’s part of the form
For services, we need to show errors and don’t have an obvious place in the UI
When we fetch something, there technically could be an error
So, we might want display a general error
Not tied to specific part of page, maybe at top, or for app page top of the panel
Or, they could be generic at top of the page (“check connection”, etc.)

*Next steps: 
 - Discuss, determine specific error cases
 - Design

**Comment by suprenant** [comment]
Per @msecret, this is actually blocking both route and service bindings. @vz3 will be working on this soon

**Comment by vz3** [comment]
This has been flagged as a blocker by @suprenant @msecret

**Comment by vz3** [comment]
This has been flagged as a blocker by @suprenant @msecret

**Comment by thisisdano** [comment]
We have some initial sketches for error handling in https://github.com/18F/cg-dashboard/issues/601
Can we discuss where it needs to go from there to unblock? What specific error cases/flows do we need to address?

**Comment by suprenant** [comment]
After discussing with @msecret @thisisdano, this no longer is a blocker. We plan to use Dan's UI for errors on services. 

@vz3 we were thinking that we might want a more generic error patterns to finish this. Does that work, and do you still plan on picking this up for this sprint?

**Comment by suprenant** [comment]
Per @vz3 – next steps here are catching up with @msecret about the different types of errors we need to design for.

**Comment by vz3** [comment]
Tracking this here:
https://docs.google.com/a/gsa.gov/spreadsheets/d/1v9nBTrF4zTr7MkIw04dpfe15P1yef2085EnzcAmdhZc/edit?usp=sharing

**Comment by suprenant** [comment]
We have a list here, but it's not feeling very complete for this stage. Could possibly use more input from you @msecret and/or Atlas folks.
