### ISSUE TITLE
Research with SME(s) to learn about technical requirements for inviting collaborators with pre-assigned roles

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#619]
Research doc: 
https://docs.google.com/document/d/1K7TIUiizp0weSHt6vxyDpafgiPWzSEmS9r12_CIM930/edit

### Findings
- https://docs.apps.cloud.gov/apps/managing-teammates/ shows the current workflow
- Current signup is asynchronous, gives existing users no insight into signup progress
- The dashboard should make this easy and visible
- Org and Space levels should clearly communicate active users and their roles
 - Existing UX for this display is lacking
- Org and Space levels should include ability to add new users
 - We should be able to add new users with roles pre-defined
 - The status of the pending/new users should be visible
 - Pending users could be delete-able
 - There should be a confirmation mechanism for feedback that a new user was added to the org/space
- Roles for pending users requires backend work to be possible. Currently roles cannot be assigned/granted until the user is active.
 - This might be a job for bots

### Next steps / Acceptance criteria: 
- [x] Talk to Bret
- [x] Talk to Atlas (Adam Kendall/Chris Nelson) more about implementation
- [ ] Discuss w/Nikki, Bernd (as needed)
- [ ] Talk to Diego about Cloud Foundry notifications 
- [ ] UX around All Organization Users Page
- [ ] Come away with technical requirements
- [ ] Break out work
 - [ ] Add a person whether or not they have an account
 - [ ] Set their role
 - [ ] Notifications
  - [ ] If someone already has an account, they get notified 
  - [ ] Notice about space or org they’re being added to

**Comment by suprenant** [comment]
Talked to @vz3 – thinking this is more a dev-side issue so assigned @msecret. Let us know if that's not right

**Comment by suprenant** [comment]
@mogul mentioned being available to help with this as needed

**Comment by suprenant** [comment]
Will set this up!

**Comment by suprenant** [comment]
Brought in information from duplicate issue: https://github.com/18F/cg-dashboard/issues/620

(@thisisdano @adborden FYI this is the information I mentioned during our call)

**Comment by suprenant** [comment]
Put time on the calendar for Friday.

**Comment by suprenant** [comment]
Conducting this session now, notes in the linked Google Doc

**Comment by thisisdano** [comment]
@suprenant @mogul 

So here's a suggestion: Meetings like this (that is to say, pretty much any real meeting with value) should have: 

1. An issue
2. Link to this issue in some kind of higher-level doc (like sprint documentation or feature documentation in something like a product wiki)
2. "Findings" — synthesis of meeting content/outcome — added/discussed in the issue
3. Next steps clearly outlined

These would be part of the Definition of Done for a meeting/interview/research session.

For instance:

- - -

### Findings
- https://docs.apps.cloud.gov/apps/managing-teammates/ shows the current workflow
- Current signup is asynchronous, gives existing users no insight into signup progress
- The dashboard should make this easy and visible
- Org and Space levels should clearly communicate active users and their roles
 - Existing UX for this display is lacking
- Org and Space levels should include ability to add new users
 - We should be able to add new users with roles pre-defined
 - The status of the pending/new users should be visible
 - Pending users could be delete-able
 - There should be a confirmation mechanism for feedback that a new user was added to the org/space
- Roles for pending users requires backend work to be possible. Currently roles cannot be assigned/granted until the user is active.
 - This might be a job for bots

### Next steps
- [ ] Talk to Atlas (Adam Kendall/Chris Nelson) more about implementation
- [ ] Talk to Diego about Cloud Foundry notifications 
- [ ] UX around All Organization Users Page
- [ ] Break out work
 - [ ] Add a person whether or not they have an account
 - [ ] Set their role
 - [ ] Notifications
  - [ ] If someone already has an account, they get notified 
  - [ ] Notice about space or org they’re being added to
 
- - -

I added the Findings section to the doc, but it should live here, too. Perhaps somewhere else as well... TBD. All of this is to the point of continuous communication throughout the program and beyond our tenures.

**Comment by thisisdano** [comment]
Oh, and der... a link to the primary doc: https://docs.google.com/document/d/1K7TIUiizp0weSHt6vxyDpafgiPWzSEmS9r12_CIM930/edit

**Comment by suprenant** [comment]
@thisisdano sounds fine and good – let's strike through the information from the working doc if we bring it here to avoid redundant information, which can be confusing. 

I pulled your link to the primary doc as that's already in the top comment here.

**Comment by thisisdano** [comment]
Maybe just place a link to the issue in the doc itself, as well.

**Comment by suprenant** [comment]
I scheduled a meeting for this with @LinuxBozo @cnelson and the squad on Thursday.

**Comment by suprenant** [comment]
Closing this for now given we're not focusing on this for PI8.

**Comment by suprenant** [comment]
Updated with link to #cloud-gov-atlas discussion that happened yesterday.
