### ISSUE TITLE
Perform front-end evaluation of new webfonts

### ISSUE THREAD

**Issue by vz3** [18F/cg-dashboard#623]
This ask is for a front-ender to take a look at the proposed new webfonts for the dashboard including 18Franklin and Roboto Mono.

18Franklin:
https://github.com/18F/cg-design

Roboto Mono:
https://fonts.google.com/specimen/Roboto+Mono

Main question is about how switching from Open Sans+Merriweather+Courier to 18Franklin+Georgia+Roboto Mono might affect browser performance/load time.

**Comment by msecret** [comment]
In terms of size for Franklin:
- Merriweather and Source Sans WOFF(2) file sizes are all around 20kb - 30kb.
- 18Franklin file size comes in around 24kb.
Theres no problem with size.

**Comment by msecret** [comment]
18Franklin font doesn't seem to have any `.ttf` files. If all we have are WOFF files then the font might not [render on IE8](http://caniuse.com/#feat=woff)

**Comment by thisisdano** [comment]
I'll see if I can export the .ttfs — I just did the conversion with fontsquirrel, so I'll get em and upload em.

**Comment by thisisdano** [comment]
@msecret OK — re-output from fontsquirrel and re-uploaded the whole package (including the  `ttf` files).
https://github.com/18F/cg-design/commit/cbbea61392843e790c2964615ab2996a9b24b07c

**Comment by suprenant** [comment]
@vz3 @thisisdano what is our value statement for this?

**Comment by vz3** [comment]
@suprenant This is a design decision. It is our team's opinion that the type combination of 18Franklin/Georgia is superior to Open Sans/Merriweather for our application. But this is admittedly something that's is difficult to get data around. There is an additional argument of using one less webfont by using Georgia (for Mac OS+Windows users but not Linux).

**Comment by vz3** [comment]
Please see here for side-by-side
https://gsa.invisionapp.com/share/8X8RHAOKS#/191214498_Type-Scale-Vertical

**Comment by msecret** [comment]
It's sounds like from a technical perspective, this change is good to go. Are we good to go from a design perspective?

**Comment by msecret** [comment]
Also, speaking of linux, we should just add these fonts to the list: http://isabelcastillo.com/georgia-alternative-font-ubuntu

**Comment by vz3** [comment]
Upon merge of this PR I believe we're good. @thisisdano @brittag 
https://github.com/18F/cg-design/pull/16

@thisisdano let's look at how these changes would affect non-dashboard side (not suggesting that we flip the switch all at once but our typefaces should be unified eventually for both design consistency and download efficiency).

**Comment by vz3** [comment]
@msecret Yes we owe you a font-stack as a component of this change.

**Comment by thisisdano** [comment]
I've been looking at this on the docs side — there are many tweaks I'll want to make, but the pair of faces should work well.

- - -

![-docs-sketch 2x](https://cloud.githubusercontent.com/assets/11464021/19125471/03c3deb4-8aec-11e6-8253-e5f344b8bdce.png)

**Comment by brittag** [comment]
Ah thanks for tagging me! Yes, with my compliance hat on, we usually need to update a repository's license files any time we add font files to a repository - feel free to ping me to help revise license files anytime!

**Comment by thisisdano** [comment]
@brittag, you're already working on the license stuff for `roboto mono` and `18franklin`, yes? (Per our discussion in the channel the other day...)

**Comment by brittag** [comment]
@thisisdano Yes, for the cg-design repository I filed a PR here: https://github.com/18F/cg-design/pull/16 ([noted by Victor, thanks!](https://github.com/18F/cg-dashboard/issues/623#issuecomment-251751616). I mean that if you all need to add the fonts to the cg-dashboard repository (or other repositories), let's update those repository files as well. :)
