### ISSUE TITLE
Move all api response formatting to api code

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#629]
In order for developers to always have consistent store objects to work with, all API response handling should be moved from the stores to the api code.

Acceptance criteria:
- [x] There should be a `formatResponse` method that works on both arrays of responses or a single response.
- [x] All `formatSplitResponse` calls done in stores should be used to the `cf_api` file.

**Comment by msecret** [comment]
#### Current state:
Every time a store receives data from the server, it does the job of formatting it. This really means taking this from the server:

```
{ 
  metadata:
    guid: 'blah'
  entity: 
    name: 'blahblah',
    other_thing: 'zxcvzxc'
}
```

and de-nesting the data so it looks like this:

```
{
  guid: 'blah'
  name: 'blah'
  other_thing: 'zxcvzxc'
}
```

Which makes the objects way easier to work with. The work to do this transformation is done individually in each store so:

```
const instances = this.formatSplitResponse(action.serviceInstances);
```

Additionally, when transforming single objects rather then arrays, we do this hacky thing:

```
const instance = this.formatSplitResponse([action.serviceInstance])[0];
```

If a dev makes the mistake in doing this, things will break.

#### Fix
Move `formatSplitResponse` to `cf_api` or `util/` and always do the transformation when the data is received in `cf_api`. Additionally, make `formatSplitResponse` work with single or multiple objects (or split to two separate methods that use the single one.

**Comment by msecret** [comment]
@adborden

**Comment by adborden** [comment]
Looks good.
