### ISSUE TITLE
Fix broken testing server

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#633]
The testing server that uses the `smocks` library to create a cloud foundry API with fake data we specify is broken. This is likely due to the [code climate fixes pr](https://github.com/18F/cg-dashboard/pull/607). My guess is that I updated the `npm-shrinkwrap` file so that one of smocks dependencies was updated so it no longer works with the API we're using.

Potential remedies:
- [ ] Attempt to get `npm-shrinkwrap` back into a version state where `smocks` was working.
- [x] Fix our use of smocks so it works with the newer version. This would have the added benefit of fixing a few security problems which is blocking us from deploying a an actual server using this test data #577. Fixing smocks means adding a separate file handler as a plugin to `hapi`, the server module `smocks` uses.

**Comment by msecret** [comment]
@adborden this is a backendy related task if you're interested.

**Comment by suprenant** [comment]
@msecret can you please close this one out after verifying that it's done?
