### ISSUE TITLE
Iterate on focus hover

### ISSUE THREAD

**Issue by vz3** [18F/cg-dashboard#635]
I would like for us to get rid of the gradient in the border and discuss potential high-contrast colors. The gradient reduces contrast which is important for this element.

This goes to design first then dev.

![latauz881r](https://cloud.githubusercontent.com/assets/582918/18963794/5ae87ba2-8644-11e6-9cd1-3a8d792c9944.gif)

**Comment by suprenant** [comment]
@vz3 we talked about this and @thisisdano got rid of the gradient. We haven't touched the contrast yet but are going to go ahead and close this up for now. Please let us know if you happen to to have other thoughts.
