### ISSUE TITLE
Display action loading state for app page panels

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#637]
In order for a developer to know when a route or service is still in the process of being deleted, (un)bound, there should be a loading UI for actions.

Acceptance criteria:
- [ ] The loading UI appears for any action taking on an existing route or service on the app page panels.
- [ ] The UI should state what action is being taken, ie "Deleting" or "Binding".
- [ ] The UI should have an animated loading indicator.

**Comment by msecret** [comment]
https://cloud.githubusercontent.com/assets/11464021/18878027/02768a02-8484-11e6-9634-484dbe3e7954.png

[design issue](https://github.com/18F/cg-design/issues/14)
[invision prototype](https://gsa.invisionapp.com/share/9T8GMJ8B8#/screens/192025036).

**Comment by msecret** [comment]
Things required before development:

- @thisisdano can you provide me with a gif of the animated loading UI? The 3 alternating blue dots.
- @thisisdano and @vz3 is the design in https://github.com/18F/cg-design/issues/14 ready for development?

**Comment by thisisdano** [comment]
@msecret You could do something like this in css for the loading animation: http://codepen.io/thisisdano/pen/jrLywZ

As for the second point, this was in the original issue:
> What if we don't know what the request is? Like if we don't know if it's "Starting", "Deleting", etc? We'll just show the loader? Trying to think of all possible scenarios now.

In what situations would we not know the kind of request? AFAIK this loader triggers only on a specific action, like `delete` or `bind`.

Other than that Q, I think it's ready to try.

**Comment by vz3** [comment]
@thisisdano animation looks great @msecret thumbs up here
