### ISSUE TITLE
Linking url of unbound routes rather then bound

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#645]
On the app page, we're mistakenly linking the URL of the unbound app routes rather then the bound ones. We should link the bound ones because unbound routes aren't technically running.

![screen shot 2016-10-05 at 10 39 38 am](https://cloud.githubusercontent.com/assets/1701077/19124258/55ab5a86-8ae7-11e6-9aa6-3cf81f8e8a87.png)

**Comment by jonathanconway** [comment]
@msecret, may I fix this with [PR690](https://github.com/18F/cg-dashboard/pull/690)?

**Comment by suprenant** [comment]
@msecret looks like this was finished. Closing this up
