### ISSUE TITLE
Change sidenav to dropdown nav

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#647]
In order for a dashboard user to easily navigate between orgs, spaces and apps without having viewable space taken up by a sidenav, the current sidenav navigation should be moved to a dropdown at the top of the page.

**Comment by msecret** [comment]
![screen shot 2016-10-05 at 4 17 47 pm](https://cloud.githubusercontent.com/assets/1701077/19135027/95a6d6c2-8b16-11e6-9555-9b8c68ec458f.png)
https://gsa.invisionapp.com/share/8X8RHAOKS#/screens/191691942

**Comment by suprenant** [comment]
Feeling this is a bigger issue. We also want to do some testing around the mechanism before jumping into development.

**Comment by suprenant** [comment]
Next step is testing this: https://github.com/18F/cg-dashboard/issues/661
