### ISSUE TITLE
Modify sizing and layouts of top page headings

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#648]
In order for a developer to clearly know what page they are looking at in the dashboard, the page headings and page layout should be large and clearly separated.

This will be included in: https://github.com/18F/cg-dashboard/issues/745
This is essentially the implementation issue for the breadcrumb: https://github.com/18F/cg-design/issues/24

This work is specific to page header at top of page, including setting up space underneath top nav where this information can go:
 - Overview/home: home icon, "Overview" displays (no breadcrumb)
 - Org/App/Space: breadcrumb nav displayed. Noting that because breadcrumb is wider, Open App and Restart App buttons move into panel below nav

Acceptance criteria:
 - [ ] There is space for a page headers in Overview/Org/App/Space pages
 - [ ] Page content in Overview/Org/App/Space pages has transparent area revealing light gray page background where actions (where available, i.e. App page) are displayed

**Comment by msecret** [comment]
Show what I mean


![screen shot 2016-10-05 at 4 17 47 pm](https://cloud.githubusercontent.com/assets/1701077/19135102/1ee9bd96-8b17-11e6-842f-7a61d5a88711.png)

**Comment by suprenant** [comment]
Feeling more comfortable tackling the nav. Entire header (including navigation) could be thornier

**Comment by suprenant** [comment]
@msecret will take a look here, thinking this could be bigger than our usual standards.

**Comment by line47** [comment]
Not a good issue for a React beginner, which I am.

**Comment by msecret** [comment]
We may have to push this back because it's harder to implement then we wanted due to the react component hierarchy.

**Comment by adborden** [comment]
Here's a relevant invision screen of the App page with actions. https://gsa.invisionapp.com/share/8X8RHAOKS#/screens/208180056
![screenshot from 2016-12-20 10-34-05](https://cloud.githubusercontent.com/assets/509703/21363068/dd82cfa4-c69f-11e6-905e-752cec5ec739.png)
