### ISSUE TITLE
Implement re-designed header and background

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#650]
In order for a dashboard user to clearly see the navigation and site, the header and background should be re-designed.

Acceptance criteria:
- [ ] The site background should be changed from dark blue to gray.
- [ ] The wrap width of the site should reflect the design.
- [ ] The typography of the navigation and logo should match the design.
- [ ] The search functionality should not be implemented yet.

Design: https://gsa.invisionapp.com/share/8X8RHAOKS#/screens/191691942

**Comment by suprenant** [comment]
Discussed prioritizing header over the background color
