### ISSUE TITLE
Update typography to new design 

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#654]
In order for dashboard users to see the new, shared, cloud.gov brand, there should be changes to the typography of the site.

Acceptance criteria:
- [ ] Font families should be changed:
  - [ ] Merriweather and Open Sans should be removed, and files should be removed.
  - [ ] 18Franklin and Roboto mono and Georgia should be added.
- [ ] Base sizes for headings, paragraphs should be defined.

**Comment by msecret** [comment]
This is what this is looking on the 3 sites:

![screenshot_2016-10-07_11-41-26](https://cloud.githubusercontent.com/assets/1701077/19203904/ba3f3cf8-8c8e-11e6-90d3-008e26dbeec9.png)
![screenshot_2016-10-07_11-41-55](https://cloud.githubusercontent.com/assets/1701077/19203905/ba4005ca-8c8e-11e6-886e-bdcc09a51708.png)
![screenshot_2016-10-07_11-42-22](https://cloud.githubusercontent.com/assets/1701077/19203906/ba40f96c-8c8e-11e6-8aa4-65ba7f5634c8.png)
![screenshot_2016-10-07_13-01-34](https://cloud.githubusercontent.com/assets/1701077/19203907/ba454f08-8c8e-11e6-8a8d-fee2347defb4.png)

**Comment by thisisdano** [comment]
hm. dunno what it's doing but that looks very wrong

**Comment by thisisdano** [comment]
@msecret is this a branch I can look at?

**Comment by msecret** [comment]
https://github.com/18F/cg-style/tree/ms-change_typography

**Comment by thisisdano** [comment]
@msecret 
I don't yet see the 18Franklin fonts loading — I see Helvetica Neue.

<img width="955" alt="screen shot 2016-10-11 at 5 59 37 am" src="https://cloud.githubusercontent.com/assets/11464021/19271106/fb57ca48-8f77-11e6-952c-e22a7f0d0653.png">
