### ISSUE TITLE
Walk through end-to-end experience

### ISSUE THREAD

**Issue by vz3** [18F/cg-dashboard#660]
What we're after: 
- Review of overall experience to help us identify gaps in the current state
- Link to identified user types, look at pages with consideration of what these users might be looking for
- Use as opportunity to review and log user types

Journey map:
https://app.mural.ly/t/gsa6/m/gsa6/1477334854264

Story map:
https://18f.storiesonboard.com/m/gov-dev

Related:
https://github.com/18F/cg-design/issues/7

Acceptance criteria: 
- [x] Documentation of design gaps
- [x] Journey map (Mural.ly)

**Comment by suprenant** [comment]
What is the current experience? What is the experience we've designed? What are the gaps, and how to we prioritize our PI8 needs to meet this?

**Comment by suprenant** [comment]
@vz can be available to lead this if we do it around 9AM PST

**Comment by suprenant** [comment]
Noting that Victor and Dan can take this one on.

**Comment by suprenant** [comment]
Updated issue with links to WIP journey map and story map.

**Comment by suprenant** [comment]
From our meeting – if anyone wants to look through the Mural, please do and add comments there/Slack if anything feels like it's missing.
