### ISSUE TITLE
Evaluate CLI commands

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#675]
What we're after: 
- Go through CLI
- Identify elements that relate to App Lifecycle epic
- Flag elements that users would benefit from including in the dashboard

CLI mapping doc:
https://docs.google.com/a/gsa.gov/spreadsheets/d/1OEE9ybyQL7bAPR7OiqPnyVspxeVCLcy-h-Co-zu7YP4/

Acceptance criteria:
- [x] Dan, Victor, Aaron, Andrew have a work session to review current state
- [x] Flag for technical team member to review work 
- [x] Produce updated spreadsheet/update wiki

**Comment by suprenant** [comment]
I'll set this meeting up!

**Comment by suprenant** [comment]
This has been set for tomorrow.

**Comment by suprenant** [comment]
@thisisdano flagging that we discussed coming up with some action items from these.

**Comment by suprenant** [comment]
Talked with @msecret, he's going to take a look here and let us know if anything pops up.

**Comment by msecret** [comment]
I took a look at the doc, especially where we wanted to potentially add functionality and left notes.

**Comment by suprenant** [comment]
Sounds good. Closing this up
