### ISSUE TITLE
Create wireframe for Overview page

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#677]
What we're after: do a quick first sweep, illustrating functional components of this view:
- What is information presented?
- What are controls?

Acceptance criteria: 
- [x] Wireframes (screens) are created 
- [x] Screens labeled well enough that each section of the wireframe can communicate the contents of these pages and low-fidelity hierarchical relationship among the elements
- [ ] Actions are annotated with mapping to command line functions
- [ ] Write additional stories, as is needed, based on our findings of any additional desired functionality

**Comment by suprenant** [comment]
Noting that Dan and Victor are planning on pairing on these.

**Comment by thisisdano** [comment]
![overview-view 2x](https://cloud.githubusercontent.com/assets/11464021/19942785/27fa5350-a0f2-11e6-9e91-6519dd0214f5.png)
