### ISSUE TITLE
Create wireframe for Space page

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#678]
What we're after: do a quick first sweep, illustrating functional components of this view:
- What is information presented?
- What are controls?

Acceptance criteria: 
- [x] Wireframes (screens) are created 
- [x] Screens labeled well enough that each section of the wireframe can communicate the contents of these pages and low-fidelity hierarchical relationship among the elements
- [ ] Actions are annotated with mapping to command line functions
- [ ] Write additional stories, as is needed, based on our findings of any additional desired functionality

**Comment by suprenant** [comment]
Noting that Dan and Victor are planning on pairing on these.

**Comment by thisisdano** [comment]
![space-view 2x](https://cloud.githubusercontent.com/assets/11464021/19942830/4fa8bdd8-a0f2-11e6-9af1-419abce0c043.png)
