### ISSUE TITLE
Create wireframe for App page

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#679]
What we're after: do a quick first sweep, illustrating functional components of this view:
- What is information presented?
- What are controls?

Acceptance criteria: 
- [x] Wireframes (screens) are created 
- [x] Screens labeled well enough that each section of the wireframe can communicate the contents of these pages and low-fidelity hierarchical relationship among the elements
- [ ] Actions are annotated with mapping to command line functions
- [ ] Write additional stories, as is needed, based on our findings of any additional desired functionality

**Comment by suprenant** [comment]
Noting that Dan and Victor are planning on pairing on these.

**Comment by thisisdano** [comment]
![app-view 2x](https://cloud.githubusercontent.com/assets/11464021/19943715/de72e14e-a0f5-11e6-89fd-0a4b6acd1e88.png)

**Comment by thisisdano** [comment]
@suprenant FYI, these will not be linked in Invision — removing from DOD

**Comment by thisisdano** [comment]
Dunno if we'll link to CLI commands rn, either — may not be a good use of time
