### ISSUE TITLE
Working functional tests

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#680]
As a developer, enable automated browser-based functional tests so that we have high confidence that changes don't break existing functionality of the user interface.

This story is a spike, so it should be time-boxed to get an idea of the effort involved in the case where it's too much work to do in a reasonable amount of time.

**Spike acceptance criteria:**
- [ ] Identify the level of effort involved to accomplish the following criteria
- [ ] Identify the steps needed to accomplish the following criteria

**Acceptance criteria:**
- [ ] Functional tests run in CI
- [ ] Functional tests use the fake testing server

Note: there has been some progress made in the [ms-selenium_try branch](https://github.com/18F/cg-dashboard/compare/master...ms-selenium_try).

**Comment by adborden** [comment]
Updated the description.

**Comment by suprenant** [comment]
Noting that @msecret is planning to pick this one up
