### ISSUE TITLE
Prototype breadcrumb nav

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#681]
What we're after: 
- Users of the dashboard should be able to view a navigation that will let them
- Gives benefits of sidebar without consuming as much real estate

Things to keep attention on:
- Scenarios where there are many spaces, apps, orgs (e.g. more than 12-30 apps/space)
- Character lengths

Invision: 
https://gsa.invisionapp.com/share/838UY596S#/191691942_App-Overview

Acceptance criteria: 
- [ ] Produce prototype that we can test with users
- [ ] Determine our next regarding possible implementation or refactoring

**Comment by suprenant** [comment]
We'll discuss during sprint planning today the degree to which additional design is or is not needed here before we implement something.

**Comment by suprenant** [comment]
Noting: would be really helpful to have this in live, one-off environment

**Comment by suprenant** [comment]
Planning to put this on staging so folks can click around on it.

**Comment by adborden** [comment]
The changes to the dashboard are not going into a PR (they're going to sit on a branch fro the duration of the test) but are visible here https://github.com/18F/cg-dashboard/compare/adborden/breadcrumb-nav
