### ISSUE TITLE
Implement app usage and limits panel top

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#682]
[Invision](https://gsa.invisionapp.com/share/838UY596S#/screens/192771128_Usage-And-Limits--default)
Design issue: https://github.com/18F/cg-dashboard/issues/618

Implement a **read only** view of the top half of the app usage and limits panel containing current application usage. This does not include historical data.

**Acceptance criteria**
- [ ] New components are implemented in pattern library
- [x] Includes average memory usage across app instances
- [x] Includes average disk usage across app instances
- [x] Includes total memory usage for app
- [x] Includes total disk usage for app
- [x] Includes the number of instances for app

![screenshot from 2016-10-19 15-55-40](https://cloud.githubusercontent.com/assets/509703/19540799/c2515782-9616-11e6-9592-f8a04871e074.png)

**Comment by adborden** [comment]
description updated.

**Comment by suprenant** [comment]
Noting that we previously had discussed testing this.

**Comment by suprenant** [comment]
@thisisdano this looks good. Can you please point me where to validate this?
 - New components are implemented in pattern library

**Comment by thisisdano** [comment]
They are not in the pattern library

**Comment by suprenant** [comment]
OK thanks. That doesn't seem critical to the core value of this issue, so I'll pull that out from the criteria and close this up. LMK if that doesn't seem right.

**Comment by thisisdano** [comment]
ok to me
