### ISSUE TITLE
Create wireframe for Org page

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#683]
What we're after: do a quick first sweep, illustrating functional components of this view:
- What is information presented?
- What are controls?

Acceptance criteria: 
- [x] Wireframes (screens) are created 
- [x] Screens labeled well enough that each section of the wireframe can communicate the contents of these pages and low-fidelity hierarchical relationship among the elements
- [ ] Actions are annotated with mapping to command line functions
- [ ] Write additional stories, as is needed, based on our findings of any additional desired functionality

**Comment by thisisdano** [comment]
![organization-view 2x](https://cloud.githubusercontent.com/assets/11464021/19942816/43b54f82-a0f2-11e6-9878-e17fca98b3a4.png)
