### ISSUE TITLE
Improve error handling for 500 error case

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#687]
What we're after: 
-  So users know it's not that they lost access to all their orgs
 - If our services are down, we're really not showing
 - Need to handle error case when 500 error when data is being fetched, when we don't necessarily know that much about what's going on
 - Link to status page, suggest refreshing
 - 500 means something wrong with our service. If data isn't coming back for awhile, it's likely because of issue with user's internet connection

Only really needed when our service goes down (a few times/month?)
Related to critical system notification in wireframes
Could include metrics, track how often this happens and report in GA

When API down 
Fetching data

Do we want a bar at the top or full page here?

Notes on content:
 - Recommend to refresh?
 - Then, check cloud.gov status page

**Acceptance criteria**
- [ ] Any uncaught error should be displayed to the user through a banner message
- [ ] Message should advise the user to try to refresh the page
- [ ] The message is dismissible via the "X" button

**Testing**

There is an error triggered on the app page that can be used to verify the messaging.

**Comment by suprenant** [comment]
@thisisdano I think we discussed this one awhile back, FYI

**Comment by suprenant** [comment]
Next steps: meet to discuss further.

**Comment by adborden** [comment]
We do see a high number of errors even on a good day. I think we should take a closer look at the API requests that fail more often so we can exclude them. It would also be nice to generate a report for Atlas on the failures we see.

**Comment by adborden** [comment]
Pulling this out of icebox since we said we would address the error UI this PI.

**Comment by adborden** [comment]
Conceptual design https://gsa.invisionapp.com/d/main#/console/8652272/189361537/preview

**Comment by adborden** [comment]
Updated AC.

**Comment by adborden** [comment]
Loaded the app page and enabled offline mode with debug tools to simulate a fetch error. Looks good.
