### ISSUE TITLE
Speed up cg-style build by removing ruby repo

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#693]
In order for the cloud.gov team to quickly develop projects that use cg-style, the cg-style build should complete in under 3 seconds.

Some notes: 
 - Need to research how this works. 
 - Some Federalist task currently going on that could possibly eventually help with this.
 - We'd someone to help that knows Ruby well – may need support from the broader team.

Acceptance criteria
- [ ] Build should complete in under 3 seconds.
- [ ] There should be no separate repo for the ruby gem, and no repo cloning in the build.

**Comment by suprenant** [comment]
@msecret as discussed. Can you please take a look to refine the title and description here when you have a chance?

**Comment by adborden** [comment]
```
$ time npm run build
real    0m13.473s
user    0m11.592s
sys     0m0.908s
```

Without gem
```
$ time npm run build
real    0m8.154s
user    0m8.400s
sys     0m0.624s
```

Still not 3s, but still an improvement.

**Comment by suprenant** [comment]
Talked to @adborden, considering this done.
