### ISSUE TITLE
Link wiki/design principles to onboarding docs

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#695]

**Comment by suprenant** [comment]
As discussed during our planning meeting last week. This is likely a small change, but I went ahead and created this issue for tracking/visibility purposes.

**Comment by adborden** [comment]
@thisisdano I was going to add the design principles wiki to the onboarding docs but it feels like the docs already linked there maybe should move onto the wiki? https://github.com/18F/cg-product/blob/master/OnboardingChecklist.md#for-review
