### ISSUE TITLE
Research marketplace via SMEs

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#704]
What we're after: conduct internal research around how the marketplace might work:
 - How pricing works
 - How we should present information 

Rather than going off of our assumptions, we want to identify and talk with an SME to learn more here.

Docs:
 - https://docs.google.com/document/d/1mxf-fcJnRt4I6izB2Z0Mjnz9l0wGURje-lK9f8wr-fY/edit
 - https://docs.google.com/document/d/1rO7eBZdbp40jqaZ1wq-EKfNDDcP95UfJp5bDDDoPfGM/edit#

Acceptance criteria:
 - [x] Conduct an interview with Bret (on product details)
- [x] Conduct an interview with Bernd (on user-centric perspective – note: @brittag and @jameshupp are interested in joining this if time allows)
 - [ ] Synthesize notes/learnings
 - [ ] Share out with team

**Comment by suprenant** [comment]
@vz3 is on this one moving forward!

**Comment by suprenant** [comment]
Noting that this is scheduled for next week.

**Comment by mogul** [comment]
Can you add me to the invitation?

**Comment by vz3** [comment]
Done

**Comment by suprenant** [comment]
Noting that our followup session is now scheduled for Monday.

**Comment by thisisdano** [comment]
My takeaways from our meeting with @berndverst 

- Need good communication of service kind (“what does the service provide?”) / possible (pre-)sort
- CLI/API parity in language has potential drawbacks in comprehensibility
- Needs good feedback in creation flow to be clear what instance was created and where (flow needs to end with clarity, disambiguation, and finality)
- Error messaging should have a verbose option for support/debugging
- Should use service metadata to its fullest to provide proper service description and context
- Consider non-expert users, especially for the dashboard
- Service instance creation could be a natural UX pair with service binding

@vz3 @adborden @line47

**Comment by brittag** [comment]
Noting in case helpful: we may also need to mark some services as outside our P-ATO boundary, so that we can offer services for prototyping use before we've managed to get them included in our P-ATO.

**Comment by thisisdano** [comment]
@brittag That's another good candidate for inclusion in service metadata, as well as "alpha" or "experimental" tags if we ever expose services with those limitations

**Comment by vz3** [comment]
# Marketplace

- Purpose is to find and use/provision Cloud.gov services for application development needs.
- Renaming to ‘services’ would create a sync issue with CLI in which it’s called ‘marketplace’
- Services
    - Can be bound to multiple apps
    - Can be bound to no apps (effectively bound to space, e.g. deployer account, auto-sleep service)
    - Some services will need arguments upon creation
    - Are named upon creation
    - Might be organized into categorized (DB, CDN, etc.)
- Allow for the kind of service to be clear and someone can easily find a service by kind/type
- Provide information that users can easily give to support when issues are encountered

Priorities

- See what services are available - Some services users expect (databases) 
    - Make it easy to find one
    - What exists and how do i find out what different options are (what is available?     - What cost is associated with these services
- organization
	- Group my service type
	- Show which services got added (success state? maybe indicating which services already spun up)
- How do we validate with user that service is actually running?
- Discoverability of service

Other high level takeaways (from @dano)

- Need good communication of service kind (“what does the service provide?”)/ possible sort
- CLI/API parity in language has potential drawbacks in comprehensibility
- Needs good feedback in creation flow to be clear what instance was created and where (flow needs to end with clarity, disambiguation, and finality)
- Error messaging should have a verbose option for support/debugging
- Should use service metadata to its fullest to provide proper service description and context
- Consider non-expert users, especially for the dashboard
- Service instance creation could be a natural UX pair with service binding

**Comment by suprenant** [comment]
@vz3 @thisisdano looks good. Do we also want to link to this from the wiki as we've been discussing for research findings?

**Comment by adborden** [comment]
Added to wiki https://github.com/18F/cg-product/wiki/Marketplace-page
