### ISSUE TITLE
Restart app action

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#706]
In order for a developer to debug an issue with their app, there should be easy to find controls on the app page to restart their app.

Acceptance criteria:
- [x] There should be a blue button a the top of the page to restart an app.
- [x] The restart button should be disabled as the request is processing.
- [x] As the request for restarting the app is processing, the user should see the dotted, loading indicator next to the restart button, until the restart is complete (which could take minutes).
- [x] If an error occurs after the restart request is sent, there error should be presented to the user.

Design: https://gsa.invisionapp.com/d/main/#/console/8652272/191691942/preview

**Comment by suprenant** [comment]
We mentioned during mid-sprint review that this might take a little pairing with the design team to make sure our direction here is clear.

**Comment by suprenant** [comment]
@thisisdano the Invision link here also is dead. Can you please update so we can review and approve?

**Comment by suprenant** [comment]
Reviewing this – my app is stopped, and I'm unable to click the Restart app button. How can I start my app so I can test this functionality?

![screen shot 2016-12-27 at 5 36 07 pm](https://cloud.githubusercontent.com/assets/1452369/21510619/2da03204-cc5b-11e6-9a32-25919a7f0934.png)

**Comment by adborden** [comment]
:+1:
