### ISSUE TITLE
Show/set app-level instances

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#707]
In order for a developer to know information about specific instances of a scaled app, there should be information on each instance usage, and the ability to restart the instance.

Acceptance criteria:
- There should be a button to restart the instance, which provides feedback after both success or failure of the request, and will show an inline, dot, loading indicator after 300ms.

**Comment by msecret** [comment]
@thisisdano @suprenant I actually am having trouble finding the mockups for this, would either of you know where they are?

**Comment by thisisdano** [comment]
There are no mocks for this yet

**Comment by suprenant** [comment]
OK. @msecret, are you able to work on this, or should we flag it as needing design?

**Comment by msecret** [comment]
I think we'll need either a design or a pretty detailed feature description of how it's supposed to look and function.

**Comment by thisisdano** [comment]
I had something in the wireframes, but I fleshed it out a bit:

![app-instances 2x](https://cloud.githubusercontent.com/assets/11464021/20187548/8fc10c08-a729-11e6-97b0-845ddb0c88fd.png)

**Comment by msecret** [comment]
We don't have any information on instance usage / allocation, it's not part of the CF API, https://apidocs.cloudfoundry.org/246/apps/get_the_instance_information_for_a_started_app.html

**Comment by thisisdano** [comment]
Well then how do we know what an app is using if we don't know what an instance is using?

**Comment by msecret** [comment]
The API gives us information on what the whole app is using, it doesnt' give us any information on what each instance is using. The data might be somewhere, but it's not part of the API.

**Comment by thisisdano** [comment]
well this panel might be useless — if the platform automatically restarts crashed instances (which it does, I think, at least a few times), then there seems to be no meaningful role the user can take.

Is there a reason to start/stop a specific instance if you have no data on it?

Might there be "stuck" instances that need a manual restart?

**Comment by msecret** [comment]
I personally never thought there was a reason to restart a specific instance. But might not be a bad idea to ask some other 18F cloud.gov users? I can post question in a channel?

**Comment by thisisdano** [comment]
that sounds good, thanks

**Comment by msecret** [comment]
@thisisdano it sounds like most users wouldn't have a reason to restart and instance. Should we cancel this feature and close this issue?

**Comment by thisisdano** [comment]
Given the information we have, that seems reasonable.

**Comment by suprenant** [comment]
Closed this issue based on above discussion of not having a strong need for this at the moment.
