### ISSUE TITLE
Build out space page (general layout)

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#709]
In order for developers to see all app statuses for a space, AND see information related to a space such as users and services, there should be a space page.

Acceptance criteria:
- [x] The user should see an app status count and a service status count at the top of the page to get quick information if any app is broken and how many services there are.
- [x] For each app, there will be allocation and usage information so a dev can quickly see the resource details of the apps.
- [x] There should be a button to add a new service instance that goes to the marketplace page.
- [x] There should be a link to documentation on pushing a new app.
- [x] The existing user management and service instance pages should be displayed as separate panels.

Noting for current sprint:
 - General space page layout

**Comment by msecret** [comment]
This is the primary design we'll be working on:

![screen shot 2016-12-01 at 1 27 59 pm](https://cloud.githubusercontent.com/assets/1701077/20813037/ec3a4ae4-b7c8-11e6-8c21-7daf34dc151f.png)

**Comment by suprenant** [comment]
Thanks for grooming this one out, @msecret. I'm creating a new issue for possible followup work.
