### ISSUE TITLE
Consider additional patterns (users)

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#714]
What we're after: consider what additional patterns we might develop during this sprint. 

Mentioned for consideration of other ongoing patterns:
 - Confirming that patterns we have continue to work in new cases to which we apply them
 - Pattern work could generally continue throughout PI
 - For this sprint, new panels/patterns could be the focus

Thinking for current sprint (8.2):
 - [ ] Users (users panel for Org page, mgmt of existing users, assigning roles)

**Comment by thisisdano** [comment]
Duplicate of https://github.com/18F/cg-dashboard/issues/737
