### ISSUE TITLE
Audit org page

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#719]
What we're after: flesh out the design and implementation of the org page.

Process:
 - Review Sketch file

Notes: 
 - Bring elements from wireframes into this view
 - Ensure that core functionality is implemented
 - Pretty broad, not sure if we want to do this
 - Procedurally similar to overview page

Consider research:
 - Remove sidebar 
 - Remove dependencies on sidebar

Goal: Functional dashboard without sidebar.

Acceptance criteria:
 - [ ]

**Comment by suprenant** [comment]
@vz3 noting that we actually highlighted this for Sprint 8.5, so we don't necessarily need to groom it right away

**Comment by vz3** [comment]
edits made.

**Comment by suprenant** [comment]
@thisisdano will take a pass to split this up and groom further and then review with @msecret / rest of team.

**Comment by suprenant** [comment]
This is covered elsewhere
