### ISSUE TITLE
Create navigation patterns for Overview page

### ISSUE THREAD

**Issue by thisisdano** [18F/cg-dashboard#722]
Whether or not we use a sidebar navigation, the overview page needs to provide access to organizations, spaces, and apps in the primary content panel. To test the breadcrumb nav, this content is critical. Before we test the breadcrumb nav, we need to implement a design for the overview page that includes this content.

- [ ] Use overview wireframes to create a navigation layout for the overview
- [ ] Communicate these patterns to development

**Comment by thisisdano** [comment]
This is nearly done. 
Based on sketch session with @vz3 last sprint. 

![overview-panel 2x](https://cloud.githubusercontent.com/assets/11464021/20276512/c2b1586a-aa59-11e6-85fc-b2a9dda05eef.png)

**Comment by vz3** [comment]
Thank you for catching this

**Comment by thisisdano** [comment]
Here's a revision of the Overview page.

- Adds page header
- Better communication of app states
- App start action for stopped/crashed apps
- Cleaner use of color
- Experiment with "dashboard" indicator in header
- Experiment with different top nav contents

See https://github.com/18F/cg-dashboard/issues/712 for more thinking on the top nav.

- - -

![screen shot 2016-11-22 at 9 16 43 am](https://cloud.githubusercontent.com/assets/11464021/20534566/872cc14c-b096-11e6-9784-9420061a262a.png)

**Comment by msecret** [comment]
Some notes on performance:

- I think we should hold off on the "Default to expanded view" for now because it has dangerous performance implications for people in many orgs.
- I think we should not show the number of apps for an org before it's opened. Doing so requires fetching a lot of data for each org, which has performance implications. I'm fine showing the amount of apps after they open the org up, but not before.

Does the design need to change at all considering these performance restrictions?

**Comment by thisisdano** [comment]
@msecret 

#1: OK — though I'd like to default to open for users with 3 or fewer orgs
#2: That feels like a bridge too far. Part of the benefit of this page is scanability. What is the real performance implication of showing number of apps (and an indication of app status) in the closed state?

**Comment by thisisdano** [comment]
If it is a big performance hit with the current data structure, can the way the data is stored be improved to improve performance?

**Comment by msecret** [comment]
So for each org, we have to fetch each app in each space for each org. So if you have 10 orgs, with 5 spaces with 2 apps each, 10 * 5 * 2. It could be way more orgs for for certain users.

So we can do an app count, from the space data but this wouldn't include the app status whether it's failing or not. Is that an OK compromise?

**Comment by thisisdano** [comment]
Hm — I see the numbers but don't have a sense of what that means in raw "performance".

Could each org's "data profile" have a piece of data (field?) that indicates if it has a crashed or stopped app — some piece of data that "pushes" up to the org level without an app call? Some kind of background process? We could default to green (OK) status if the org includes none of that data, and show stopped/crashed indicators that data exists.

Forgive my ignorance with database terminology. I just want this to be as useful as possible.

**Comment by thisisdano** [comment]
OR, in the simplest case — suspend some functionality only in cases of some large number of orgs (say > 10)

**Comment by msecret** [comment]
That does make sense, but we're unfortunately confined to how the cloud foundry API works. So we can't really change the API to add this functionality for various reasons.

The only thing I can think of is to only have the status data once you've gone to that app (although I'm not sure how useful that would be). So once you go to the app level, that data becomes available, and we can show it here.

**Comment by msecret** [comment]
Thats another idea, so only fetch data for the first 10 ors?

**Comment by thisisdano** [comment]
Yeah, like a lazy-load option.

Or, if < 10 orgs, fetch all data — if > 10 orgs, fetch some limited subset of data (no status, to be sure — or perhaps also no # of apps, too... — if, like a ridiculous # of orgs)

**Comment by msecret** [comment]
That sounds possible, although will add complexity to completing the feature. I'll come up with a general design for the code and provide some estimations of how long things will take and we'll decide from there.

**Comment by thisisdano** [comment]
Awesome, thanks Marco

**Comment by suprenant** [comment]
Talking with @thisisdano now – for the sake of this issue, he's going to do a little cleanup, and this will then be ready for implementation, pending our hashing out any related performance issues together.
