### ISSUE TITLE
Design additional patterns (Contents panels at Org/Space level, Org/Space usage)

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#735]
What we're after: consider what additional patterns we might develop during this sprint. 

Mentioned for consideration of other ongoing patterns:
 - Confirming that patterns we have continue to work in new cases to which we apply them
 - Pattern work could generally continue throughout PI
 - For this sprint, new panels/patterns could be the focus

Pending:
 - [ ] Contents panels at Org/Space level
 - [ ] Usage at Org/Space level

Related: #714

**Comment by suprenant** [comment]
Thinking @line47 could possibly help here.

**Comment by suprenant** [comment]
Breaking out Services/Marketplace to separate issue.

**Comment by thisisdano** [comment]
OK — making progress. Here's my first pass at a view of usage/quotas at the org level — kind of a mashup of the App limits and the overview contents, with a focus on allocation and costs. Maybe not perfect, but a step toward better communication of this data.

[Sketch](https://github.com/18F/cg-design/raw/dw-sketch/Sketch/cg-atomic-bass.sketch)
[Invision](https://gsa.invisionapp.com/share/838UY596S#/207322451_Org)

@vz3 @line47 @msecret 

![org-usage-quotas](https://cloud.githubusercontent.com/assets/11464021/20732702/ca83d832-b644-11e6-81d1-fd109bdce4f1.png)

**Comment by line47** [comment]
I think these look great! 

I'm wondering about if the vertical indicator to the left of disk quota and service quota are needed when the status is healthy or good (green)?

**Comment by vz3** [comment]
Let's consider refactoring the presentation of services vs apps as discussed post-usability testing. Otherwise I think this is good to go 👍

**Comment by vz3** [comment]
Last point will be addressed by an issue coming out of last round of research notes for #716. good to go otherwise. closing.
