### ISSUE TITLE
Design controls for users and roles

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#737]
Managers need to be able to easily assign roles to users at their hierarchical level. All users need to be able to see their role assignments, edit if possible, and see other users in their orgs and spaces.

The current layout is complicated to read and edit, with incomplete action feedback.

A successful pattern:

- [ ] Allows appropriate users to modify roles
- [ ] Allows all users to see role assignments
- [ ] Prevents users with space roles but no org role
- [ ] Prevents orgs with no manager
- [ ] Prevents irreversible demotion of privileges

**Comment by thisisdano** [comment]
### Org Users

**Wireframe**

![org-users 2x](https://cloud.githubusercontent.com/assets/11464021/20444901/c5e88f04-ad87-11e6-9adf-112aa5146cb5.png)

**Patterns**

![org-users 2x](https://cloud.githubusercontent.com/assets/11464021/20444918/d6e5fa80-ad87-11e6-93d3-777874bcfbfe.png)

### Space Users

**Wireframe**

![space-users 2x](https://cloud.githubusercontent.com/assets/11464021/20445095/9d7dc0ce-ad88-11e6-9062-026311a06074.png)

**Patterns**

![space-users 2x](https://cloud.githubusercontent.com/assets/11464021/20445114/a7fc93a4-ad88-11e6-9138-b7e7979063f3.png)


[Sketch](https://github.com/18F/cg-design/blob/dw-sketch/Sketch/cg-atomic-bass.sketch)

**Comment by thisisdano** [comment]
@line47 @vz3 Users panel, y'all. ^^^

Peep the notes — there's a bunch of little logic things...

**Comment by msecret** [comment]
So one thing that we might need to add (that I'm pretty confused about actually), let's say we have a user that has no current permission in a space or org. How do we add them to that space or org with their 1st permission.

Currently, the user won't even show up in the user list, because they're not considered an org or space user until they have probably at least one permission in the space or org. So the interface would need to take a user email/name input and the permission to add.

This might need to be looked into more, as I'm pretty confused how this works.

**Comment by thisisdano** [comment]
I suppose my position on this is that we're not ready to add "add a new user to this org" functionality to the dashboard at this point. (It's marked as 'to come" as an element in my wireframe and my patterns.) I think the mechanism for doing this is too complicated to add at this point and it's better to spend our energy improving the experience of existing functionality.

**Comment by thisisdano** [comment]
That said, if a user has permissions in an org _just not in a space_, users with Manager permissions could assign a space role in the space users panels I've designed above by selecting the appropriate editable tag. (All org users appear in the space users panel to users with Manager permissions.)

**Comment by msecret** [comment]
Yea that makes sense, although its the functionality that I require the most.

**Comment by thisisdano** [comment]
In the future, tho, I'd imagine an org manager could select an "Add user" button as shown below and be prompted to add an email and set org and space roles at that time. The new user would then get an email with this invitation and the roles set. The panel would show a pending invitation message until the user accepts and establishes the account. (Through some dashboard mechanism.) But there are numerous flow complexities that keep it from being achievable in this PI, imo.

<img width="483" alt="screen shot 2016-11-18 at 2 05 35 pm" src="https://cloud.githubusercontent.com/assets/11464021/20448307/297b1edc-ad98-11e6-9a74-569195cbc740.png">

**Comment by vz3** [comment]
Accepting this design let's figure out next steps.

**Comment by suprenant** [comment]
Great, thanks. Issue for followup implementation: https://github.com/18F/cg-dashboard/issues/761
