### ISSUE TITLE
Edit app usage and limits

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#739]
In order for a developer to quickly change memory or disk usage to fix a at risk or broken app, there should be controls to modify app limits.

Acceptance criteria:
- [x] There should be an edit button on the panel that starts the editing process.
- [x] Instance memory, disk and scale should be editable with form to change values.
- [x] If any changes to limits causes a quota problem, it should be expressed with warnings.
- [x] If the request to change the values takes more then 500ms, there should be a loading indicator displayed across the whole panel.
- [x] If an error occurs while changing values, an error message should be displayed at top of panel

E.g. modify, change values

We have designs for this in the usage and allocation panel
Notify design if there is a state that is still needed

**Comment by suprenant** [comment]
In talking to @msecret, we're thinking someone picking this up that is _not_ him (e.g. @adborden @line47) could be helpful to diversify the eyes we have on this area.

**Comment by msecret** [comment]
### API design
Should use the following API method: https://apidocs.cloudfoundry.org/246/apps/updating_an_app.html

```
// cf_api
putApp(appGuid, app) {
  // app should probably be a full app object, not just the values to update
  http.put(`/apps/{appGuid}`, app).then((res) =>{
    appActions.updatedApp(res.data);
  }).catch((err) => {
    appActions.error(err); // Re-use but have to place error message at top.
  });
}
```

**Comment by msecret** [comment]
### Action design

Pass full app object. Pass the appGuid separately to cf_api because it's actually required by the URL to call, but here can just be full object.

```js
updateApp(app) {
  APP_UPDATE
}

updatedApp(app) {
  APP_UPDATED
}
```

**Comment by msecret** [comment]
### Store design

Depending on above, whether it's easier for `updateApp` to take partial updates or full app object, should merge the partial updates with the full app object, then set `updating` property to true, in same vein as `error` property in restart app code.

```js
  on APP_UPDATE:
    const existingApp = this.get(action.appGuid);
    const mergedApp = Object.assign({}, existing, action.updates);
    const updatingApp = Object.assign({}, merged, { updating: true });
    cfApi.putApp(action.appGuid, updatingApp);
    this.emitChange();

  on APP_UPDATED:
    const app = this.get(action.app.guid);
    this.merge('guid', action.app);
    this.emitChange();
```

**Comment by suprenant** [comment]
In standup today, we discussed that the app will restart and be down when limits are edited. @adborden and @thisisdano are going to pair on this item and let us know where they land so we can make sure we have a good direction here.

**Comment by adborden** [comment]
@thisisdano and I chatted about this, there is an existing polling pattern we use for the app restart, that sounds like it would be a reasonable solution. Once the update is triggered, we know the app will restart. If we poll the app every second or so, the UI will update and the inline loading indicator will say "updating app" so the user knows the app is restarting. The stats will drop to zero (because the instances are stopped) and then will jump up once the instance count is greater than 0, at which point the inline loading indicator will disappear.

In an ideal world, the app could subscribe to real-time events from the cloud.gov pattern and update in near-realtime. We are not there yet.

**Comment by suprenant** [comment]
Looks good to me
