### ISSUE TITLE
Design interaction for creating a new space

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#741]
What we're after: design functionality/interaction so users can create a new space

Notes: 
 - Will need to determine where the button goes and how interaction works
 - Related to contents panel on org page
 - Discussed possibly functionality about a form with prefilled details, but not sure if this would fit in an MVP

Acceptance criteria:
 - [ ] A button (and additional interactive elements) are available with copy indicating they can be used to create a new space
 - [ ] A new space is created when the interaction is executed

**Comment by suprenant** [comment]
I think this came up when @thisisdano and I were talking about the overall experience.

**Comment by suprenant** [comment]
On review, this really wasn't groomed enough to be in Ready. Backing this out for now. Had planned on this being part of Sprint 8.3.

**Comment by msecret** [comment]
API method: https://apidocs.cloudfoundry.org/246/spaces/creating_a_space.html

**Comment by suprenant** [comment]
Do we also want to include the action for removing a space? I think we had discussed this previously.
