### ISSUE TITLE
Provide instructions on creating a new app in an empty space

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#742]
When a space is empty, we should tell the user how to create a new app.

Copy proposal from @adborden:
> From your code directory, use the cloud foundry CLI to push your code.
`$ cf push my-new-app-name`

--

What we're after:
 - Design what this functionality/interaction will look like (space-level item)

Notes:
 - This is related to contents panel on org page
 - Previously noted that we might want to do research around this

**Comment by suprenant** [comment]
I think this came up when @thisisdano and I were talking about the overall experience.

**Comment by suprenant** [comment]
On review, this really wasn't groomed enough to be in Ready. Backing this out for now. Had planned on this being part of Sprint 8.3.

**Comment by vz3** [comment]
For documentation's sake, where did this story come from? I imagine whomever did can talk about what this feature would actually do.

**Comment by suprenant** [comment]
@vz3 I believe we had flagged it during PI planning as "Create app from deck (or link to instructions)"

https://app.mural.ly/t/gsa6/m/gsa6/1476664708352

At that time, I don't think we were sure whether or not this would need further design, but we since flagged it as possibly needing some.

**Comment by adborden** [comment]
Right, a new user has no apps in the dashboard, how do they create one? That's what this story is about. They drop to the CLI  and use `cf push` to push their code. But the user doesn't know that from the dashboard. The MVP for this story could be a link to https://cloud.gov/docs/getting-started/your-first-deploy/ or a brief description like:

> From your code directory, use the cloud foundry CLI to push your code.
> `$ cf push my-new-app-name`

**Comment by vz3** [comment]
@suprenant Right but what does that button do? Because there needs to be code to roll out an app.

@adborden I dig this. Super helpful. Thx

**Comment by vz3** [comment]
@adborden What if this button rolled out some sort of "Hello World" app? Would that be a best practice? It seems usable but also feels weird bc we'd be providing code.

**Comment by vz3** [comment]
Just capturing this: this issue might be renamed to:
> Provide instructions on creating a new app in an empty space.

If we go with @adborden's idea for MVP.

**Comment by adborden** [comment]
I think this is the same card https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-1170
