### ISSUE TITLE
Dashboard build process doesn't correctly display JSX errors

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#743]
Background: A while ago, we had to change our build because our tests were not stopping when there was a syntax error in the test file. Instead, the test file would be skipped over, so the developer could commit code to production that had broken tests. Unfortunately this change introduce a  new bug where the build won't accurately or legibly display syntax errors in JSX and other files.

An example of error being displayed incorrectly:
```
Error: "BabelLoaderError: SyntaxError: Unexpected token (26:2)\n\n\u001b[0m  24 |   active\u001b[1m:\u001b[22m \u001b[36mtrue\u001b[39m\u001b[1m,\u001b[22m\n  25 |   loadingDelayMS\u001b[1m:\u001b[22m LOADING_TIME\n> 26 |   style\u001b[1m:\u001b[22m \u001b[31m'cover'\u001b[39m\n     |   ^\n  27 | \u001b[32m}\u001b[39m\u001b[1m;\u001b[22m\n  28 | \n  29 | \u001b[36mclass\u001b[39m Loading \u001b[36mextends\u001b[39m React\u001b[1m.\u001b[22mComponent \u001b[32m{\u001b[39m\u001b[0m\n"

```

Example of how same error should look:
```
BabelLoaderError: SyntaxError: Unexpected token (26:2)

  24 |   active: true,
  25 |   loadingDelayMS: LOADING_TIME
> 26 |   style: 'cover'
     |   ^
  27 | };
  28 |
  29 | class Loading extends React.Component {
```

Fix: 
A. Have configuration to only turn on the feature that stops tests with a syntax error on single test runs OR test runs that run on a CI server. This ensures that broken test files will never be committed because will be caught at CI level while devs still have easier debugging during local development. Less risky option, easier to configure.
B. Attempt to fix build so tests stop on syntax errors AND errors display correctly. I currently don't know how this would be done. Riskier option because more unknown.

**Comment by suprenant** [comment]
Discussed, thinking Fix A is way to go.

**Comment by adborden** [comment]
Confirmed fix.
