### ISSUE TITLE
Analyze push functionality 

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#744]
From sprint planning: 
From CLI map
Aaron/Bret talked, been thinking about this
Have to drop to CLI to push first app
URL to Github repo, push it for user
Not sure if we have time for this
Create app. Start button would be a push?
What is code for doing this? Creates shell/container, could push app there
Heroku: Heroku button, one-click thing to let someone fork an app, input details/variables, creates repo for user
Documentation could be useful at the very least
Research how people are going to create apps, if/how CLI is useful. CLI can ask questions?

**Comment by suprenant** [comment]
On review, this really wasn't groomed enough to be in Ready. Backing this out for now. Had planned on this being part of Sprint 8.3.

**Comment by adborden** [comment]
Sounds like from our sprint review, this has been promoted as a feature for the next PI. It would still be nice to do some research here and as a stretch maybe find time to do an MVP for this.

**Comment by msecret** [comment]
Yea one of my concerns for next PI is that there won't be a design team, so doing some work now could be a big help.
