### ISSUE TITLE
Audit App page to determine and prioritize missing elements

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#745]
What we're after: flesh out App page

Review Sketch file/InVision docs
Elements should map to functional pieces we have now
Bring them, stylistically, up to the level of the design work

Process/acceptance criteria: 
 - [x] Developer and @thisisdano pair to go through App page, determine what is missing (e.g. fonts/colors)
 - [x] Create punch list of missing items
 - [x] Determine with team which of these punch list items should be prioritized and make additional issue(s) for that work

This will include: https://github.com/18F/cg-dashboard/issues/648

**Comment by suprenant** [comment]
Updated acceptance criteria after talking through process with @adborden

**Comment by suprenant** [comment]
@line47 and @thisisdano will be meeting on this one soon.

**Comment by line47** [comment]
@thisisdano and I went over this issue today and I'll be tackling this early next week!

**Comment by line47** [comment]
Missing items between the Sketch file and my local instance are as follows:

### Header Updates
1. Move Application name into heading under the navigation
2. Setup breadcrumb dropdown for organization navigation
    1. What about removing the home icon from the beginning of the breadcrumb? Won’t clicking the cloud.gov logo in the heading take the user to the same location?
3. Update log out link style to a button
4. Add help link to the header navigation
5. Remove About and Contact links from the navigation 
    1. what about putting those links into a footer?
6. Align open app and restart app buttons to the right of the page.

### Usage and Allocation Updates
1. Add View more data for usage and stats at kibana.cloud.gov
2. Change “App scale 2x” text to “Instances” and change explanatory text to “Instances applies to memory and disk”
3. Round top and bottom borders on instance memory used amounts
4. Color code instance memory used bars based on the memory being used. Green, Yellow, Red.
5. Color code space available based on space being used. Green, Yellow, Red.
6. Show trending direction based on data from last week. Example: + 14 MB from last week
7. Adjust font weight of content to make lighter
8. Add button for modify allocation and scale
9. Add 7 day sparkline chart for memory usage and disk usage.
    1. Show the min and max used during this 7 day window
10. Add bar chart showing memory used vs memory available
    1. Color code the data based on how much is remaining. Green, Yellow, Red.
11. Add bar chart showing disk space used vs disk space available
    1. Color code the data based on how much is remaining. Green, Yellow, Red.
12. Add bar chart showing memory allocated, memory used and memory available
    1. Color code the data based on how much is remaining. Green, Yellow, Red.
13. Add bar chart showing disk space allocated, disk space available and memory available
    1. Color code the data based on how much is remaining. Green, Yellow, Red.
14. Add organization quota link to total memory and total disk space allocated

**Comment by thisisdano** [comment]
I think the only things I'd add right now are to take a look at the add/edit route action (and perhaps all actions) and see what needs to change in the action states.

**Comment by msecret** [comment]
I'm confused by some of what's missing such as

4. Change Unbind button to a link
5. Add Delete and Bind links to route available items

Where in the wireframes in the Unbind button a link? The current dashboard has Delete and Bind links/buttons.

**Comment by thisisdano** [comment]
@msecret here's the invision link to the app page and the current panel layouts: https://gsa.invisionapp.com/d/main#/console/8652272/191691942/preview

**Comment by suprenant** [comment]
Noting that @vz3 will go through this to develop some sort of prioritized list for us to decide what to tackle.

**Comment by vz3** [comment]
https://docs.google.com/a/gsa.gov/spreadsheets/d/1WJ4Vh29Jr3e_u3xLiNBW-lotnhcK25FVmtLCYWHpVz8/edit?usp=sharing
