### ISSUE TITLE
Don't use filesystem store

### ISSUE THREAD

**Issue by jmcarp** [18F/cg-dashboard#751]
We're currently using the filesystem session store. That means session data isn't shared across app instances, so if we ever scale to more than one instance, users will be load-balanced between instances with potentially different local session stores. To fix, we can switch to a shared session store, like the redis store. Alternatively, we can use [sticky sessions](https://docs.cloudfoundry.org/concepts/http-routing.html) to avoid users switching between instances, but we'd still lose session data on restart.

**Comment by adborden** [comment]
No sticky sessions, a redis-like solution is preferred, IMHO.

**Comment by mogul** [comment]
@suprenant what do you think about pulling this one out of the icebox? (With just one instance, we are subjecting users to potentially flaky behavior when cloud.gov is updated and the single dashboard app instance gets rolled to another host, so I'm suggesting that resolving this is appropriate if we're calling dashboard production-worthy.)

**Comment by suprenant** [comment]
@mogul sounds good – will discuss with the team and follow up here.

**Comment by jmcarp** [comment]
PR at #905.

**Comment by suprenant** [comment]
Noting that this issue will be complete once #905 is merged, though we want to do more thorough review and testing of that PR. @adborden may pick this up next week.
