### ISSUE TITLE
Fix memory leak on space detail view

### ISSUE THREAD

**Issue by jmcarp** [18F/cg-dashboard#757]
On some space detail views, I see a `possible EventEmitter memory leak detected` warning in the console--for example, https://dashboard.fr.cloud.gov/#/org/4175a5b2-78a4-42b0-94c2-280f8be41e7f/spaces/4a543094-ecff-43b5-a4a2-43886a892e4a/apps/cded9067-5b8e-4fcb-9acc-24d44b88983c.

<img width="891" alt="screen shot 2016-11-21 at 7 43 40 pm" src="https://cloud.githubusercontent.com/assets/1633460/20506543/dbc7117c-b022-11e6-9a3f-e0e8757def9d.png">

We may have unused event listeners hanging around that aren't being cleaned up, in which case we should drop them when we're done using them. If not, we can bump the limit on listeners: http://www.jongleberry.com/understanding-possible-eventemitter-leaks.html

**Comment by msecret** [comment]
Thanks @jmcarp, I've seen this before and keep forgetting to write it somewhere to track it. I've investigated a bit and I don't think theres a leak. I think it's just a lot of listeners due to how the flux system works. We should probably set the max to more then 11.
