### ISSUE TITLE
Form on #about needs a legend

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#758]
@msecret commented on [Thu Jun 30 2016](https://github.com/18F/cg-landing/issues/80)

Form at the bottom, Fieldset requires a legend

---

@msecret commented on [Thu Jun 30 2016](https://github.com/18F/cg-landing/issues/80#issuecomment-229816433)

Ref https://github.com/18F/Accessibility_Reviews/issues/18

**Comment by brittag** [comment]
This is probably better as a cg-site issue rather than a cg-dashboard issue, since it's about https://cloud.gov/#contact

**Comment by suprenant** [comment]
Issue moved to [18F/cg-site #594](https://github.com/18F/cg-site/issues/594) via [**ZenHub**](https://www.zenhub.com/)
