### ISSUE TITLE
Notify customers of shutdown cg-deck at console.cloud.gov

### ISSUE THREAD

**Issue by adborden** [18F/cg-dashboard#760]
We'd like to stop support for the old cg-deck app at https://console.cloud.gov/. We don't really have the resources to keep it up to date with security patches.

There are a handful of users of console.cloud.gov, we can engage them about shutting down the service. From slack:

> send quick emails to the two people who have preferred it (an EPA person and Noah) letting them know it's gone due to rotting code and that they are welcome to reach out to the Navigator squad for discussion about the pros and cons of the new dashboard

cc @brittag 

Acceptance criteria:
 - [x] Email Noah Kunin 
 - [x] Email EPA contact

**Comment by suprenant** [comment]
@brittag can you please send me the contact information of the EPA user so I can get in touch with  them? I don't know who it is.

**Comment by brittag** [comment]
👍  Sent in Slack!

**Comment by suprenant** [comment]
Emailed Noah and Michael – this is done.
