### ISSUE TITLE
Design additional patterns (Services/Marketplace)

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#763]
What we're after: develop additional patterns

Mentioned for consideration of other ongoing patterns:
 - Confirming that patterns we have continue to work in new cases to which we apply them
 - Pattern work could generally continue throughout PI
 - For this sprint, new panels/patterns could be the focus

Acceptance criteria:
 - [ ] Deliver designs for Services/Marketplace

Related: #714

**Comment by thisisdano** [comment]
At long last, some progress!

Here's the start of a Marketplace panel that would live at the space level:

![screen shot 2016-12-05 at 12 47 41 pm](https://cloud.githubusercontent.com/assets/11464021/20901834/42b4a306-bae9-11e6-8052-0e4962d05809.png)


Working on the actions now.

Here are the relevant assets:
[Invision](https://gsa.invisionapp.com/share/838UY596S#/207322417_Space)
[Sketch](https://github.com/18F/cg-design/raw/dw-assets/Sketch/cg-atomic-bass.sketch)
[18Franklin](https://github.com/18F/18franklin/tree/master/fonts/otf)

@vz3 @line47

**Comment by line47** [comment]
This looks great @thisisdano

**Comment by vz3** [comment]
Seconded 😍

**Comment by msecret** [comment]
Looks awesome. As discussed previously, we will need to update the actual data for our services in a different part of our cloud foundry stack to implement this.

**Comment by thisisdano** [comment]
@msecret yeah, for sure — though it looks like the content team is actually developing this content (i.e. it lives in the docs now at least) so there's a starting point!

**Comment by thisisdano** [comment]
docs link: cloud.gov/docs/services/

**Comment by thisisdano** [comment]
Also, I'd sent this along to Scott, but here are the service icons as svg: https://github.com/18F/cg-design/tree/dw-assets/assets/icon/services

**Comment by thisisdano** [comment]
Invision of an `add service instance` action flow here: https://gsa.invisionapp.com/share/838UY596S#/209840512_Marketplace-PlanHover

You just need to page through with arrow keys :)

Working on a more complex flow for advanced options next.

**Comment by thisisdano** [comment]
Create service instance flow for services with options: 
https://gsa.invisionapp.com/share/838UY596S#/209994627_Marketplace-Adv-Default

See docs on this service for context: https://cloud.gov/docs/services/cdn-route/

**Comment by mogul** [comment]
😍

**Comment by suprenant** [comment]
@vz3 to review – pending this, we'll consider this done.
