### ISSUE TITLE
Start button for apps on overview page

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#765]
In order for a developer to quickly fix a broken app, there should be a start button the the overview page.

Acceptance criteria:
- [ ] When an app has crashed or is stop, the  button should "start" the app.
- [ ] When an app is being started, there should be a loading indicator until it starts.
- [ ] The start button should be disabled while the app is starting.
- [ ] If an error occurs while starting an app, an error message should appear inline next to the button.

**Comment by suprenant** [comment]
Noting that we're not sure whether or not we need to pick this up or not given that this functionality exists on the app page. We'll discuss during sprint planning.

**Comment by thisisdano** [comment]
It's maybe a nice-to-have, but, that said, once we have the feature on the app page we out to be able to plonk it anywhere.

**Comment by adborden** [comment]
An app start button now exists https://github.com/18F/cg-dashboard/pull/977
