### ISSUE TITLE
Implement multi-tiered status bar for org quick look

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#766]
In order for a developer to see 3 status bars to get a general sense of app status when look at an org, there should be a status bar that can show three statuses.

Design: https://github.com/18F/cg-dashboard/issues/722 

Acceptance criteria:
- [ ] There should be a status bar that can be placed at the bottom of a panel row
- [ ] If all apps are running/green, the whole status bar should be green
- [ ] If one or more apps is crashed/red, or stopped/black there should be a green status and red/black status part of the bar
- [ ] If there is more then one app(s) that are both crashed and stopped, there should be both red

**Comment by msecret** [comment]
![image](https://cloud.githubusercontent.com/assets/1701077/20635063/0ad7959e-b326-11e6-8927-031afcd770f1.png)

**Comment by suprenant** [comment]
@vz3 is going to take a look at the design here before we implement anything.

**Comment by thisisdano** [comment]
To clarify the purpose of the status bar:

![artboard 2x](https://cloud.githubusercontent.com/assets/11464021/20840241/6ad6490c-b864-11e6-9341-8aea27e05463.png)

So, there could be two bars below if there are only two statuses in the org. 

And @msecret you can find all icon variations here: https://github.com/18F/cg-design/tree/dw-assets/assets/icon

Probably a few quirks/inconsistencies to work out here, but I think it works as a implementable pass.

**Comment by suprenant** [comment]
Flagging that we still need review on this, but it's not holding us up at the moment.

**Comment by suprenant** [comment]
@vz3 nudging here – can you please take a look before sprint planning on Thursday and slate it in the queue based on your thoughts of relative priority? 

If you don't think it's a priority for this coming sprint, please put it at the top of the Icebox, and we can take a look next time we plan.
