### ISSUE TITLE
Implement App page audit findings

### ISSUE THREAD

**Issue by line47** [18F/cg-dashboard#769]
It would make sense to break the work down by panel. 
I have already broken down the app page audit in this way. See: https://github.com/18F/cg-dashboard/issues/745
For example: Routes, Services, Recent Activity, etc...

**Comment by suprenant** [comment]
Noting that @vz3 will go through this to develop some sort of prioritized list for us to decide what to tackle.

**Comment by vz3** [comment]
Priority doc here

https://docs.google.com/a/gsa.gov/spreadsheets/d/1WJ4Vh29Jr3e_u3xLiNBW-lotnhcK25FVmtLCYWHpVz8/edit?usp=sharing

**Comment by suprenant** [comment]
@line47 to groom further with support from @vz3 and me as needed

**Comment by suprenant** [comment]
@line47 looks good – I believe these are now all incorporated in other issues, so I'm closing this up. Please let me know if that's not the case.

**Comment by suprenant** [comment]
@vz3 on review, I could use your input here. What is your intended priority here? 

For now, I'll back out all of these issues of this sprint, but let's discuss ASAP to determine what we might want to (and be able to) include).
