### ISSUE TITLE
Link for activity to logs.cloud.gov

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#770]
What we're after:
 - Have a link saying "for complete app logs" and link to app logs on logs.cloud.gov

Notes: 
- Technical limitations of logs.cloud.gov
  - The authorization is very short, maybe ~20 minutes before you need to login again
  - Clicking a link while un-authed, you lose the context of the link after logging in. It makes the link useless.
- Devs will take the lead here and then will ask for design feedback

Related research issue: #713

Acceptance criteria: 
 - [x] Have a link saying "for complete app logs" linking to app logs on logs.cloud.gov
 - [x] Testing this link yields no significant errors or workflow delays

**Comment by suprenant** [comment]
Some of this will likely be informed by the App page audit @line47 worked on.

**Comment by adborden** [comment]
My understanding is that https://github.com/18F/cg-dashboard/issues/713 the historical usage/limits would be consumed for the sparkline. The activity log is the log lines/events from cloud.gov. We currently show events and errors in the activity log in the app panel, but there are many more informational log lines that we could show, or just link to logs.cloud.gov.

My opinion is that we either want to embed a visualization from logs.cloud.gov or just link to it. We won't be able to build anything as rich as logs.cloud.gov and there would be a lot of effort to handle the volume of logs that a user might want to see and the result would be something lesser than what logs.cloud.gov provides.

**Comment by adborden** [comment]
updated with some technical notes.

**Comment by suprenant** [comment]
Thanks, @adborden. I took a crack at acceptance criteria – please feel free to flesh out if you think something clearer would be better.

**Comment by adborden** [comment]
Here's an example that links to the App Overview dashboard with an app selected by name. We should swap out the org/space guids to be dynamic.

> https://logs.cloud.gov/app/kibana#/dashboard/App-Overview?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-12h,mode:quick,to:now))&_a=(filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:%5Blogs-app-%5DYYYY.MM.DD,key:'@source.app.name',negate:!f,value:federalist),query:(match:('@source.app.name':(query:federalist,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:%5Blogs-app-%5DYYYY.MM.DD,key:'@source.org.id',negate:!f,value:ec667d26-3a64-4c91-97c2-766cdaa040d3),query:(match:('@source.org.id':(query:ec667d26-3a64-4c91-97c2-766cdaa040d3,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:%5Blogs-app-%5DYYYY.MM.DD,key:'@source.space.id',negate:!f,value:'747f486d-9a9f-491a-8dcc-47cc973593bf'),query:(match:('@source.space.id':(query:'747f486d-9a9f-491a-8dcc-47cc973593bf',type:phrase))))),options:(darkTheme:!f),panels:!((col:1,id:App-logs-by-type,panelIndex:1,row:1,size_x:9,size_y:2,type:visualization),(col:10,id:App-names,panelIndex:2,row:1,size_x:3,size_y:2,type:visualization),(col:1,columns:!('@level','@source.name','@source.space.name','@source.app.name','@message'),id:app-all,panelIndex:3,row:3,size_x:12,size_y:7,sort:!('@timestamp',desc),type:search)),query:(query_string:(analyze_wildcard:!t,query:'*')),title:'App%20-%20Overview',uiState:(P-1:(spy:(mode:(fill:!f,name:!n))),P-2:(spy:(mode:(fill:!f,name:!n)))))

**Comment by adborden** [comment]
@suprenant looks great.

**Comment by msecret** [comment]
We actually already had code that did this btw, having a hard time finding it

**Comment by adborden** [comment]
:+1:
