### ISSUE TITLE
Implement marketplace in space page

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#780]
In order for a manager to add a service to a space, there should be a service marketplace on the space page.

Acceptance criteria:
- [x] The marketplace link in the sidenav should be removed.
- [ ] There should be a "Services" named panel on the space page with list of services to make service instances out of.
- [ ] The flow to create a new service instance should work the same as on the current marketplace page.

Need to explore what happens when user clicks button to add something from the marketplace

Research for reference: https://github.com/18F/cg-dashboard/issues/704

**Comment by msecret** [comment]
https://gsa.invisionapp.com/d/main/#/console/8652272/207322417/preview

**Comment by suprenant** [comment]
Asking Marco to groom for sprint planning this week.

**Comment by adborden** [comment]
:+1:
