### ISSUE TITLE
Remove some top nav links change log out to be a button

### ISSUE THREAD

**Issue by line47** [18F/cg-dashboard#782]
- [x] Update log out link style in header style to be a button
- [x] Remove About and Contact links from the top navigation

### Header Sketch
<img width="1052" alt="screen shot 2016-12-02 at 9 55 06 am" src="https://cloud.githubusercontent.com/assets/1449852/20838231/a082897e-b875-11e6-83ad-0aa94668d2c0.png">

### App Page Panels Sketch 
<img width="1021" alt="screen shot 2016-12-02 at 9 55 17 am" src="https://cloud.githubusercontent.com/assets/1449852/20838233/a4387a6a-b875-11e6-8d4c-5186ef2009cb.png">

### Acceptance criteria: 
- [ ] Experience matches items from list above

**Comment by line47** [comment]
I'd like to get some help with implementing this search portion. @msecret or @adborden If you could find some time to pair that would be awesome!

**Comment by line47** [comment]
I pulled the search portion out of this as it's captured in https://github.com/18F/cg-dashboard/issues/648. This will allow me to complete this issue.

**Comment by line47** [comment]
I need some help from @msecret or @adborden on adding HREF functionality to the Action component to support the login/log out buttons

**Comment by line47** [comment]
@adborden helped me out with adding button styling functionality to the the link action!

**Comment by suprenant** [comment]
@line47 this generally looks good, but I'm not sure the vertical alignment is where we want it to be. Please see screenshot – can you review?

![screen shot 2016-12-21 at 4 17 06 pm](https://cloud.githubusercontent.com/assets/1452369/21408164/0e8cf594-c799-11e6-9d12-2a58fcc27837.png)

**Comment by line47** [comment]
I am seeing the same thing as your screenshot on staging. The alignment of the button was merged here: https://github.com/18F/cg-style/pull/221 not sure why we are not seeing it on staging. @msecret can you take a look?

**Comment by msecret** [comment]
Because we haven't release cg-style since then, https://github.com/18F/cg-style/releases/tag/2.3.0

**Comment by line47** [comment]
Thanks for the clarification @msecret!

**Comment by adborden** [comment]
Hmm, yeah, this makes acceptance hard. Style changes don't get released with the PR. @suprenant @line47 you might want to do a screen share and do what I call "local acceptance" rather than wait for cg-style to get released, idk.

**Comment by line47** [comment]
Thanks @adborden! @suprenant let's screen share on this soon.

**Comment by suprenant** [comment]
Reviewed with @line47, this looks good, closing up this issue.
