### ISSUE TITLE
App page updates to recent activity styling and number of items

### ISSUE THREAD

**Issue by line47** [18F/cg-dashboard#783]
- [x] Add show more activity button to the bottom of the recent activity list.
** I would like to propose that instead of a button we have a link that takes the user out to logs.cloud.gov. @thisisdano @vz3 thoughts?
- [x] Determine number of recent activity items to show. 
** I would propose we show the most recent 10 and cap it there.
- [x] Update font for non-server messages to 18Franklin
- [x] Update left-side vertical pill indicator to round top and bottom. Take a look at [this doc page](https://cloud.gov/docs/getting-started/accounts/#managing-mfa-totp-with-authentication-applications) for the current pattern example.
- [x] Make date/time text red when encountering a critical issue (crashed/stopped).
- [x] Adjust font weights for panel
- [x] Add link to logs.cloud.gov for recent activity

### Recent Activity Sketch

<img width="1019" alt="screen shot 2016-12-02 at 11 26 33 am" src="https://cloud.githubusercontent.com/assets/1449852/20841592/5574d9fc-b882-11e6-9508-7d85baeacf93.png">

Acceptance criteria: 
- [x] The user experience reflects the above changes
- [x] Activity log shows at most 24 items

**Comment by suprenant** [comment]
@line47 looks good

**Comment by line47** [comment]
I'm unsure how to get a critical issue to appear in the activity log so I can style appropriately. @msecret @adborden Is there some test data I could look at? I didn't see any in the test data.

**Comment by msecret** [comment]
@line47 add the following after line 47 of `stores/activity_store.js`:

https://gist.github.com/msecret/d11abddde5908f1fc685e46f6609806e

And then visit testapp01 application in your testSpace01 space, which is in your cf-deck-testing organization

**Comment by line47** [comment]
@msecret when I add that block of code after line 47 I get the issue `Parsing error 'this' can not be used as shorthand property.`.

I do show that testapp01 in testSpace01 and cf-deck-testing org is stopped.
The activity log is not showing any items.

**Comment by line47** [comment]
I'm going to push the users over to logs.cloud.gov for this release and let the user log in. 
After talking with @adborden it seems there may currently be issue with maintaining the user logged in state from cloud.gov to logs.cloud.gov

**Comment by vz3** [comment]
@line47 I'm guessing @msecret meant line 96 per the code comment and just got mixed up by your handle :)

**Comment by line47** [comment]
Rad! Thanks @vz3, that worked!

**Comment by line47** [comment]
@adborden or @msecret I'd like to get a few minutes with either of you to figure out how to limit the recent activity on the app page to the most recent 10 items. That's the last item on this issue to get done and I'm unsure how to accomplish it.

**Comment by adborden** [comment]
@line47 happy to help out here. My _hunch_ is that it's really straight forward. [Here](https://github.com/18F/cg-dashboard/blob/master/static_src/components/activity_log.jsx#L10) is where the activity comes from, so potentially it's as simple as adding a `slice` to limit the number of items.

```javascript
let activity = // ...
const itemLimit = Math.min(activity.length, 10);
activity = activity.slice(0, itemLimit);
```

**Comment by line47** [comment]
Thanks @adborden I've got it figured in https://github.com/18F/cg-dashboard/pull/806

**Comment by suprenant** [comment]
Noting we want to change from 10 to 24 recent items in the list here.
