### ISSUE TITLE
Styling updates for routes

### ISSUE THREAD

**Issue by line47** [18F/cg-dashboard#784]
- [x] Change Bound Routes unbind button to a link
- [x] When editing or adding a route update route preview URL to align left with the rest of the form
- [x] Set routes panel width to 6 column
- [x] Add horizontal lines between routes
- [x] Add a link to the environment. For example, staging, to the right of the services heading 
- [x] Adjust font weights for panel header to make lighter

### Routes Sketch

<img width="497" alt="screen shot 2016-12-02 at 11 41 10 am" src="https://cloud.githubusercontent.com/assets/1449852/20842096/454b6e5e-b884-11e6-93a8-9db4374f64eb.png">

#### Routes Adding/Editing Sketch

<img width="515" alt="screen shot 2016-12-02 at 11 42 24 am" src="https://cloud.githubusercontent.com/assets/1449852/20842149/7cf5901e-b884-11e6-8f8e-6e4c8e05005b.png">

Acceptance criteria:
- [x] The user experience reflects the above changes

**Comment by line47** [comment]
@suprenant review when you can

**Comment by suprenant** [comment]
Thinking this could take some React work.

**Comment by msecret** [comment]
I had to back out the changes to make this panel half sized because of problems with the grid size on the app page. I think we'll need to complete that after we remove the sidebar. Maybe we can make a new issue for it?

**Comment by line47** [comment]
We could add adjusting the widths of services and routes panels to the panel background issue? https://github.com/18F/cg-dashboard/issues/819

**Comment by adborden** [comment]
The user experience reflects the above changes.
