### ISSUE TITLE
Styling updates to services

### ISSUE THREAD

**Issue by line47** [18F/cg-dashboard#785]
- [x] Update text for the add a service button to “Add a new service from the marketplace”
- [x] Right align cost of the service
- [x] Add horizontal lines between services
- [x] Add a link to the environment. For example, staging, to the right of the services heading
- [x] When unbind is clicked change to a button "Yes, unbind" with the cancel button just like the unbinding of a route pattern.
- [x] Update text when a service is unbound to "Unbind SERVICE NAME service from this app?"
- [x] Adjust font weights for panel. Header should be lighter weight. Service name, status and actions should be heavier.

### Services Sketch

<img width="496" alt="screen shot 2016-12-02 at 12 04 08 pm" src="https://cloud.githubusercontent.com/assets/1449852/20842973/8a8d58b2-b887-11e6-925e-ef262d09d90d.png">

Acceptance criteria:
 - [x] The user experience reflects the above changes

**Comment by line47** [comment]
@suprenant take a look when you can

**Comment by suprenant** [comment]
Noting that we can't move anything to two-column design until sidebar is removed.

**Comment by adborden** [comment]
The user experience reflects the above changes.
