### ISSUE TITLE
Styling updates to usage and allocation

### ISSUE THREAD

**Issue by line47** [18F/cg-dashboard#786]
- [x] Change “App scale 2x” text to “Instances” and change explanatory text to “Instances applies to memory and disk”
- [x] Update left-side vertical pill indicator to round top and bottom. Take a look at [this doc page](https://cloud.gov/docs/getting-started/accounts/#managing-mfa-totp-with-authentication-applications) for the current pattern example.
- [x] Add "View more data for usage and stats at kibana.cloud.gov" link (This item needs some discussion @thisisdano @vz3)
- [x] Adjust font weights for panel. Header should be lighter weight. Body should be normal weight.

### Usage And Allocation Sketch

<img width="1003" alt="screen shot 2016-12-02 at 12 21 18 pm" src="https://cloud.githubusercontent.com/assets/1449852/20844109/4209f14a-b88c-11e6-886f-a9bf699eb891.png">

Acceptance criteria:
 - [ ] The user experience reflects the above changes

**Comment by line47** [comment]
@suprenant take a look

**Comment by suprenant** [comment]
@line47 generally looks good. As discussed, I paired it with an epic and also added some bare-bones acceptance criteria.

**Comment by suprenant** [comment]
Holding on this until sidebar is removed could be useful here.

**Comment by line47** [comment]
Also put some work into setting up the status pill as seen here:  https://github.com/18F/cg-style/issues/220

**Comment by suprenant** [comment]
@line47 can you please review the "Instance applies to memory and disk" copy in the attached to confirm that it's the desired presentation?

Also, I'm unable to view the left-side vertical pill indicator change, so can you also please give me a screenshot of that for acceptance?

![screen shot 2016-12-28 at 2 08 02 pm](https://cloud.githubusercontent.com/assets/1452369/21530550/2d193cd4-cd07-11e6-9e27-eb5c7ad441f7.png)

**Comment by line47** [comment]
Here is a screenshot of the status pills from dashboard-staging:
![screen shot 2016-12-29 at 10 03 58 am](https://cloud.githubusercontent.com/assets/1449852/21546656/3861553e-cdae-11e6-9587-747b260e3c98.png)

Here is a screenshot of the entire usage and allocation panel from the most recent master where the "Instance applies to memory and disk" is getting the proper text sizing using the class `subtext`. Notice the status pills here as well.

![screen shot 2016-12-29 at 10 37 05 am](https://cloud.githubusercontent.com/assets/1449852/21547256/e12dfb28-cdb2-11e6-912a-cf8515cb6df6.png)

**Comment by suprenant** [comment]
OK, thanks @line47 ! Looks good, closing this up
