### ISSUE TITLE
Dashboard should be generic

### ISSUE THREAD

**Issue by jmcarp** [18F/cg-dashboard#790]
In principle, nothing about this app should be specific to cloud.gov--so this should be a cloud foundry dashboard, not a cloud.gov dashboard. Toward that goal, we should remove any hard-coded references to cloud.gov here, either linking to cloud foundry materials or allowing operators to override text, logos, etc. I'm glad to see that @tessereth has started this work in https://github.com/AusDTO/cg-dashboard/pull/2.

* [ ] Link to cloud foundry docs instead of docs.cloud.gov
* [ ] Allow operators to override templates
* [ ] Rename project to cf-dashboard

**Comment by msecret** [comment]
Will discuss this with Bret based on Pivotal discussion of making dashboard more transparent with CF.

**Comment by jonathaningram** [comment]
I don't mean to bring up old issues, but I was looking through what issues are still around and noticed this. As you know, lots of the work cloud.gov.au is doing is about making the project more generic and so pretty soon most of this ticket will be done anyway.

I just wanted to chime in and briefly comment on the task "Rename project to cf-dashboard".

At this stage cloud.gov.au is calling this "console", not "dashboard". It matches console.cloud.google.com and console.aws.amazon.com. For me, this is a console not a dashboard. For me a dashboard is a page showing charts and stats or the home page of most web applications. I don't want to bikeshed (really, dashboard is fine) but if the project does undergo a rename, perhaps consider `cf-console`.
