### ISSUE TITLE
Address misc. accessibility issues

### ISSUE THREAD

**Issue by tessereth** [18F/cg-dashboard#791]
So I've been having a look at the accessibility of the dashboard. I found a few things that will be picked up by automated testing and so will presumably be covered by https://github.com/18F/cg-dashboard/issues/787. But I've found a few others that won't and some I'm not sure about so I thought I'd list them here.

I wasn't sure whether to make this one issue or a bunch of them. If you'd like me to split it up, I'm more than happy to do that. Also, given I don't know how familiar you are with accessibility things, I've erred on the side of more information than less. Apologies if I'm telling you things you already know or are already planning to/have fixed.

## Missing ARIA live regions

Many assistive technologies are based on the DOM. If the DOM is being updated dynamically, you need to specify `aria-live` attributes on any sections that might be changing. This ensures, for instance, that screen reader users are notified of changes.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions#document-main

## Same title and H1 for every page

On the one hand, this is a single page app. On the other hand, there are different logical pages and they even have different routes. I think it would make a lot of sense for the title and h1 to reflect the route. It would also make it easier for users of assistive technologies to determine where they are.

## Tables are hard, nested tables are worse

Tables are generally tricky for a screen reader user to navigate. I imagine the nested tables on the marketplace page would be even harder. I imagine they're hard to use on mobile as well.

## Buttons should be buttons and links should be links

This one's a bit more vague but I've seen a few questionable instances. The `Create service instance` buttons on the marketplace page should possibly be links because it takes you to a new piece of content. The links in the navbar with `href="#"` should possibly be buttons because they are show/hiding the rest of the navbar.

## Link and button text should be meaningful outside of context

The marketplace page has many buttons called `Create service instance` which all to different things. The button text should describe which instance and plan is being created.

## The semantic name should match the visual name

The marketplace `create service instance` buttons have `aria-label="create"`. This means a voice recognition user who tried to click the button by saying "create service instance" would not be able to activate the button. Removing the `aria-label` should make it default to the button text.

## The three level nested list in the navbar is confusing

A screen reader reports the nesting level and the start and end of each list. It makes it somewhat confusing to understand the navbar. Semantically, the navbar is currently:

* Overview
* ORGANIZATIONS (not a link)
* org1
    * org1 overview
        * space1
        * space2
    * org1 marketplace

There's probably a simpler, flatter way of representing this information.

**Comment by suprenant** [comment]
Thanks @tessereth! This is very helpful. And this one issue is fine for now – we can split is up as needed as we take on any of the work here.
