### ISSUE TITLE
Conduct usablity testing on live site

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#794]
What we're after: 
 - To help make sure the end-to-end experience works well for new users, we want to conduct research with users.

Related discussion:
https://gsa-tts.slack.com/archives/cloud-gov-skyporter/p1480717896004543

Notes: 
Start with home page, log in, walk through typical actions
Possibly dependent on #454 (Alternative might be to create a test account)

Acceptance criteria: 
 - [x] Candidates are identified
 - [ ] Research script is created
 - [ ] Research sessions are conducted
 - [ ] Findings are summarized, available in Google Docs and/or the wiki, and shared with the team

**Comment by suprenant** [comment]
Noting that we originally thought this would be useful to conduct by our next mid-sprint check-in (Monday, Dec 12th).

**Comment by suprenant** [comment]
We have a session booked for today and are working to schedule others.

**Comment by suprenant** [comment]
@vz3 @thisisdano where are our notes from any sessions we've done so far here?

**Comment by vz3** [comment]
[Session 1](https://docs.google.com/document/d/1d66nxY3dAwWihZDOY2f4kniLRdjr0QtrwRbipxp7EiU/edit#heading=h.mqrypcji68j)
[Session 2](https://docs.google.com/document/d/1P8s8CsSuQjhTQTcb-stTsViej73c390RM0xvSwapPVo/edit)
[Session 3](https://docs.google.com/a/gsa.gov/document/d/1P8s8CsSuQjhTQTcb-stTsViej73c390RM0xvSwapPVo/edit?usp=sharing)

**Comment by suprenant** [comment]
Noting that we want to do this on the live site.

**Comment by suprenant** [comment]
To do this, we want the breadcrumb in and good test data to use.

**Comment by suprenant** [comment]
...and possibly also including expressive empty states before testing.
