### ISSUE TITLE
Clean up sidebar nav for docs

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#796]
It's sometimes the case in the sidebar that that proper view is not highlighted. We want to fix this so users can easily navigate docs to find what they are looking for.

Implementation notes:
 - Find example of exhibition of each behavior
 - Determine and document priority/steps to fix
 - Fix accordingly 

Acceptance criteria:
- [ ] Docs pages should have proper highlight of current section
- [ ] Every section that is a parent section should have an arrow
- [ ] Arrow switching of open-close states behavior should be consistent (arrow indicating that parent session is open/closed does not currently consistently happen)

**Comment by suprenant** [comment]
Slated for Sprint 8.5. Thought we had a similar issue on the board but can't find it at the moment.

**Comment by thisisdano** [comment]
- proper highlight of current section
- proper arrow switching of open-close states
- arrows for all sections with subsections

**Comment by suprenant** [comment]
Issue moved to [18F/cg-site #643](https://github.com/18F/cg-site/issues/643) via [**ZenHub**](https://www.zenhub.com/)
