### ISSUE TITLE
Build out service instances (space page)

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#798]
Related (we're tackling this first): https://github.com/18F/cg-dashboard/issues/709

**Comment by msecret** [comment]
Building the new Service instances and User management UI should be separate tasks, or even separate epics from the space epic.

**Comment by suprenant** [comment]
@msecret OK – split this out and put User management here. Feel free to adjust further: https://github.com/18F/cg-dashboard/issues/803
