### ISSUE TITLE
Organization usage and quota numbers

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#800]
In order for a manager to understand the resource usage of a whole org, there should be a set of numbers on the organization overview page.

Acceptance criteria:
- [ ] There should be the memory usage and memory limit (without cost information).
- [ ] There should be disk usage and disk limit (without cost information).
- [ ] There should be services used with service quota if there is one (without cost information).
- [ ] All usage stats should show current warning/status by displaying the standard green/yellow/red bar on the side and have the amount available numbers colored by the status. This is similar to the app page usage stats.

This story is for just the numbers portion of the UI, which is on the left side. For the graphs on the right side, see [823](https://github.com/18F/cg-dashboard/issues/823).

**Comment by suprenant** [comment]
Asking Marco to groom for sprint planning this week.

**Comment by msecret** [comment]
@suprenant s notes:


Design issue: https://github.com/18F/cg-dashboard/issues/735

(similar to quota/application limit panel from app page)
 - View/modify quota from the level
 - Can org quotas be changed right now (need to find out about that)
 - Current design shows future state when we’re not billed on quota

Notes: 
 - Might want to break down implementation more
 - Highly related to org page
 - Org and space are two distinct pieces of work - so there will be other issues/follow-on work for the space page
