### ISSUE TITLE
Implement org view

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#801]
In order for a manager to see all spaces and apps as part of an org, there should be a UI for spaces and apps.

Acceptance criteria:
- [x] The app icons should be color-coded based on their state.
- [x] App memory usage and limit should be displayed.
- [x] If an app has crashed, there should be a color-coded crashed label.
- [x] There should be count with status and icon UIs for spaces, apps and services (only services is new, other ones exist already).

**Any code built should leverage existing components on space quick look and app list!**

Things that **will not be done** as part of this story:
- Displaying services [827](https://github.com/18F/cg-dashboard/issues/827)
- Displaying any sort of cost information.
- Multi-tiered status bars, [766](https://github.com/18F/cg-dashboard/issues/766)
- Add a new space, [742](https://github.com/18F/cg-dashboard/issues/741)
- Quota and usage panel, [800](https://github.com/18F/cg-dashboard/issues/800)

**Comment by vz3** [comment]
Design:
https://gsa.invisionapp.com/share/838UY596S#/207322451_Org

**Comment by suprenant** [comment]
Asking Marco to groom for sprint planning this week.

**Comment by msecret** [comment]
@suprenant previous notes I moved:

This will include: 
 - Display spaces (at org view)
 - Display apps (at org view)
 - Show all services associated with a space

Design issue: https://github.com/18F/cg-dashboard/issues/735

(shows hierarchy of view)
 - Showing the contents of that view
 - Read-only view of what that subsection is consuming (this could be first pass)

Notes: 
 - Previously discussed this as breaking down overview/contents panels for org page
 - Might want to break down implementation more
 - Highly related to org page
 - Org and space are two distinct pieces of work - so there will be other issues/follow-on work for the space page

Acceptance criteria:
 - [ ]

**Comment by suprenant** [comment]
This is looking good. @adborden, when you get a chance, could you please review the crashed app criterion for acceptance?

**Comment by adborden** [comment]
:+1: I think this story looks good, but we've got a bug for the crashed app to follow up on https://github.com/18F/cg-dashboard/issues/860
