### ISSUE TITLE
Discuss dashboard top nav at program level

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#811]
What we're after:
 - Dashboard team would like more consistency between sitewide nav and dashboard nav. They don't need to be identical, but some elements (e.g. login/log out, header) should be consistent.

Notes:
 - cg-site and dashboard header has some inconsistencies
 - We already have some design around this

Design issue for reference: https://github.com/18F/cg-dashboard/issues/712

In addition to elements in the design issue, let's make sure this includes: 
 - Change "Dashboard" to "Login"
 - Address consistency of nav button placement

Acceptance criteria:
 - [ ] Set up meeting with interested program-level folks
 - [ ] There are issues in the Github repos for discrete next steps

**Comment by vz3** [comment]
I propose that we change "Dashboard" to "Login" and change it to a button style for consistency with the overall Dashboard experience. Receptive to push back.

**Comment by thisisdano** [comment]
^^^ Yes 100%

Login/Logout as action rather than Dashboard as destination

**Comment by vz3** [comment]
Dan's thinking on this is here:
https://github.com/18F/cg-dashboard/issues/712
