### ISSUE TITLE
Remove sidebar from dashboard

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#818]
What we're after: 
We want to provide the user a better way to navigate the experience

Notes: 
 - Remove sidebar once current functionality is replicated in other areas:
https://github.com/18F/cg-dashboard/issues/813 (breadcrumb implementation)
 - All views designed (org, space, app) enough so they have a contents panel at the top of the page
 - (12/12) by next sprint: overview and space should be in pretty good shape. If we can do the org view, maybe then we kill the sidebar

Need to double-check that it doesn't break anything

Acceptance criteria:
 - [x] Sidebar is not displayed
 - [x] Users can still navigate entirety of experience using new navigation scheme
 - [x] No pages are broken by the change in the horizontal width

**Comment by suprenant** [comment]
Note that we need to do this after the marketplace.

**Comment by suprenant** [comment]
Discussed a bit during standup today:
 - Should we still be doing this given where we are in the IP?
 - Thinking we might want to keep it, replace simple header treatment to display (if not breadcrumb)

**Comment by msecret** [comment]
Is this done?

**Comment by adborden** [comment]
LGTM
