### ISSUE TITLE
Implement background color for panels

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#819]
Colors should be (panels: white, page background: grey)

![screen shot 2016-12-13 at 12 44 43 pm](https://cloud.githubusercontent.com/assets/1452369/21153916/21777732-c132-11e6-936f-bacea95ff27f.png)

Acceptance criteria: 
 - [x] Production matches design (background color gaps between panels) across all dashboard sections

**Comment by thisisdano** [comment]
Looks like this is done — just needs the main content panel to go clear to see the white panels.

**Comment by adborden** [comment]
LGTM
