### ISSUE TITLE
Analyze Enable code pushes via web UI

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#821]
What we're after: develop an understanding of this functionality so we can scope and design possible solutions that may be implemented in the next PI. 

Epic with preliminary details:
 - https://github.com/18F/cg-product/issues/563

Acceptance criteria: 
 - [ ] Summary notes/recommendations are available
 - [ ] Github issue is created for followup work, including design

**Comment by suprenant** [comment]
Noting that this may go back from PI9 to PI10 unless we learn that this is critical for new customers.

**Comment by jcscottiii** [comment]
we have a card for this in favro
