### ISSUE TITLE
Analyze One-click app deploys

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#822]
What we're after: develop an understanding of this functionality so we can scope and design possible solutions that may be implemented in the next PI. 

Epic with preliminary details:
 - https://github.com/18F/cg-product/issues/564

Acceptance criteria: 
 - [ ] Summary notes/recommendations are available
 - [ ] Github issue is created for followup work, including design

**Comment by suprenant** [comment]
Noting that this may go back from PI9 to PI10 unless we find time to prioritize user research during PI8 (which we're not currently expecting).

**Comment by jcscottiii** [comment]
we have a card for this in favro
