### ISSUE TITLE
Display all space services on org page

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#827]
In order for a user to see all services on an org, there should be a view of them on the org page.

Design: https://github.com/18F/cg-dashboard/issues/735

**Comment by msecret** [comment]
This may need more design based on this comment: https://github.com/18F/cg-dashboard/issues/735#issuecomment-266555350

**Comment by suprenant** [comment]
Discussing this with Marco now – in some designs, we're showing services and apps together, but the comment here indicates that we're showing them separately. So, we should talk and sort this out.

**Comment by thisisdano** [comment]
Just show them together for now. (First apps, then services.) We will work on differentiation shortly. Possibly adding a subhed between the apps and services. But I don't think it should block present development.

**Comment by msecret** [comment]
If differentiation is being worked on, I'd much rather wait for that because showing them together will take extra engineering effort that would all be lost when we separate them.
