### ISSUE TITLE
Refactor panel component to simplify

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#833]
The panel.scss file in cg-style and the panels in the react codebase are too complicated. Refactoring should:

- reduce file in panel.scss
- combine patterns into as few separate things as possible

Notes from team discussion:
 - Panels are doing several different (and really, too many) things: padding related to the grid, a component with title/body/rows, has white background
 - We should split features into modifier classes or separate things
 - Card vs. panel
 -- Card lives inside a panel
 -- Panel is a white rectangle with some padding with spot for things at top and bottom
 -- Prefer that the panel is lightweight and content agnostic
 -- At bottom, panel elements not regularized
 -- At top, only two things can happen

**Comment by adborden** [comment]
cc @line47

**Comment by suprenant** [comment]
Thinking that this work very well may happen organically through other issues we currently are working on which may obviate the need for this issue.

**Comment by adborden** [comment]
Pulling this out of icebox since we said we would tackle this early in the PI, probably for sprint 2.
