### ISSUE TITLE
Refactor action component so it can take an href

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#835]
The `Action` component is really useful for styling purposes, so it would help greatly if it could just be a link with an href as well.

**Comment by adborden** [comment]
@line47 is currently working on this.

**Comment by line47** [comment]
This is accounted for in PR https://github.com/18F/cg-dashboard/pull/843

**Comment by suprenant** [comment]
@line47 can you please advise on the AC here so we can confirm whether or not this is done? LMK if you'd like to pair to review.

**Comment by line47** [comment]
This was used so we could add an HREF 

Acceptance Criteria

- [ ] Can add an HREF to an `<action>` component. An example of this would be seen in the log out button of the top nav.

**Comment by msecret** [comment]
THe AC's here are in the code, they're not at all visible to a user of the dashboard, so a developer has to accept them

**Comment by adborden** [comment]
Writing AC for tech debt can be tricky, but what @line47 laid out is done in my book.
