### ISSUE TITLE
App restarting state breaks when reloading page

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#839]
Currently, on app restart, we manually set our own "RESTARTING" state as the `state` on the app. This is bad because if the user refreshes the page during restart, they'll lose this state and the app will look like it's just down.

Instead, we should figure out if the app is restarting. It is when the `state` is `"STARTED"` and the amount of `instances` is 0.

Notes:
 - Would need to write some heuristics

Acceptance criteria: 
 - [ ] If user clicks restart on app and then refreshes page, app should be displayed in a restarting state

**Comment by suprenant** [comment]
Noting that this is related to https://github.com/18F/cg-dashboard/issues/860, which @adborden is currently working on. This issue feels like more of an edge case, so we may or may not pick this up in this sprint.
