### ISSUE TITLE
Replicate Sketch patterns in Pattern Library

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#845]
How can we move out of Sketch and into the live code that makes up the production app?

The Sketch file has a robust collection of patterns that describe a wide variety of current and upcoming functionality. Translating these patterns into solid, reliable code will make current and future development simpler and more consistent with our aesthetic standards and design principles.

Implementation notes:
- [ ] Convert Sketch patterns into live code
- [ ] Develop reusable patterns that make it simple to communicate our design intention for current and future implementation
- [ ] Strengthen and refine existing patterns
- [ ] Communicate these patterns and their intended usage in the pattern library

@thisisdano has done some of this work, but there are some key pieces — especially around user management and the marketplace — that exist only in Sketch.

Acceptance criteria:
Patterns prototyped in the pattern library for the following patterns (examples of these will be posted below): 
- [ ] org user management
- [ ] space user management
- [ ] marketplace display
- [ ] add service flow
- [ ] organization overview
- [ ] organization quota/usage
- [ ] site top nav
- [ ] footer
- [ ] notification bar
- [ ] empty state container

These prototypes should:
- [ ] match styling in Sketch
- [ ] make use of existing components if possible
- [ ] suggest new components
- [ ] include examples of all variants
- [ ] be organized in the `Prototypes` section of the PL, tagged as `WIP`
- [ ] be styled with utility classes and nonsemantic `div`s for portability

**Comment by suprenant** [comment]
@thisisdano and me to groom further ASAP

**Comment by suprenant** [comment]
@thisisdano to groom further, at least in broad strokes for now

**Comment by thisisdano** [comment]
How can we move out of Sketch and into the live code that makes up the production app?

The Sketch file has a robust collection of patterns that describe a wide variety of current and upcoming functionality. Translating these patterns into solid, reliable code will make current and future development simpler and more consistent with our aesthetic standards and design principles.

- [ ] Convert Sketch patterns into live code
- [ ] Develop reusable patterns that make it simple to communicate our design intention for current and future implementation
- [ ] Strengthen and refine existing patterns
- [ ] Communicate these patterns and their intended usage in the pattern library

I've already done some of this work, but there are some key pieces — especially around user management and the marketplace — that exist only in Sketch.

**Comment by suprenant** [comment]
As mentioned to @thisisdano, we need to flesh out the acceptance criteria here ASAP before we go much further here. Will set up a meeting for us to sync on this and also talk about our broader plans for the pattern library.

**Comment by suprenant** [comment]
@thisisdano AC here is looking good, thanks

**Comment by adborden** [comment]
Invision https://gsa.invisionapp.com/share/8X8RHAOKS#/screens
Sketch https://github.com/18F/cg-design/tree/master/Sketch
