### ISSUE TITLE
Styling refinements to overview org card

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#846]
What we're after: 
Update the styling on the live page to match the sizing, alignments, and font styling of the InVision prototype.

InVision prototype:
https://gsa.invisionapp.com/share/838UY596S#/207297501_Overview

Some changes:
 - Decrease whitespace below status bars
 - Increase font weight of status
 - Type treatment of space prefix before an app

Acceptance criteria:
 - [x] Overview org card on production matches the InVision prototype (see additional notes below)

**Comment by suprenant** [comment]
@thisisdano we're looking for more detail here. Would you either like to implement any changes here yourself, pair with a dev, or provide an annotated screenshot of exact changes we're after here?

**Comment by thisisdano** [comment]
So here's a diff-y kind of image. A bit hard to read, but as implemented (gray) overlaid with proposed changes:

![overview-org-cards](https://cloud.githubusercontent.com/assets/11464021/21280828/519b04fc-c39d-11e6-8be3-218d6ccc1c39.png)

There are a few things going on here that I'd like to adjust, not limited to:

- height of card
- alignment inside of card
- size of icons
- size of status indicators
- alignment within status indicators
- font size/weight in org title
- font size/weight in org contents
- indent in org contents
- alignment in org content
- height of content rows
- color of content rows

And some html structural things that should make these components more interoperable with other overview panels, and panels of all sorts. (So they work properly, have correct size, alignment, fonts, etc across all panels.)

I have actually made these changes to the code in the PL (they're live code and not static Sketch) and it's a matter of transferring those changes to the production templates.

In general, there are many small details, both in the way it looks and in the way it's built that I feel could be improved. I'm working with @line47 to do this now. Finishing this and getting all the new pattern stuff up is my first priority rn.

**Comment by line47** [comment]
I think I need to hold off on this until after the pattern library PR is merged. https://github.com/18F/cg-style/pull/225

**Comment by thisisdano** [comment]
Fixed with these two PRs:
https://github.com/18F/cg-dashboard/issues/846
https://github.com/18F/cg-dashboard/pull/894

**Comment by adborden** [comment]
Looks like the invision
