### ISSUE TITLE
Space overview page shows crashed app as ok

### ISSUE THREAD

**Issue by adborden** [18F/cg-dashboard#860]
I created `adborden-node-crashed` which never opens a port for listening so the health check fails and CF reports the app as crashed. You can see on the Space Overview in the dashboard, `adborden-node-crashed` shows up as green.

This is in the [cf-deck-testing/dev](https://dashboard-staging.apps.cloud.gov/#/org/48b3f8a1-ffe7-4aa8-8e85-94768d6bd250/spaces/82af0edb-8540-4064-82f2-d74df612b794) org/space.

![screenshot from 2016-12-22 14-13-57](https://cloud.githubusercontent.com/assets/509703/21442163/fd93469a-c850-11e6-90eb-b521492a4ca1.png)
![screenshot from 2016-12-22 14-12-53](https://cloud.githubusercontent.com/assets/509703/21442167/02480cac-c851-11e6-9685-112c56205ad9.png)

Notes:
 - We should only say okay if it's fully okay

**Comment by msecret** [comment]
@adborden do you know what `status` show up? In that screenshot, it looks like CF thinks the app is started, not crashed.

**Comment by adborden** [comment]
The app state is "STARTED". 

fwiw, the cf cli uses the condition [`runnning_instances == 0 && state !== STOPPED`](https://github.com/cloudfoundry/cli/blob/ffee70cca68ab15df71f48641f6fa3bb007c4a2b/cf/uihelpers/ui.go#L20) to determine crashed... although I assumed rebooting would also look like that.

Here's the full app summary https://gist.github.com/adborden/548719c53bfd26d4ce46e6bf11bd8f7a

**Comment by adborden** [comment]
Hmm, it looks like there are more state values on the app instance. Maybe we should include that information to determine if an app is crashing https://github.com/cloudfoundry/cli/blob/ffee70cca68ab15df71f48641f6fa3bb007c4a2b/cf/models/application.go#L76

It kind of makes sense because an app is really either starting, stopped, or in some state of running. YOu could have only one instance of several crashed, and that would mean the app is running, but not in a healthy state. cc @thisisdano

**Comment by adborden** [comment]
And here's the cli output for the app details, including the instances:
```
$ cf app adborden-node-crashed
Showing health and status for app adborden-node-crashed in org cf-deck-testing / space dev as aaron.borden@gsa.gov...
OK

requested state: started
instances: 0/1
usage: 64M x 1 instances
urls: adborden-node-crashed.apps.cloud.gov
last uploaded: Thu Dec 22 22:06:18 UTC 2016
stack: cflinuxfs2
buildpack: node.js 1.5.24

     state      since                    cpu    memory   disk     details
#0   crashing   2016-12-22 02:10:45 PM   0.0%   0 of 0   0 of 0
```

**Comment by suprenant** [comment]
@adborden can we please either pair or can you send a screenshot/steps to confirm that this one is resolved?

**Comment by suprenant** [comment]
Paired with @adborden to accept this – it looks good.
