### ISSUE TITLE
Domain dropdown list is empty in Routes panel on App page

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#864]
What we're after: display correct domains in route panel dropdown on app page for all users.

This should display organization-specific domains – at the very least, app.cloud.gov for GovCloud 
and apps.cloud.gov for East/West.

Notes: 
 - Not sure if this is specific to Andrew or other users, as well. We'll have to investigate and possibly outline steps to reproduce
 - Andrew reports this on both staging and production using the GovCloud environment
 - Andrew/Aaron to pair for 15-30 minutes to see what they can learn about this issue within Andrew's current config

Acceptance criteria:
 - [ ] Andrew/Aaron report pairing results to team 
AND/OR
 - [ ] Domain dropdown list displays correct domains

<img width="894" alt="screen shot 2016-12-23 at 5 39 54 pm" src="https://cloud.githubusercontent.com/assets/1452369/21506415/aeff3096-cc35-11e6-9a8f-8c6190ee03f2.png">
<img width="837" alt="screen shot 2016-12-23 at 5 34 00 pm" src="https://cloud.githubusercontent.com/assets/1452369/21506416/af000cc8-cc35-11e6-899b-36a4cef1675b.png">

**Comment by suprenant** [comment]
Scheduled time with @adborden for later today to screenshare/walkthrough.

**Comment by suprenant** [comment]
As an update, Aaron and I kicked at this for awhile this afternoon. He's going to try some other possible diagnostics, and we'll regroup as needed.

**Comment by suprenant** [comment]
The fix @adborden put in on demo appears to be working! 

https://dashboard-demo.app.cloud.gov

**Comment by adborden** [comment]
@suprenant has verified this.
