### ISSUE TITLE
Conduct usability testing with live instance

### ISSUE THREAD

**Issue by vz3** [18F/cg-dashboard#867]
Possible dependency #454 

We should conduct a round of usability testing with the live site. The outcome should be a set of recommendations to address usability issues, hopefully followed with prototype designs.

**Comment by suprenant** [comment]
@vz3 I think this is a dupe. If so, can you please consolidate? https://github.com/18F/cg-dashboard/issues/794

**Comment by vz3** [comment]
Closing as dupe
