### ISSUE TITLE
Double loading on Overview

### ISSUE THREAD

**Issue by adborden** [18F/cg-dashboard#869]
As the page is loading, we see the spinner, then the org quick look panels come in for a moment, then we get the loading again, and finally we get our loaded quick look panels.

![peek 2016-12-28 17-59](https://cloud.githubusercontent.com/assets/509703/21535294/b0ef4c86-cd27-11e6-9082-d813ac761593.gif)

**Comment by thisisdano** [comment]
Here's another view of this:

![loading](https://cloud.githubusercontent.com/assets/11464021/21777982/44d35956-d656-11e6-8c6d-dd524164a9ec.gif)

**Comment by adborden** [comment]
I'm still seeing this behavior, kicking it back to Ready.
