### ISSUE TITLE
Address loading indicator and page position issues w overview card open/close.

### ISSUE THREAD

**Issue by adborden** [18F/cg-dashboard#870]
What we're after: to avoid confusing users, overview cards should consistently display loading indicators when needed without visibly affecting the loading state of other cards.

Also, we are currently displaying too much space for the loader. The height of the expanded panel should be limited to only the size of the loader and then expand as needed to accommodate the additional panel contents.

Each quicklook panel goes into a loading state when one of them is expanded.
![peek 2016-12-28 18-22](https://cloud.githubusercontent.com/assets/509703/21535497/b8c0c78e-cd2a-11e6-99b3-1f03a616d482.gif)

Acceptance criteria:
 - [ ] Opening and closing a card does not result in visual changes in other cards
 - [ ] If the loader displays when a card is opened, the containing panel should be sized to only fit that loader

**Comment by vz3** [comment]
Some documentation from the design review:
If a card is open, opening a card below it results in the loader showing up in the top-most open card. 
Additionally, expanding lower card resets page position.

Recc: Keep existent objects in view when expanding new card. Don’t reset page position. Auto-expand cards if > 10 orgs.

**Comment by thisisdano** [comment]
The space issue is addressed here: https://github.com/18F/cg-style/pull/284

Plus, in addressing this issue I was able to clarify that an expand action in any card triggers a load in all open cards, as seen below: 

![loading](https://cloud.githubusercontent.com/assets/11464021/21767171/4fdf65f8-d627-11e6-841e-3f762b0c9a1b.gif)
