### ISSUE TITLE
Walkthrough app page to diagnose bugs

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#876]
To increase confidence in the app page, we want to review it as a squad to find and triage any bugs we may not currently be tracking.

Acceptance criteria:
 - [x] Squad meeting is scheduled to walk through app page together
 - [x] Notes from meeting are in Google Docs
 - [x] Relevant issues are filed in Github

**Comment by suprenant** [comment]
Squad meeting (with other cloud.gov folks welcome if interested/available) scheduled for Tuesday. This is on the cloud.gov calendar.

**Comment by adborden** [comment]
Two docs were created, issues for priority 3 and higher were created in Github.
https://docs.google.com/document/d/1Hx3QXfkmxdpX-rPxu3XNp2VRuGc8BaNryzshE43dPu0/edit
https://docs.google.com/document/d/1qSDrAEQ3yIioiWViYuo0hEnt7Jkux5EJaqVXqdjdKgo/edit#heading=h.8323d8i28e8d
