### ISSUE TITLE
Create service instance action wraps poorly

### ISSUE THREAD

**Issue by adborden** [18F/cg-dashboard#882]
On the space page, the action says "Create service instance" which wraps and gets cutoff

![screenshot from 2016-12-29 11-56-42](https://cloud.githubusercontent.com/assets/509703/21553608/0b697be6-cdbe-11e6-8cb0-f2245676e92b.png)

**Comment by msecret** [comment]
Moving this issue to https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-2993 as it's too small by itself.
