### ISSUE TITLE
Moving pattern library from WIP state to ready state

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#887]
What we're after: if we have WIP components that exist in pattern library and production...this can be confusing. We want to make sure the pattern library works with production styles and matches what we have in the dashboard to make sure this process is working, solid, and makes sense.

Notes:
 - Maybe not do all of the components, but start components with app page
 - Want to get patterns production ready. What patterns? Where do we expect to implement them?
 - For a pattern in the library to be ready for production, it at least needs to be assigned the final classes that will be used in production
 - Patterns need to be in cg-style and have proper rules assigned to them
 - Classes may be new, or ones we already use, or modifications
 - If modifications, we need to make sure that these don't break existing components
 - Pulling from utility class "safe space" to production space without breaking things that already exist
 - Also need some documentation
 - Need to be reviewed (PR)
 - Low bar could be draft/WIP state. If more time, we could go to beta

**Comment by line47** [comment]
Current list of patterns in the pattern library:
(Checked items are marked `Ready` in the pattern library)

### Base
- [ ] Borders
- [ ] Colors
- [ ] Grid
- [ ] Line Height
- [ ] Opentype
- [ ] Spacing Scale
- [ ] Type Scale
- [ ] Typefaces

### Components
- [ ] Action
- [ ] Breadcrumb Nav
- [ ] Icon
- [ ] Icon Square
- [ ] Icon Ui
- [ ] Loading
- [ ] Status
- [ ] Status Pill
- [ ] Trigger

### Features
- [ ] Card
- [ ] Count Status
- [ ] Count Status Grid
- [ ] Page Header
- [ ] Panel
- [ ] Panel Overview Org
- [ ] Panel Your Orgs
- [ ] Tree View

**Comment by msecret** [comment]
Based on the [descriptions here](https://github.com/18F/cg-style/blob/master/fractal.js#L36), are these all actually ready? Do they have accessibility and usability checks and documentation?

**Comment by msecret** [comment]
I also dont think the goal of this story is moving things to ready, it's moving things out of `prototype`/`draft`.

**Comment by line47** [comment]
That is a good point @msecret I'll go back through the list and mark items as they are.

**Comment by line47** [comment]
I've updated the checklist above with the status of PL items.

**Comment by line47** [comment]
https://github.com/18F/cg-style/pull/272 for Actions and Breadcrumbs

**Comment by adborden** [comment]
https://github.com/18F/cg-style/pull/272 was merged :+1:
