### ISSUE TITLE
Change page headers to entity name only, possibly add simple breadcrumb

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#888]
Notes:
 - Want to change the styling to page header styling
 - Title goes to top
 - Aaron to take lead on this, pair with Dan to review
 - Fine-tune further if needed
 - Nice to have: on top of page title, display rudimentary breadcrumb (e.g. org/space/app with links)

The page header styles will resemble (but not quite match) the [original design here](https://gsa.invisionapp.com/share/8X8RHAOKS#/screens/208103400).

Acceptance criteria:
- [x] Each page had a header at the top of the body content
- [x] For applicable pages, an entity icon exists in the header
- [x] Component exists in the pattern library
- [x] (reach) simple breadcrumb above page header

**Comment by adborden** [comment]
@suprenant I took stab at the AC, does that make sense?

**Comment by suprenant** [comment]
@adborden yes, looks good, thank you. I like how you outlined the last item as a reach goal, as well.

**Comment by thisisdano** [comment]
This header/title should appear in the same spot that `Overview` appears on the dashboard overview — AND each header (including overview) should should get the appropriate large icon before it. 

![screen shot 2016-12-30 at 7 27 00 am](https://cloud.githubusercontent.com/assets/11464021/21568466/c2ada22c-ce69-11e6-9bde-60056ca45b83.png)

- - -

![titles-headers](https://cloud.githubusercontent.com/assets/11464021/21568538/5a1dff6c-ce6a-11e6-8b94-4f5c6dc25814.png)

**Comment by suprenant** [comment]
Looks good to me
