### ISSUE TITLE
Add some description/layout for 404 page

### ISSUE THREAD

**Issue by adborden** [18F/cg-dashboard#897]
404 page is especially confusing because there is no layout or content. 404s shouldn't really ever happen, so we might also want to include some context about how to get in touch with support.

![screenshot from 2016-12-30 10-52-14](https://cloud.githubusercontent.com/assets/509703/21570782/1d927744-ce7e-11e6-88eb-8be9e0a53f67.png)

Notes: 
 - A team member with strong templating skills should update this template

Acceptance criteria:
- [ ] There is a link to the Overview page (so users have somewhere to go)
- [ ] There is content about what happened and what the users options are
- [ ] There is a site header (so users understand they are still on the cloud.gov site)

**Comment by adborden** [comment]
Hmm, it looks like there are a handful of [special cases](https://github.com/18F/cg-product/issues/127#issuecomment-285533678) for 404s. For example, the app page will just display "No app" when the app doesn't exist.

https://dashboard.cloud.gov/#/org/4a962676-e687-46c4-95f4-7a83712065c6/spaces/aed2de1d-a8d2-43ad-a790-f3832f35bd33/apps/not-an-app

**Comment by adborden** [comment]
Hmm, for the special cases, instead of having empty state text, we should just show the 404 template.

**Comment by adborden** [comment]
Hmm, it might make sense to include "hints" as to why you got the 404 page. In the special case above, we could say:
> This resource might have been recently renamed or removed. Try looking for it in your [space/org].

Assuming we have an org/space fetched from the guids in the URL, we can create a link to the org/space of the app you just removed.

I have yet to investigate this, but in the case of a blue-green deployment with autopilot, _I think_ the app would be assigned a new guid, hence it would be available at a new URL. So if the user has the app page open and refreshed after a deployment, they might see "No app", which is confusing. Hopefully the above messaging would address that. (again, I have yet to confirm if this is the case with blue-green deployment).

**Comment by brittag** [comment]
I like the direction of that hint text! Is it possible to say "This application" instead of "This resource", to be specific?
