### ISSUE TITLE
Usage and allocation panel confusing when apps are in an inconsistent state

### ISSUE THREAD

**Issue by adborden** [18F/cg-dashboard#899]
The Stat component is used for displaying resources used as well as resources available. If some information is missing from the API (maybe because the app is in an unusual state), the Stat shows the wrong information. This app is running, but data is missing from the API.
![pasted_image_at_2016_12_30_10_06_am](https://cloud.githubusercontent.com/assets/509703/21570924/41240e10-ce7f-11e6-9d3f-1b7f8c36a563.png)

Notes from team discussion:
 - We're not getting data we’re supposed to get. Logic assumes that we’ll get usage data, but sometimes we don’t
 - The platform should return current usage data. When usage is zero, column is duplicated
 - We're seeing this in GovCloud, but not East/West

Implementation notes:
 - Check with Atlas for upstream fix (note that the upstream fix itself will not completely resolve this issue)
 - Present a design that assumes the bug will not be fixed, possibly with a conditional, such as this app is not available

Acceptance criteria:
 - [ ] First column displays usage information. If no data is available, NA is displayed
 - [ ] Second column displays allocation information. If no data is available, NA is displayed

**Comment by vz3** [comment]
Design should suggest a state for when we are unable to pull instance memory used. Something as simple as "N/A" is more useful than outputting an incorrect amount. cc @thisisdano

**Comment by adborden** [comment]
Here is a screenshot of a stopped app, this is also confusing.
![screenshot from 2017-01-03 10-49-14](https://cloud.githubusercontent.com/assets/509703/21619113/226298d0-d1a3-11e6-8ce6-6383a1111b6d.png)

**Comment by suprenant** [comment]
@adborden you mentioned that we're seeing this either in GovCloud or East/West, but not both. I missed writing down which one – can you please clarify?

**Comment by suprenant** [comment]
@adborden on review, it looks like it's GovCloud that shows the error. If that's not the case, please let me know. Otherwise, disregard!

**Comment by suprenant** [comment]
@adborden can we please pair on this or can you send a screenshot of the "If no data available" states" to accept? The rest of the changes here look good to me.

**Comment by suprenant** [comment]
Looks good to me!
