### ISSUE TITLE
GovCloud returns `0` for app usage stats

### ISSUE THREAD

**Issue by adborden** [18F/cg-dashboard#900]
https://gist.github.com/adborden/cce87e343274ed7158dab47bcabf5d52#L15

This is actually the root cause of this particular state in https://github.com/18F/cg-dashboard/issues/899 and breaks the usage and limits panel.

**Comment by adborden** [comment]
BTW, you can also see this manifest on the CLI, since we're using the same API. The app instances will show no usage.
```
$ govcloud app cg-dashboard
Showing health and status for app cg-dashboard in org cloud-gov / space dashboard-prod as aaron.borden@gsa.gov...
OK

requested state: started
instances: 1/1
usage: 256M x 1 instances
urls: dashboard.fr.cloud.gov
last uploaded: Fri Dec 30 00:40:03 UTC 2016
stack: cflinuxfs2
buildpack: go_buildpack

     state     since                    cpu    memory      disk      details
#0   running   2017-01-02 01:02:16 AM   0.0%   0 of 256M   0 of 1G
```

**Comment by suprenant** [comment]
@adborden looks like we're good here on the Atlas side. Can you please accept?

**Comment by jmcarp** [comment]
This just rolled out to production, and I confirmed that I can get app statistics via `cf curl`.
