### ISSUE TITLE
Total disk usage wraps poorly

### ISSUE THREAD

**Issue by adborden** [18F/cg-dashboard#901]
![screenshot from 2016-12-30 13-47-06](https://cloud.githubusercontent.com/assets/509703/21573194/8583f2ac-ce96-11e6-9391-a36d6db909c6.png)

**Comment by thisisdano** [comment]
Probably not an issue anymore

**Comment by adborden** [comment]
This looks like we have more space with the panel refactor. Plus the Total disk used secondary text was removed.
