### ISSUE TITLE
Sessions stored on disk

### ISSUE THREAD

**Issue by adborden** [18F/cg-dashboard#902]
We store sessions on disk using [gorilla/sessions](https://github.com/gorilla/sessions). That means that if you scale to more than one instance, each will have a different copy of the session. If you start the auth process on one and finish on another, the second instance will have no idea of the original session.

For example, when you scale to 2 instances for the dashboard, a user might not be able to complete the login because their `state` will appear empty to any instance that didn't start the session. If you land on another instance for the `/oauth2callback`, `state` (empty) won't match the request.

We'll have to setup some store to transparently handle sessions that isn't tied to the instance, e.g. redis.
cc @jmcarp

**Comment by sharms** [comment]
Hi! We should probably close one of these? https://github.com/18F/cg-dashboard/issues/751
