### ISSUE TITLE
Overview cards that have all data fetched should default to open

### ISSUE THREAD

**Issue by thisisdano** [18F/cg-dashboard#908]
To make the overview page more useful to users (largely managers), the overview cards containing the first ten spaces should default to open if all of the data has been fetched for the spaces in those orgs.

Acceptance criteria:
- [ ] If a user belongs to orgs with ten or fewer total spaces, all orgs should start in the open view
- [ ] If a user belongs to orgs with more than ten total spaces, the overview cards containing the first ten spaces should default to open, and any additional overview cards should default to closed

- - -

![screen shot 2017-01-03 at 10 00 51 am](https://cloud.githubusercontent.com/assets/11464021/21618194/9d5c2ef2-d19e-11e6-955d-5b4fe9978940.png)

**Comment by suprenant** [comment]
Updated after discussing with @msecret. Thinking there could also be separate followup work making it clearer for the user why some org cards might be open and others closed, and/or suggesting more clearly how cards can be open and closed.
