### ISSUE TITLE
Implement dashboard footer

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#911]
In order for org managers and developers to find global cloud.gov links and understand more about the dashboard site, there should be a footer based on the design.

Acceptance criteria:
- [x] The footer should contain links to cloud.gov home, contact, contributing (which should go to this repo).
- [x] The footer should contain information about what cloud.gov is and who created it.

[Design](https://gsa.invisionapp.com/d/main#/console/8652272/210294901/preview)

**Comment by line47** [comment]
@thisisdano has put some thought into the footer, see his comments here... https://github.com/18F/cg-dashboard/issues/712#issuecomment-261315674

**Comment by thisisdano** [comment]
from sketch file:

![footer--dashboard 2x](https://cloud.githubusercontent.com/assets/11464021/21658052/ce3c032c-d279-11e6-93d8-7c06f97ff7b5.png)

**Comment by adborden** [comment]
Looks good
