### ISSUE TITLE
Breadcrumb refinements

### ISSUE THREAD

**Issue by thisisdano** [18F/cg-dashboard#912]
We're simplifying the breadcrumb to make it clearer at each view.

Acceptance criteria:

- [x] remove the icons from the breadcrumb
- [x] output `overview` for the overview node of the breadcrumb

The styling changes are already addressed in https://github.com/18F/cg-style/pull/270 pull request.

- [x] each breadcrumb link should be underlined
- [x] the breadcrumb should be a bit bigger
- [x] slashes should be darker (@vz3 I know we talked about removing the trailing slash, but after looking at the change in the browser, I'd like to keep it...)

And it's getting this console error:

```
warning.js?0260:36 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Breadcrumbs`. See https://fb.me/react-warning-keys for more information.
    in div (created by Breadcrumbs)
    in Breadcrumbs (created by SpaceContainer)
    in div (created by SpaceContainer)
    in div (created by SpaceContainer)
    in div (created by SpaceContainer)
    in SpaceContainer
    in div (created by App)
    in main (created by App)
    in div (created by App)
    in div (created by App)
    in App
```

- - -

![screen shot 2017-01-04 at 10 20 57 am](https://cloud.githubusercontent.com/assets/11464021/21653767/99fa2d12-d267-11e6-816d-a714c616cf03.png)

**Comment by suprenant** [comment]
@thisisdano cool. Since there's no AC here, let's pair to accept when we meet later today.

**Comment by suprenant** [comment]
Talked this through – the above are AC, so I'll review accordingly.

**Comment by suprenant** [comment]
Looks good to me
