### ISSUE TITLE
Top header has a responsive size on smaller screens causing gutter

### ISSUE THREAD

**Issue by adborden** [18F/cg-dashboard#913]
At ~1000px, the top header shrinks while the content of the page is fixed and becomes scrollable. The effect is that there is a gutter on the right of the top header.

**at 900px**
![screenshot from 2017-01-04 10-39-30](https://cloud.githubusercontent.com/assets/509703/21654507/a5f2a95c-d26a-11e6-9033-11cdb8fdf603.png)

Acceptance criteria: 
 - [ ] Gutter is not displayed

**Comment by thisisdano** [comment]
Fixed in https://github.com/18F/cg-style/pull/270

**Comment by thisisdano** [comment]
Tho since this app isn't responsive, maybe we should remove the `width = device width` in the page header meta

**Comment by adborden** [comment]
Looks good at 900, 1000, 1200px.
