### ISSUE TITLE
When route edit form is open, cancel button appears disabled but should not be

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#914]
What we're after: display cancel/OK buttons here in a way to avoid confusing users.

Notes: 
 - Pattern library should have complete set of button states
 - OK state (hover) color: darker green
 - Cancel: base outline

![screen shot 2017-01-04 at 12 57 05 pm](https://cloud.githubusercontent.com/assets/1452369/21654948/6881bc6c-d27d-11e6-9f78-575e57944ddd.png)

Acceptance criteria:
 - [x] Cancel button is displayed in black with a black outline
 - [x] OK button is filled green

**Comment by adborden** [comment]
LGTM
