### ISSUE TITLE
Modify route, click OK, doesn’t work, click cancel, shows editing app indicator when an error has occurred

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#915]
What we're after: users trying to modify routes should either not be able to modify routes for which they do not have permissions and/or received clear errors for actions for which they don't have permissions or are otherwise invalid.

Notes: 
 - That this only happens when user doesn't have permission to modify a route
 - Display error where rest of errors are showing in UI
 - We'll need to review how permissions are currently working here

Possible fixes:
1. Users don't have access to change items they don't have permissions for
2. Correctly display error messages all the time

![screen shot 2017-01-04 at 12 57 05 pm](https://cloud.githubusercontent.com/assets/1452369/21654990/90d0fe12-d27d-11e6-91b9-7136690b2c3f.png)

Acceptance criteria:
 - [x] In the case that a modification is attempted without appropriate permissions, an error would be clearly visible

**Comment by suprenant** [comment]
Noting that we're going for option #2 above and will consider #1 if there's time.

**Comment by adborden** [comment]
Error appears correctly.
