### ISSUE TITLE
Fetching too many events on app page

### ISSUE THREAD

**Issue by adborden** [18F/cg-dashboard#916]
http://localhost:9999/#/org/48b3f8a1-ffe7-4aa8-8e85-94768d6bd250/spaces/82af0edb-8540-4064-82f2-d74df612b794/apps/2f684200-b9da-4ea6-a3c8-01a1df5ef2d3

I'm seeing all 45 pages for 2200 events being fetched and only 10 getting displayed. The page doesn't load until all the events have been fetched, which is completely unnecessary.

**Comment by thisisdano** [comment]
I can say this results in a very slow page load :)

**Comment by msecret** [comment]
The app page loader actually doesn't wait on the activity log data as seen here:

https://github.com/18F/cg-dashboard/blob/master/static_src/components/app_container.jsx#L47

so I would say this doesn't effect performance that much, but is still a bad practice to fetch so much information.
