### ISSUE TITLE
Fetching too many quotas

### ISSUE THREAD

**Issue by adborden** [18F/cg-dashboard#926]
We're fetching all the org quotas with `/quota_definitions`. This includes **every** quota that exists within the cloud foundry, not just the orgs you are a member of. As cloud.gov scales, this will mean slower performance for dashboard users.

A single quota can be fetched with `/quota_definitions/:guid`

**Comment by msecret** [comment]
The app page definitely waits on the quota store, so this could be effecting performance.

**Comment by msecret** [comment]
The question: how do we find the quota definition guid for a given org or space?

**Comment by adborden** [comment]
Hmm, it's on the organization and space endpoints, although I'm not sure when/if we're calling those.

**org**
https://apidocs.cloudfoundry.org/250/organizations/retrieve_a_particular_organization.html
`quota_definition_guid`

**space**
https://apidocs.cloudfoundry.org/250/spaces/retrieve_a_particular_space.html
`space_quota_definition_guid`
