### ISSUE TITLE
PI9 potential work: fake data for testing server

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#931]
The fake testing server is a node server that uses hand-crafted fake Cloud Foundry API data to provide data for the dashboard without requiring an actual CF API. This is currently being used to developer/test/interact with the dashboard without having to set up Golang and could be used for more comprehensive functional testing.

### Benefits
- Allow users to develop the dashboard easily without needing to set up go or a CF API. Would help future cloud.gov team as well as open source contributors.
- Unblock functional testing task, as fake data is required to correctly set up functional tests for the dashboard.

### Cost
Could be 5-20 days depending on what tasks are taken on.

### Individual tasks
| Task                                                                         | Reasoning/benefits                                                                                                                                                                        | Time estimation |
|------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------|
| Write JSON for all basic CF API GET responses                                |                                                                                                                                                                                           | 5-9 days        |
| Write logic and JSON for updating/deleting CF API responses                  | To allow for more in depth testing, there should be responses and logic for when user is editing things in their UI rather then just fetching data.                                       | 4-6 days        |
| Write JSON for error and edge cases                                          | Error conditions and certain edge cases can be very hard to reproduce with the actual Cloud Foundry API. Creating this data would ensure the team always has the tools to test for these. | 3-5 days        |
| Create tool to easily take CF API HTTP responses and format to editable JSON | Not required, might help out with the process of hand-crafting all the data.                                                                                                              | 4-8 days        |
| Tool for important large amounts of data                                     | Large amounts of data is an edge case in many places in the app that often goes untested.                                                                                                 | 5-9 days        |

### Notes
- Again, not all tasks have to be completed to provide value.

**Comment by elisechant** [comment]
@adborden where did you guys land with this? am building sameish thing down under

**Comment by adborden** [comment]
@elisechant a first version was recently merged. Does this work for you? https://github.com/18F/cg-dashboard/pull/945

**Comment by elisechant** [comment]
ahh... i see. Thanks @adborden.
