### ISSUE TITLE
Show more activity button not working

### ISSUE THREAD

**Issue by line47** [18F/cg-dashboard#940]
When clicking the `Show more activity` button in the Recent activity panel nothing happens.
This was observed on https://dashboard-staging.apps.cloud.gov 

### Steps to reproduce:
1. Navigate to an application page, will work better with a new app that doesn't ahve much activity.
2. Go to the Recent activity panel at the bottom of page
2a.Observe that theres a "Show more activity" button"
3. Click the `Show more activity` button
3a. Observe that nothing happens

### Acceptance Criteria:
- [ ] When there are 10 or less items of activity, the show more activity button should not be shown.
- [ ] When clicking the `Show more activity` button the next set of 10 activity items should be displayed.

**Comment by msecret** [comment]
This may be an issue where the Show more button is appearing when there is not any more activity to see.

**Comment by adborden** [comment]
https://github.com/18F/cg-dashboard/issues/940 is a duplicate.

**Comment by adborden** [comment]
I think there's an off-by-one error. When there are 10 items, the button appears, but clicking it shows nothing.

**Comment by adborden** [comment]
Also, when clicking it repeatedly, eventually no more events appear, but the button still shows and clicking it does nothing.
