### ISSUE TITLE
Research/implement unit testing for UI components

### ISSUE THREAD

**Issue by adborden** [18F/cg-dashboard#948]
React recommends the [Jest framework](https://facebook.github.io/jest/docs/tutorial-react.html#content), but we can look at other frameworks too. Right now our UI components have very little test coverage. We've been bitten by regressions in our UI components due to lack of coverage.

- [x] An example unit test for a single UI component so that others can implement new tests with little friction.

**Comment by msecret** [comment]
Something we should research and build into this first example: a unit test for a component that contains other components by not rending the sub components (supposedly there is a way to do this for testing conditions)

**Comment by adborden** [comment]
Looks like [Jest does not run in the browser](https://github.com/facebook/jest/issues/139), so any jest tests will be outside of our karma suite. I am okay with this, but might even suggest we ditch karma. If we have decent functional browser-based tests combined with non-browser unit tests then I see no reason to need a layer in between with karma.

**Comment by adborden** [comment]
Checking out [Enzyme](http://airbnb.io/enzyme/index.html) which supports the shallow rendering. So far so good.
