### ISSUE TITLE
Add link to the running app at top of app page

### ISSUE THREAD

**Issue by adborden** [18F/cg-dashboard#951]
[Invision screen](https://gsa.invisionapp.com/share/8X8RHAOKS#/screens/192169637)

In order for a developer to quickly see the running app at a URL, there should be a Open app button in the app page header.

Add an "Open app" action to the page header that opens the route of the application. In case the application is bound to multiple routes, we should use the first one as returned by the API.

![screenshot from 2017-01-12 16-42-22](https://cloud.githubusercontent.com/assets/509703/21914160/29e13f72-d8e6-11e6-9463-e6703c25b1ec.png)

- [ ] action button exists in page header titled open app
- [ ] action button opens the application route when clicked

**Comment by msecret** [comment]
Requires https://github.com/18F/cg-style/pull/290

**Comment by adborden** [comment]
Looks good.
