### ISSUE TITLE
Rethink and implement health states for application activity log

### ISSUE THREAD

**Issue by adborden** [18F/cg-dashboard#953]
From the [app walkthrough](https://docs.google.com/document/d/1Hx3QXfkmxdpX-rPxu3XNp2VRuGc8BaNryzshE43dPu0/edit) we identified some issues around the application activity log component.

### [3] Display more information/change states
Updating an app appears as a warning (gold). Maybe this shouldn’t be the case
Change messages so they’re more descriptive of what the action is

- [x] Only errors should have the status-pill
- [x] No status-pill for any other events (start/update), no ok or warning state at all

### [2] Not clear that activity entries are clickable and expandable

- [x] Entire row should be clickable for the expand target
- [x] Row should have better indication that it is clickable, make the hover cursor a pointer

### [2] Change language from ambiguous “updating” to something like modified the app resources

- [x] For the update event, change copy to "modified the application's resource allocation"

### [2] Add label describing the raw data upon expansion: “Event log”

- [x] When log event is expanded, add copy: "Raw event log"

### [3] “Show more activity” action

It does not do anything, should fetch the next set of events, should not be displayed if there are no longer any events to fetch (addressed in https://github.com/18F/cg-dashboard/issues/949)

- [x] “Show more activity” button should be outline style.

**Comment by adborden** [comment]
For the clickable indicator, not sure if we just need to change the pointer or if we need to add some kind of chevron/arrow.

**Comment by msecret** [comment]
Checking this out on demo (which has activity-log-ux branch), I found certain log entries are off in their left alignment. See screenshot.

Is that just from cg-style differences, or is it a problem?

**Comment by msecret** [comment]
Checked it out on staging, the UI thing isn't there.
