### ISSUE TITLE
Binding service to app fails with "app space binding to service is taken"

### ISSUE THREAD

**Issue by adborden** [18F/cg-dashboard#959]
> The app space binding to service is taken: 2f684200-b9da-4ea6-a3c8-01a1df5ef2d3 3f6b7712-3c72-48ff-9774-c7b0895c4489

Response
```
{
  "code": 90003,
  "description": "The app space binding to service is taken: 2f684200-b9da-4ea6-a3c8-01a1df5ef2d3 78f00930-8942-4d63-b8d7-38353c8d7818",
  "error_code": "CF-ServiceBindingAppServiceTaken"
}
```

Also the formatting is off
![screenshot from 2017-01-17 10-53-12](https://cloud.githubusercontent.com/assets/509703/22035056/6cbb2798-dca3-11e6-84d6-a2263a5db380.png)
- [ ] Indicator should disappear
- [ ] Bind button should re-appear in the disabled state.

Repro
1. Create a service in the marketplace
2. Bind the service on the application page

Expected
Service is bound successfully, appears under bound services

Actual
Error appears, indicator never leaves

**Comment by adborden** [comment]
Also, it looks like the bind actually succeeds despite the 400.

```
$ cf services
Getting services in org cf-deck-testing / space dev as aaron.borden@gsa.gov...
OK

name                 service   plan          bound apps      last operation
sfsdsdsdsdsdsd-rds   rds       shared-psql   adborden-node   create succeeded
abcdef               rds       shared-psql   adborden-node   create succeeded
```

And the services now appear in the "Bound services" section of the panel.

**Comment by brittag** [comment]
I just ran into something similar on staging:

![screen shot 2017-01-27 at 5 28 08 pm](https://cloud.githubusercontent.com/assets/391313/22393326/19d4fdc4-e4b9-11e6-8008-33b58ad494d8.png)

I got an error message (which was ok) but the "binding" indicator stayed there, which was confusing.

**Comment by adborden** [comment]
https://github.com/18F/cg-dashboard/issues/960 was meant to capture this kind of thing, where an error happens and then the user just falls off a cliff because they have no instruction on what to do and the UI state itself is in a confusing state.

**Comment by adborden** [comment]
Hmm, I just realized the AC on this story refers to clearing the indicator but I don't think it quite makes sense as written. @brittag is there an interaction that you would expect to see here?

To me, it sounds like there are at least a couple options but blurs into design questions for me. Either we do something like what https://github.com/18F/cg-dashboard/issues/991 is asking for, where after an error/success, the user has to clear the messaging somehow. Or we give better instruction to refresh the page within the existing error messaging.

**Comment by brittag** [comment]
In my specific experience noted above, I would have simply expected the "binding..." indicator to disappear when the error message popped up.

There's a second problem, that the appropriate next step isn't clear, but to me that's a separate issue - an enhancement rather this issue (which I consider a bug).

**Comment by msecret** [comment]
There is technically a next step being given: "Please wait and try again...". Is that really what will fix the problem though?

**Comment by adborden** [comment]
My main issue with this is the "Please wait and try again", isn't possible because the action links are gone. You can't try again without refreshing the page and that is not obvious.

**Comment by brittag** [comment]
Yeah, "Please wait and try again" is unclear since it's vague. It could be "This instance should become available in a moment, so refresh the page and try again."

Adding more words would mean this error design should get updated, since it's getting long. Can it be on two lines (one for "service broker error: x" and one for "error: x"), with different text alignment? (It's bit odd looking right now with the right-alignment.)

**Comment by suprenant** [comment]
Trying this now but having trouble binding services on my hello world app. Will review with the team.

**Comment by suprenant** [comment]
Planning some followup work related to service instance bugs, so closing this up. If this persists, please let Customer team know!
