### ISSUE TITLE
Errors from user actions should clear forms and give user guidance

### ISSUE THREAD

**Issue by adborden** [18F/cg-dashboard#960]
There's a lot of places where an user-triggered action fails, but the indicator and UI state don't reset. It's clear that something went wrong, but it is now confusing what state things are in. There are several examples of this.

The form should still be available in an error condition so that the user can possible change their inputs to resolve the error. Clicking "Cancel" should reset the form and refresh the state so that the user understands what state the UI is in.

Acceptance Criteria
- [ ] Display error until user clears it by clicking "Cancel" or equivalent action
- [ ] Clicking "cancel" should clear error and refresh the UI state
- [ ] On unhandled error, the user should be prompted to refresh the page.

**Comment by adborden** [comment]
We'll also want to address [the case where there is no cancel button](https://github.com/18F/cg-dashboard/issues/959#issuecomment-275818481). Here's an example where the user triggers an action, then sees an indicator that the action is in progress. Then the error occurs, but the state doesn't reset. The user has no where left to go except to refresh the page.

![screen shot 2017-01-27 at 5 28 08 pm](https://cloud.githubusercontent.com/assets/391313/22393326/19d4fdc4-e4b9-11e6-8008-33b58ad494d8.png)

**Comment by adborden** [comment]
We are planning to implement https://github.com/18F/cg-dashboard/issues/687 in the near future, I think it will address the case with no "Cancel" button because it instructs the user to refresh the page.

**Comment by adborden** [comment]
Hmm, on second thought, the banner is really meant for unhandled errors. It might make most sense to adjust the error message here to hint to the user that they should refresh the page.

**Comment by msecret** [comment]
I definitely think the binding loader should be removed. In terms of that problem, forms not clearing correctly, is this an isolated incident or are there other cases of this? 

I'm a little concerned of scope of going through every cloud foundry error message and writing our own guidance. That could be a large task and probably requires somebody with design/content experience.
