### ISSUE TITLE
Update Organization overview copy

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#966]
Review this copy, especially “A few things you can do here” - suspect that it's outdated and should be updated or removed

![screen shot 2017-01-20 at 7 34 45 pm](https://cloud.githubusercontent.com/assets/1452369/22170724/97a5118e-df47-11e6-917a-0e12b563c58b.png)

**Comment by adborden** [comment]
That copy looks accurate to me. I don't have any ideas for updating it. Do you have something specific you think should be updated @suprenant?

**Comment by suprenant** [comment]
@brittag can you please tell us if you had specific thoughts for changes here?

**Comment by brittag** [comment]
Ah thanks! I recommend updating "A few things you can do here" with the newer features, for example:

* Change memory allocation and number of instances for apps.
* Restart apps.

I'm not sure whether this list it's useful in its current format, but it doesn't hurt to update it for now.
