### ISSUE TITLE
Write copy for Organization and Space users

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#967]
This copy was written in July 2016 when the current checkboxes weren't really functioning. This content should be updated.

![screen shot 2017-01-20 at 7 37 38 pm](https://cloud.githubusercontent.com/assets/1452369/22170776/faf6abbc-df47-11e6-8a2f-a42d9efc4c41.png)

![screen shot 2017-01-20 at 7 39 10 pm](https://cloud.githubusercontent.com/assets/1452369/22170787/287490d6-df48-11e6-9141-09610ce132cc.png)

**Comment by adborden** [comment]
@suprenant can you clarify what the copy should be?

**Comment by suprenant** [comment]
@adborden I'm not exactly sure. Writing that would be part of this story.

**Comment by adborden** [comment]
OK, updated the title. Kicking this back to icebox.
