### ISSUE TITLE
Update Marketplace copy

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#968]
This content on the Space page is out of date and should be updated.

![screen shot 2017-01-20 at 7 40 09 pm](https://cloud.githubusercontent.com/assets/1452369/22170813/6029ada4-df48-11e6-85ff-37a6da251921.png)

- [ ] Update copy as per https://github.com/18F/cg-dashboard/issues/968#issuecomment-275290092

**Comment by adborden** [comment]
I suggest updating this as:
> Use this marketplace to create service instances for apps in this space. Then bind service instances to an app from the app page or using the command line. [Learn about using service instances and marketplaces].
