### ISSUE TITLE
Update Create service instance copy

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#969]
This content is out of date and should be updated:

_After you create a service instance, you can look at your space to check whether your service instance was created. (We’ll make this better.) Then you can bind the service instance to an app using the command line._

![screen shot 2017-01-20 at 7 42 00 pm](https://cloud.githubusercontent.com/assets/1452369/22170831/96f100da-df48-11e6-9063-c04365f32793.png)

- [ ] Remove the copy for now

**Comment by adborden** [comment]
I'm trying to come up with some updated copy, but I think the easier thing to do is just remove the text all together.

**Comment by adborden** [comment]
_If_ there was a page about binding apps in docs.cloud.gov, we could link to that. Is that the route we want to go down?

**Comment by msecret** [comment]
I think we should just remove the text for now.

**Comment by msecret** [comment]
Moving this to https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-2993 as it's too small of a story on its own.
