### ISSUE TITLE
Make link styles consistent on Space page

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#970]
The attached shows that the link (and content) styles on the Space page are not consistent and should be reviewed and updated. 

![screen shot 2017-01-20 at 7 43 19 pm](https://cloud.githubusercontent.com/assets/1452369/22170841/c2bed340-df48-11e6-9f64-95ed9f9e55c6.png)

**Comment by adborden** [comment]
This also applies to the Overview cheatsheet.

![screenshot from 2017-01-25 18-01-53](https://cloud.githubusercontent.com/assets/509703/22317420/694755ba-e328-11e6-80e1-d858c80dce22.png)
