### ISSUE TITLE
Fake service appearing in dashboard

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#975]
From @brittag:
_I still see that fake service issue on E/W dashboard -> overview -> sandbox -> britta.gustafson -> scroll to bottom of page_
_I don't see it in GovCloud dashboard_
_I do see it in E/W dashboard -> overview -> sandbox-gsa -> britta.gustafson -> scroll to bottom of page_

![screen shot 2017-01-05 at 12 39 54 pm](https://cloud.githubusercontent.com/assets/1452369/22257822/cbad68c0-e224-11e6-8dbd-1a0a62076963.png)

**Comment by msecret** [comment]
I don't think we can do anything about this from the navigator side, this sounds like an agent-q issue. From the navigator side, we just consume the API data which includes this service.

**Comment by msecret** [comment]
@suprenant can you move this issue to another team?

**Comment by suprenant** [comment]
@msecret sure, I'll move it to AgentQ, thanks. cc @mogul
