### ISSUE TITLE
Routes under App Dashboard

### ISSUE THREAD

**Issue by johangithub** [18F/cg-dashboard#976]
Hello,

The link within Bound routes section under App Dashboard directs me to 

https://<span></span>dashboard.fr.cloud.gov/<APPNAME\>.app.cloud.gov

instead of 

<APPNAME\>.app.cloud.gov

https://github.com/18F/cg-dashboard/blob/master/static_src/components/route.jsx

**Comment by adborden** [comment]
Thank you for the report!

**Comment by adborden** [comment]
This has been fixed but won't go out until our next deploy sometime next week.
