### ISSUE TITLE
Rotate UAA Client ID for govcloud

### ISSUE THREAD

**Issue by adborden** [18F/cg-dashboard#989]
We've added a new client ID for our UAA OAuth2 app which needs to be rotated. See @LinuxBozo for questions.

- [x] `CONSOLE_CLIENT_ID`  is updated in `stage`
- [x] `CONSOLE_CLIENT_ID`  is updated in `prod`
- [ ] Remove `deck-ups` once released

**Comment by msecret** [comment]
Do we need to update these IDs in our local configurations?

**Comment by LinuxBozo** [comment]
If you are using the `18f-console` client id, yes.

**Comment by adborden** [comment]
Our dev instances are configured for E/W where the client_id should still be `18f-console`, right?

**Comment by LinuxBozo** [comment]
@adborden Correct. I talked with @msecret earlier. E/W config (and local dev) remains unchanged as we're moving closer to shutting it down entirely.
