### ISSUE TITLE
After user clicks "Create service instance", the success message disappears too fast

### ISSUE THREAD

**Issue by brittag** [18F/cg-dashboard#991]
In order for a cloud.gov user to understand that they successfully created a service instance, they should get a feedback message that they can see even if they read slowly or get distracted (such as if they are busy working on multiple things at once).

This is a followup on https://github.com/18F/cg-dashboard/issues/457#issuecomment-265236794 - right now when you create a service instance, the confirmation of success disappears after only a few seconds. It should stick around until it gets dismissed. This is an accessibility and usability issue.

Also the created message gets a few extra capital letters due to styling (they're not in [the code here](https://github.com/18F/cg-dashboard/blob/master/static_src/components/create_service_instance.jsx)), which is just a cosmetic issue, but the text color contrast might need checking (medium green on light blue-green).

![screen shot 2017-01-27 at 5 24 49 pm](https://cloud.githubusercontent.com/assets/391313/22393083/1160b6ae-e4b6-11e6-859a-5b15ec11fc0c.png)

**Comment by brittag** [comment]
There's an additional problem here now, that it shows a "cancel" button after the "created" message, and I'm not sure what the "cancel" button would do if I clicked it. Would it undo the creation of the service instance?

**Comment by suprenant** [comment]
Deprioritizing this for now given it's generally developer-facing and we have more urgent work to do.
